// Copyright (c) PRO-Robotech
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: kacho/cloud/storage/v1/internal_storage_backend_service.proto

package storagev1

import (
	_ "github.com/PRO-Robotech/kacho/pkg/api/kacho/iam/authz/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Род бэкенда — закрытый перечень, а не свободная строка.
//
// За каждым значением стоит адаптер в нашем коде. Свободная строка позволила бы
// зарегистрировать бэкенд, исполнять который некому: регистрация прошла бы, а
// первый же том упёрся бы в отсутствующего исполнителя — то есть отказ переехал
// бы с пути администратора на путь арендатора.
type StorageBackend_BackendKind int32

const (
	StorageBackend_BACKEND_KIND_UNSPECIFIED StorageBackend_BackendKind = 0
	// Ceph RBD — первый и пока единственный адаптер.
	StorageBackend_CEPH_RBD StorageBackend_BackendKind = 1
)

// Enum value maps for StorageBackend_BackendKind.
var (
	StorageBackend_BackendKind_name = map[int32]string{
		0: "BACKEND_KIND_UNSPECIFIED",
		1: "CEPH_RBD",
	}
	StorageBackend_BackendKind_value = map[string]int32{
		"BACKEND_KIND_UNSPECIFIED": 0,
		"CEPH_RBD":                 1,
	}
)

func (x StorageBackend_BackendKind) Enum() *StorageBackend_BackendKind {
	p := new(StorageBackend_BackendKind)
	*p = x
	return p
}

func (x StorageBackend_BackendKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StorageBackend_BackendKind) Descriptor() protoreflect.EnumDescriptor {
	return file_kacho_cloud_storage_v1_internal_storage_backend_service_proto_enumTypes[0].Descriptor()
}

func (StorageBackend_BackendKind) Type() protoreflect.EnumType {
	return &file_kacho_cloud_storage_v1_internal_storage_backend_service_proto_enumTypes[0]
}

func (x StorageBackend_BackendKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StorageBackend_BackendKind.Descriptor instead.
func (StorageBackend_BackendKind) EnumDescriptor() ([]byte, []int) {
	return file_kacho_cloud_storage_v1_internal_storage_backend_service_proto_rawDescGZIP(), []int{0, 0}
}

// Полоса действия бэкенда. Три состояния, потому что вывод из обращения —
// процесс, а не событие: тома живут дольше решения администратора о бэкенде.
type StorageBackend_Status int32

const (
	StorageBackend_STATUS_UNSPECIFIED StorageBackend_Status = 0
	// Принимает новые привязки и исполняет существующие.
	StorageBackend_ACTIVE StorageBackend_Status = 1
	// Новые привязки создавать нельзя, существующие исполняются. Это и есть штатный
	// способ вывести бэкенд: удаление невозможно, пока на него ссылаются ревизии.
	StorageBackend_DRAINING StorageBackend_Status = 2
	// Выведен из обращения: не принимает ни новых привязок, ни работы по
	// существующим. Строка сохраняется, потому что на неё ссылаются ревизии, а они
	// неизменяемы.
	StorageBackend_DISABLED StorageBackend_Status = 3
)

// Enum value maps for StorageBackend_Status.
var (
	StorageBackend_Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "ACTIVE",
		2: "DRAINING",
		3: "DISABLED",
	}
	StorageBackend_Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"ACTIVE":             1,
		"DRAINING":           2,
		"DISABLED":           3,
	}
)

func (x StorageBackend_Status) Enum() *StorageBackend_Status {
	p := new(StorageBackend_Status)
	*p = x
	return p
}

func (x StorageBackend_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StorageBackend_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_kacho_cloud_storage_v1_internal_storage_backend_service_proto_enumTypes[1].Descriptor()
}

func (StorageBackend_Status) Type() protoreflect.EnumType {
	return &file_kacho_cloud_storage_v1_internal_storage_backend_service_proto_enumTypes[1]
}

func (x StorageBackend_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StorageBackend_Status.Descriptor instead.
func (StorageBackend_Status) EnumDescriptor() ([]byte, []int) {
	return file_kacho_cloud_storage_v1_internal_storage_backend_service_proto_rawDescGZIP(), []int{0, 1}
}

// StorageBackend — зарегистрированный бэкенд блочного хранения (internal-only).
//
// Регистрация — это утверждение «вот чем мы умеем исполнять хранение и где». Она
// НЕ несёт устройства бэкенда: ни адресов мониторов, ни пулов, ни топологии. Пул и
// шаблон изоляции арендатора живут в ревизии привязки [DiskTypeBinding], потому что
// они меняются вместе с политикой класса, а не вместе с самим бэкендом.
type StorageBackend struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID бэкенда. Префикс `sb-` (дефисный канон), присваивается на Create,
	// неизменяем на всю жизнь записи.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Человекочитаемое имя. Косметический ярлык: уникально в реестре, но адресацию не
	// несёт и меняться вправе свободно.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Род бэкенда. Неизменяем после Create — см. комментарий к [Update].
	Kind StorageBackend_BackendKind `protobuf:"varint,3,opt,name=kind,proto3,enum=kacho.cloud.storage.v1.StorageBackend_BackendKind" json:"kind,omitempty"`
	// Описание для администратора. 0-256 символов.
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// Зоны, которые этот бэкенд обслуживает. Ревизия привязки создаётся только на
	// зону из этого списка — иначе класс объявлялся бы в зоне, где исполнять его
	// некому.
	ZoneIds []string `protobuf:"bytes,5,rep,name=zone_ids,json=zoneIds,proto3" json:"zone_ids,omitempty"`
	// Непрозрачная координата бэкенда: `<схема>://<путь>`.
	//
	// В API НЕ кладутся ни адреса мониторов, ни имена пулов, ни любая иная физика —
	// схема разрешается конфигурацией процесса, которая и знает, куда идти. Форма
	// «схема://путь» выбрана не для красоты: она делает запрет проверяемым. Голый
	// `host:port` под неё не подходит, а именно он и был бы адресом монитора,
	// просочившимся в контракт.
	Endpoint string `protobuf:"bytes,6,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	// ССЫЛКА на учётные данные, никогда само значение: `<схема>://<путь>`.
	//
	// Секрет не проходит через API и не хранится в нашей БД — процесс разрешает
	// ссылку у хранилища секретов при старте. Причина прямая: то, что прошло через
	// запрос, попадает в журналы, трассировки и ответы, а то, чего у нас нет, нельзя
	// выдать ни ошибкой, ни утечкой проекции. Область и ротация учётных данных —
	// ответственность хранилища секретов, а не наша.
	CredentialsRef string `protobuf:"bytes,7,opt,name=credentials_ref,json=credentialsRef,proto3" json:"credentials_ref,omitempty"`
	// Текущая полоса действия. Задаётся администратором явно (в том числе на Create):
	// бэкенд регистрируют и до того, как он готов принимать привязки.
	Status StorageBackend_Status `protobuf:"varint,8,opt,name=status,proto3,enum=kacho.cloud.storage.v1.StorageBackend_Status" json:"status,omitempty"`
	// Отметка создания. Усечена до секунд на проводе.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Отметка последнего изменения. Усечена до секунд на проводе.
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageBackend) Reset() {
	*x = StorageBackend{}
	mi := &file_kacho_cloud_storage_v1_internal_storage_backend_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageBackend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageBackend) ProtoMessage() {}

func (x *StorageBackend) ProtoReflect() protoreflect.Message {
	mi := &file_kacho_cloud_storage_v1_internal_storage_backend_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageBackend.ProtoReflect.Descriptor instead.
func (*StorageBackend) Descriptor() ([]byte, []int) {
	return file_kacho_cloud_storage_v1_internal_storage_backend_service_proto_rawDescGZIP(), []int{0}
}

func (x *StorageBackend) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StorageBackend) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StorageBackend) GetKind() StorageBackend_BackendKind {
	if x != nil {
		return x.Kind
	}
	return StorageBackend_BACKEND_KIND_UNSPECIFIED
}

func (x *StorageBackend) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *StorageBackend) GetZoneIds() []string {
	if x != nil {
		return x.ZoneIds
	}
	return nil
}

func (x *StorageBackend) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *StorageBackend) GetCredentialsRef() string {
	if x != nil {
		return x.CredentialsRef
	}
	return ""
}

func (x *StorageBackend) GetStatus() StorageBackend_Status {
	if x != nil {
		return x.Status
	}
	return StorageBackend_STATUS_UNSPECIFIED
}

func (x *StorageBackend) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *StorageBackend) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateStorageBackendRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Имя бэкенда. Уникально в реестре.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Род бэкенда. Обязателен: неуказанный род — это регистрация без исполнителя.
	Kind StorageBackend_BackendKind `protobuf:"varint,2,opt,name=kind,proto3,enum=kacho.cloud.storage.v1.StorageBackend_BackendKind" json:"kind,omitempty"`
	// Описание для администратора.
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Зоны, которые бэкенд обслуживает. Каждая валидируется peer-вызовом kacho-geo на
	// пути запроса, fail-closed: непроверенная зона означала бы привязку, которую
	// никто не исполнит.
	ZoneIds []string `protobuf:"bytes,4,rep,name=zone_ids,json=zoneIds,proto3" json:"zone_ids,omitempty"`
	// Непрозрачная координата бэкенда, форма `<схема>://<путь>`.
	Endpoint string `protobuf:"bytes,5,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	// Ссылка на учётные данные, форма `<схема>://<путь>`. Значение, не похожее на
	// ссылку (в том числе сам секрет), отвергается `INVALID_ARGUMENT` — так материал
	// секрета не доезжает ни до журнала, ни до колонки.
	CredentialsRef string `protobuf:"bytes,6,opt,name=credentials_ref,json=credentialsRef,proto3" json:"credentials_ref,omitempty"`
	// Полоса действия при регистрации. Опущено — `ACTIVE`.
	Status        StorageBackend_Status `protobuf:"varint,7,opt,name=status,proto3,enum=kacho.cloud.storage.v1.StorageBackend_Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStorageBackendRequest) Reset() {
	*x = CreateStorageBackendRequest{}
	mi := &file_kacho_cloud_storage_v1_internal_storage_backend_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStorageBackendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStorageBackendRequest) ProtoMessage() {}

func (x *CreateStorageBackendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kacho_cloud_storage_v1_internal_storage_backend_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStorageBackendRequest.ProtoReflect.Descriptor instead.
func (*CreateStorageBackendRequest) Descriptor() ([]byte, []int) {
	return file_kacho_cloud_storage_v1_internal_storage_backend_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateStorageBackendRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateStorageBackendRequest) GetKind() StorageBackend_BackendKind {
	if x != nil {
		return x.Kind
	}
	return StorageBackend_BACKEND_KIND_UNSPECIFIED
}

func (x *CreateStorageBackendRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateStorageBackendRequest) GetZoneIds() []string {
	if x != nil {
		return x.ZoneIds
	}
	return nil
}

func (x *CreateStorageBackendRequest) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *CreateStorageBackendRequest) GetCredentialsRef() string {
	if x != nil {
		return x.CredentialsRef
	}
	return ""
}

func (x *CreateStorageBackendRequest) GetStatus() StorageBackend_Status {
	if x != nil {
		return x.Status
	}
	return StorageBackend_STATUS_UNSPECIFIED
}

type GetStorageBackendRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID бэкенда, о котором спрашивают.
	StorageBackendId string `protobuf:"bytes,1,opt,name=storage_backend_id,json=storageBackendId,proto3" json:"storage_backend_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetStorageBackendRequest) Reset() {
	*x = GetStorageBackendRequest{}
	mi := &file_kacho_cloud_storage_v1_internal_storage_backend_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStorageBackendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStorageBackendRequest) ProtoMessage() {}

func (x *GetStorageBackendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kacho_cloud_storage_v1_internal_storage_backend_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStorageBackendRequest.ProtoReflect.Descriptor instead.
func (*GetStorageBackendRequest) Descriptor() ([]byte, []int) {
	return file_kacho_cloud_storage_v1_internal_storage_backend_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetStorageBackendRequest) GetStorageBackendId() string {
	if x != nil {
		return x.StorageBackendId
	}
	return ""
}

type ListStorageBackendsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Максимальное число записей на странице.
	PageSize int64 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Курсор страницы: значение [ListStorageBackendsResponse.next_page_token] из
	// предыдущего ответа.
	PageToken     string `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStorageBackendsRequest) Reset() {
	*x = ListStorageBackendsRequest{}
	mi := &file_kacho_cloud_storage_v1_internal_storage_backend_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStorageBackendsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStorageBackendsRequest) ProtoMessage() {}

func (x *ListStorageBackendsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kacho_cloud_storage_v1_internal_storage_backend_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStorageBackendsRequest.ProtoReflect.Descriptor instead.
func (*ListStorageBackendsRequest) Descriptor() ([]byte, []int) {
	return file_kacho_cloud_storage_v1_internal_storage_backend_service_proto_rawDescGZIP(), []int{3}
}

func (x *ListStorageBackendsRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListStorageBackendsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListStorageBackendsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Страница реестра.
	StorageBackends []*StorageBackend `protobuf:"bytes,1,rep,name=storage_backends,json=storageBackends,proto3" json:"storage_backends,omitempty"`
	// Курсор следующей страницы. Пуст, когда страница последняя.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStorageBackendsResponse) Reset() {
	*x = ListStorageBackendsResponse{}
	mi := &file_kacho_cloud_storage_v1_internal_storage_backend_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStorageBackendsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStorageBackendsResponse) ProtoMessage() {}

func (x *ListStorageBackendsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kacho_cloud_storage_v1_internal_storage_backend_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStorageBackendsResponse.ProtoReflect.Descriptor instead.
func (*ListStorageBackendsResponse) Descriptor() ([]byte, []int) {
	return file_kacho_cloud_storage_v1_internal_storage_backend_service_proto_rawDescGZIP(), []int{4}
}

func (x *ListStorageBackendsResponse) GetStorageBackends() []*StorageBackend {
	if x != nil {
		return x.StorageBackends
	}
	return nil
}

func (x *ListStorageBackendsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type UpdateStorageBackendRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID правимого бэкенда.
	StorageBackendId string `protobuf:"bytes,1,opt,name=storage_backend_id,json=storageBackendId,proto3" json:"storage_backend_id,omitempty"`
	// Новое имя.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Новое описание.
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Новый список обслуживаемых зон (замена целиком, не слияние).
	ZoneIds []string `protobuf:"bytes,4,rep,name=zone_ids,json=zoneIds,proto3" json:"zone_ids,omitempty"`
	// Новая координата бэкенда.
	Endpoint string `protobuf:"bytes,5,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	// Новая ссылка на учётные данные (ротация ссылки, не секрета).
	CredentialsRef string `protobuf:"bytes,6,opt,name=credentials_ref,json=credentialsRef,proto3" json:"credentials_ref,omitempty"`
	// Новая полоса действия.
	Status StorageBackend_Status `protobuf:"varint,7,opt,name=status,proto3,enum=kacho.cloud.storage.v1.StorageBackend_Status" json:"status,omitempty"`
	// Какие поля применить.
	//
	// Маска с неизвестным полем — `INVALID_ARGUMENT`; маска с `kind` —
	// `"kind is immutable after StorageBackend.Create"`, причём проверка
	// неизменяемости идёт ПЕРВОЙ, иначе `kind` вернулся бы обезличенным «unknown
	// field» вместо конвенционного текста. Пустая маска — правка всех изменяемых
	// полей из тела.
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,8,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStorageBackendRequest) Reset() {
	*x = UpdateStorageBackendRequest{}
	mi := &file_kacho_cloud_storage_v1_internal_storage_backend_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStorageBackendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStorageBackendRequest) ProtoMessage() {}

func (x *UpdateStorageBackendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kacho_cloud_storage_v1_internal_storage_backend_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStorageBackendRequest.ProtoReflect.Descriptor instead.
func (*UpdateStorageBackendRequest) Descriptor() ([]byte, []int) {
	return file_kacho_cloud_storage_v1_internal_storage_backend_service_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateStorageBackendRequest) GetStorageBackendId() string {
	if x != nil {
		return x.StorageBackendId
	}
	return ""
}

func (x *UpdateStorageBackendRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateStorageBackendRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateStorageBackendRequest) GetZoneIds() []string {
	if x != nil {
		return x.ZoneIds
	}
	return nil
}

func (x *UpdateStorageBackendRequest) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *UpdateStorageBackendRequest) GetCredentialsRef() string {
	if x != nil {
		return x.CredentialsRef
	}
	return ""
}

func (x *UpdateStorageBackendRequest) GetStatus() StorageBackend_Status {
	if x != nil {
		return x.Status
	}
	return StorageBackend_STATUS_UNSPECIFIED
}

func (x *UpdateStorageBackendRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type DeleteStorageBackendRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID снимаемого с регистрации бэкенда.
	StorageBackendId string `protobuf:"bytes,1,opt,name=storage_backend_id,json=storageBackendId,proto3" json:"storage_backend_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DeleteStorageBackendRequest) Reset() {
	*x = DeleteStorageBackendRequest{}
	mi := &file_kacho_cloud_storage_v1_internal_storage_backend_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteStorageBackendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteStorageBackendRequest) ProtoMessage() {}

func (x *DeleteStorageBackendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kacho_cloud_storage_v1_internal_storage_backend_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteStorageBackendRequest.ProtoReflect.Descriptor instead.
func (*DeleteStorageBackendRequest) Descriptor() ([]byte, []int) {
	return file_kacho_cloud_storage_v1_internal_storage_backend_service_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteStorageBackendRequest) GetStorageBackendId() string {
	if x != nil {
		return x.StorageBackendId
	}
	return ""
}

type DeleteStorageBackendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteStorageBackendResponse) Reset() {
	*x = DeleteStorageBackendResponse{}
	mi := &file_kacho_cloud_storage_v1_internal_storage_backend_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteStorageBackendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteStorageBackendResponse) ProtoMessage() {}

func (x *DeleteStorageBackendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kacho_cloud_storage_v1_internal_storage_backend_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteStorageBackendResponse.ProtoReflect.Descriptor instead.
func (*DeleteStorageBackendResponse) Descriptor() ([]byte, []int) {
	return file_kacho_cloud_storage_v1_internal_storage_backend_service_proto_rawDescGZIP(), []int{7}
}

var File_kacho_cloud_storage_v1_internal_storage_backend_service_proto protoreflect.FileDescriptor

const file_kacho_cloud_storage_v1_internal_storage_backend_service_proto_rawDesc = "" +
	"\n" +
	"=kacho/cloud/storage/v1/internal_storage_backend_service.proto\x12\x16kacho.cloud.storage.v1\x1a\x1cgoogle/api/annotations.proto\x1a google/protobuf/field_mask.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a&kacho/iam/authz/v1/authz_options.proto\"\xc0\x04\n" +
	"\x0eStorageBackend\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12F\n" +
	"\x04kind\x18\x03 \x01(\x0e22.kacho.cloud.storage.v1.StorageBackend.BackendKindR\x04kind\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x19\n" +
	"\bzone_ids\x18\x05 \x03(\tR\azoneIds\x12\x1a\n" +
	"\bendpoint\x18\x06 \x01(\tR\bendpoint\x12'\n" +
	"\x0fcredentials_ref\x18\a \x01(\tR\x0ecredentialsRef\x12E\n" +
	"\x06status\x18\b \x01(\x0e2-.kacho.cloud.storage.v1.StorageBackend.StatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"9\n" +
	"\vBackendKind\x12\x1c\n" +
	"\x18BACKEND_KIND_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bCEPH_RBD\x10\x01\"H\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06ACTIVE\x10\x01\x12\f\n" +
	"\bDRAINING\x10\x02\x12\f\n" +
	"\bDISABLED\x10\x03\"\xc2\x02\n" +
	"\x1bCreateStorageBackendRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12F\n" +
	"\x04kind\x18\x02 \x01(\x0e22.kacho.cloud.storage.v1.StorageBackend.BackendKindR\x04kind\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x19\n" +
	"\bzone_ids\x18\x04 \x03(\tR\azoneIds\x12\x1a\n" +
	"\bendpoint\x18\x05 \x01(\tR\bendpoint\x12'\n" +
	"\x0fcredentials_ref\x18\x06 \x01(\tR\x0ecredentialsRef\x12E\n" +
	"\x06status\x18\a \x01(\x0e2-.kacho.cloud.storage.v1.StorageBackend.StatusR\x06status\"H\n" +
	"\x18GetStorageBackendRequest\x12,\n" +
	"\x12storage_backend_id\x18\x01 \x01(\tR\x10storageBackendId\"X\n" +
	"\x1aListStorageBackendsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x03R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"\x98\x01\n" +
	"\x1bListStorageBackendsResponse\x12Q\n" +
	"\x10storage_backends\x18\x01 \x03(\v2&.kacho.cloud.storage.v1.StorageBackendR\x0fstorageBackends\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\xe5\x02\n" +
	"\x1bUpdateStorageBackendRequest\x12,\n" +
	"\x12storage_backend_id\x18\x01 \x01(\tR\x10storageBackendId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x19\n" +
	"\bzone_ids\x18\x04 \x03(\tR\azoneIds\x12\x1a\n" +
	"\bendpoint\x18\x05 \x01(\tR\bendpoint\x12'\n" +
	"\x0fcredentials_ref\x18\x06 \x01(\tR\x0ecredentialsRef\x12E\n" +
	"\x06status\x18\a \x01(\x0e2-.kacho.cloud.storage.v1.StorageBackend.StatusR\x06status\x12;\n" +
	"\vupdate_mask\x18\b \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\"K\n" +
	"\x1bDeleteStorageBackendRequest\x12,\n" +
	"\x12storage_backend_id\x18\x01 \x01(\tR\x10storageBackendId\"\x1e\n" +
	"\x1cDeleteStorageBackendResponse2\x9c\t\n" +
	"\x1dInternalStorageBackendService\x12\xd5\x01\n" +
	"\x06Create\x123.kacho.cloud.storage.v1.CreateStorageBackendRequest\x1a&.kacho.cloud.storage.v1.StorageBackend\"n\x8a\xb5\x18\x1fstorage.storage_backends.create\x92\xb5\x18\fsystem_admin\x9a\xb5\x18\f\n" +
	"\acluster\x12\x01*\xa2\xb5\x18\x011\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/storage/v1/storageBackends\x12\xde\x01\n" +
	"\x03Get\x120.kacho.cloud.storage.v1.GetStorageBackendRequest\x1a&.kacho.cloud.storage.v1.StorageBackend\"}\x8a\xb5\x18\x1cstorage.storage_backends.get\x92\xb5\x18\fsystem_admin\x9a\xb5\x18\f\n" +
	"\acluster\x12\x01*\xa2\xb5\x18\x011\x82\xd3\xe4\x93\x022\x120/storage/v1/storageBackends/{storage_backend_id}\x12\xda\x01\n" +
	"\x04List\x122.kacho.cloud.storage.v1.ListStorageBackendsRequest\x1a3.kacho.cloud.storage.v1.ListStorageBackendsResponse\"i\x8a\xb5\x18\x1dstorage.storage_backends.list\x92\xb5\x18\fsystem_admin\x9a\xb5\x18\f\n" +
	"\acluster\x12\x01*\xa2\xb5\x18\x011\x82\xd3\xe4\x93\x02\x1d\x12\x1b/storage/v1/storageBackends\x12\xeb\x01\n" +
	"\x06Update\x123.kacho.cloud.storage.v1.UpdateStorageBackendRequest\x1a&.kacho.cloud.storage.v1.StorageBackend\"\x83\x01\x8a\xb5\x18\x1fstorage.storage_backends.update\x92\xb5\x18\fsystem_admin\x9a\xb5\x18\f\n" +
	"\acluster\x12\x01*\xa2\xb5\x18\x011\x82\xd3\xe4\x93\x025:\x01*20/storage/v1/storageBackends/{storage_backend_id}\x12\xf6\x01\n" +
	"\x06Delete\x123.kacho.cloud.storage.v1.DeleteStorageBackendRequest\x1a4.kacho.cloud.storage.v1.DeleteStorageBackendResponse\"\x80\x01\x8a\xb5\x18\x1fstorage.storage_backends.delete\x92\xb5\x18\fsystem_admin\x9a\xb5\x18\f\n" +
	"\acluster\x12\x01*\xa2\xb5\x18\x011\x82\xd3\xe4\x93\x022*0/storage/v1/storageBackends/{storage_backend_id}BHZFgithub.com/PRO-Robotech/kacho/pkg/api/kacho/cloud/storage/v1;storagev1b\x06proto3"

var (
	file_kacho_cloud_storage_v1_internal_storage_backend_service_proto_rawDescOnce sync.Once
	file_kacho_cloud_storage_v1_internal_storage_backend_service_proto_rawDescData []byte
)

func file_kacho_cloud_storage_v1_internal_storage_backend_service_proto_rawDescGZIP() []byte {
	file_kacho_cloud_storage_v1_internal_storage_backend_service_proto_rawDescOnce.Do(func() {
		file_kacho_cloud_storage_v1_internal_storage_backend_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kacho_cloud_storage_v1_internal_storage_backend_service_proto_rawDesc), len(file_kacho_cloud_storage_v1_internal_storage_backend_service_proto_rawDesc)))
	})
	return file_kacho_cloud_storage_v1_internal_storage_backend_service_proto_rawDescData
}

var file_kacho_cloud_storage_v1_internal_storage_backend_service_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_kacho_cloud_storage_v1_internal_storage_backend_service_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_kacho_cloud_storage_v1_internal_storage_backend_service_proto_goTypes = []any{
	(StorageBackend_BackendKind)(0),      // 0: kacho.cloud.storage.v1.StorageBackend.BackendKind
	(StorageBackend_Status)(0),           // 1: kacho.cloud.storage.v1.StorageBackend.Status
	(*StorageBackend)(nil),               // 2: kacho.cloud.storage.v1.StorageBackend
	(*CreateStorageBackendRequest)(nil),  // 3: kacho.cloud.storage.v1.CreateStorageBackendRequest
	(*GetStorageBackendRequest)(nil),     // 4: kacho.cloud.storage.v1.GetStorageBackendRequest
	(*ListStorageBackendsRequest)(nil),   // 5: kacho.cloud.storage.v1.ListStorageBackendsRequest
	(*ListStorageBackendsResponse)(nil),  // 6: kacho.cloud.storage.v1.ListStorageBackendsResponse
	(*UpdateStorageBackendRequest)(nil),  // 7: kacho.cloud.storage.v1.UpdateStorageBackendRequest
	(*DeleteStorageBackendRequest)(nil),  // 8: kacho.cloud.storage.v1.DeleteStorageBackendRequest
	(*DeleteStorageBackendResponse)(nil), // 9: kacho.cloud.storage.v1.DeleteStorageBackendResponse
	(*timestamppb.Timestamp)(nil),        // 10: google.protobuf.Timestamp
	(*fieldmaskpb.FieldMask)(nil),        // 11: google.protobuf.FieldMask
}
var file_kacho_cloud_storage_v1_internal_storage_backend_service_proto_depIdxs = []int32{
	0,  // 0: kacho.cloud.storage.v1.StorageBackend.kind:type_name -> kacho.cloud.storage.v1.StorageBackend.BackendKind
	1,  // 1: kacho.cloud.storage.v1.StorageBackend.status:type_name -> kacho.cloud.storage.v1.StorageBackend.Status
	10, // 2: kacho.cloud.storage.v1.StorageBackend.created_at:type_name -> google.protobuf.Timestamp
	10, // 3: kacho.cloud.storage.v1.StorageBackend.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 4: kacho.cloud.storage.v1.CreateStorageBackendRequest.kind:type_name -> kacho.cloud.storage.v1.StorageBackend.BackendKind
	1,  // 5: kacho.cloud.storage.v1.CreateStorageBackendRequest.status:type_name -> kacho.cloud.storage.v1.StorageBackend.Status
	2,  // 6: kacho.cloud.storage.v1.ListStorageBackendsResponse.storage_backends:type_name -> kacho.cloud.storage.v1.StorageBackend
	1,  // 7: kacho.cloud.storage.v1.UpdateStorageBackendRequest.status:type_name -> kacho.cloud.storage.v1.StorageBackend.Status
	11, // 8: kacho.cloud.storage.v1.UpdateStorageBackendRequest.update_mask:type_name -> google.protobuf.FieldMask
	3,  // 9: kacho.cloud.storage.v1.InternalStorageBackendService.Create:input_type -> kacho.cloud.storage.v1.CreateStorageBackendRequest
	4,  // 10: kacho.cloud.storage.v1.InternalStorageBackendService.Get:input_type -> kacho.cloud.storage.v1.GetStorageBackendRequest
	5,  // 11: kacho.cloud.storage.v1.InternalStorageBackendService.List:input_type -> kacho.cloud.storage.v1.ListStorageBackendsRequest
	7,  // 12: kacho.cloud.storage.v1.InternalStorageBackendService.Update:input_type -> kacho.cloud.storage.v1.UpdateStorageBackendRequest
	8,  // 13: kacho.cloud.storage.v1.InternalStorageBackendService.Delete:input_type -> kacho.cloud.storage.v1.DeleteStorageBackendRequest
	2,  // 14: kacho.cloud.storage.v1.InternalStorageBackendService.Create:output_type -> kacho.cloud.storage.v1.StorageBackend
	2,  // 15: kacho.cloud.storage.v1.InternalStorageBackendService.Get:output_type -> kacho.cloud.storage.v1.StorageBackend
	6,  // 16: kacho.cloud.storage.v1.InternalStorageBackendService.List:output_type -> kacho.cloud.storage.v1.ListStorageBackendsResponse
	2,  // 17: kacho.cloud.storage.v1.InternalStorageBackendService.Update:output_type -> kacho.cloud.storage.v1.StorageBackend
	9,  // 18: kacho.cloud.storage.v1.InternalStorageBackendService.Delete:output_type -> kacho.cloud.storage.v1.DeleteStorageBackendResponse
	14, // [14:19] is the sub-list for method output_type
	9,  // [9:14] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_kacho_cloud_storage_v1_internal_storage_backend_service_proto_init() }
func file_kacho_cloud_storage_v1_internal_storage_backend_service_proto_init() {
	if File_kacho_cloud_storage_v1_internal_storage_backend_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kacho_cloud_storage_v1_internal_storage_backend_service_proto_rawDesc), len(file_kacho_cloud_storage_v1_internal_storage_backend_service_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kacho_cloud_storage_v1_internal_storage_backend_service_proto_goTypes,
		DependencyIndexes: file_kacho_cloud_storage_v1_internal_storage_backend_service_proto_depIdxs,
		EnumInfos:         file_kacho_cloud_storage_v1_internal_storage_backend_service_proto_enumTypes,
		MessageInfos:      file_kacho_cloud_storage_v1_internal_storage_backend_service_proto_msgTypes,
	}.Build()
	File_kacho_cloud_storage_v1_internal_storage_backend_service_proto = out.File
	file_kacho_cloud_storage_v1_internal_storage_backend_service_proto_goTypes = nil
	file_kacho_cloud_storage_v1_internal_storage_backend_service_proto_depIdxs = nil
}
