# Copyright (c) PRO-Robotech
# SPDX-License-Identifier: AGPL-3.0-or-later

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Values.name }}
  ports:
    - name: grpc
      port: {{ .Values.ports.grpc }}
      targetPort: grpc
    - name: grpc-internal
      port: {{ .Values.ports.internalGrpc }}
      targetPort: grpc-internal
