// Copyright (c) PRO-Robotech
// SPDX-License-Identifier: BUSL-1.1

// Команда stand-ns — Go-половина стенда проб в своём пространстве имён
// (kacho#3102). Оболочку ведёт deploy/scripts/stand-ns.sh; здесь только то,
// что требует РАЗБОРА YAML, а не текста.
//
//	stand-ns relocate -namespace NS -ca-namespace CANS < рендер > рендер
//	    пост-обработчик рендера helm (deploy/helm/plugins/kacho-stand-ns):
//	    переносит стенд в NS, отказывает на непереносимом (tools/standns)
//	stand-ns images -list СЛОЙ…
//	    печатает имена образов частей ЭТОГО дерева, объявленных цепочкой
//	stand-ns images -refs "образ=ссылка …" СЛОЙ…
//	    печатает накладку, ставящую каждому такому образу названную ссылку
//
// Коды: 0 — исполнено; 1 — находка (часть без ссылки); 2 — отказ входа.
package main

import (
	"flag"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"

	"gopkg.in/yaml.v3"

	"github.com/PRO-Robotech/kacho/internal/localimages"
	"github.com/PRO-Robotech/kacho/tools/standns"
)

func main() {
	os.Exit(run(os.Stdin, os.Stdout, os.Stderr, os.Args[1:]))
}

func run(stdin io.Reader, stdout, stderr io.Writer, args []string) int {
	if len(args) == 0 {
		_, _ = fmt.Fprintln(stderr, "stand-ns: режим не назван (relocate | images)")
		return 2
	}
	switch args[0] {
	case "relocate":
		return relocate(stdin, stdout, stderr, args[1:])
	case "images":
		return images(stdout, stderr, args[1:])
	}
	_, _ = fmt.Fprintf(stderr, "stand-ns: неизвестный режим %q (relocate | images)\n", args[0])
	return 2
}

func relocate(stdin io.Reader, stdout, stderr io.Writer, args []string) int {
	fs := flag.NewFlagSet("relocate", flag.ContinueOnError)
	fs.SetOutput(stderr)
	ns := fs.String("namespace", "", "пространство имён стенда")
	ca := fs.String("ca-namespace", "", "пространство ресурсов cert-manager")
	if err := fs.Parse(args); err != nil {
		return 2
	}
	census, err := standns.Relocate(stdin, stdout, standns.Options{Namespace: *ns, CANamespace: *ca})
	if err != nil {
		_, _ = fmt.Fprintf(stderr, "stand-ns relocate: ОТКАЗ — %v\n", err)
		return 2
	}
	_, _ = fmt.Fprintf(stderr, "stand-ns relocate → %s: %s\n", *ns, census)
	return 0
}

func images(stdout, stderr io.Writer, args []string) int {
	fs := flag.NewFlagSet("images", flag.ContinueOnError)
	fs.SetOutput(stderr)
	list := fs.Bool("list", false, "напечатать образы частей этого дерева")
	refsArg := fs.String("refs", "", "«образ=ссылка» через пробел или запятую")
	if err := fs.Parse(args); err != nil {
		return 2
	}
	files := fs.Args()
	if len(files) == 0 {
		_, _ = fmt.Fprintln(stderr, "stand-ns images: не названо ни одного слоя — образы выводить не из чего")
		return 2
	}
	folded := map[string]any{}
	for _, f := range files {
		raw, err := os.ReadFile(filepath.Clean(f))
		if err != nil {
			_, _ = fmt.Fprintf(stderr, "stand-ns images: слой %s не читается (%v)\n", f, err)
			return 2
		}
		var layer map[string]any
		if err := yaml.Unmarshal(raw, &layer); err != nil {
			_, _ = fmt.Fprintf(stderr, "stand-ns images: слой %s не разбирается (%v)\n", f, err)
			return 2
		}
		folded = localimages.Merge(folded, layer)
	}
	if *list {
		names := localimages.TreeImages(folded)
		if len(names) == 0 {
			_, _ = fmt.Fprintln(stderr, "stand-ns images: частей этого дерева цепочка не объявляет ни одной — это не «нечего переводить», а слепой обход")
			return 2
		}
		_, _ = fmt.Fprintln(stdout, strings.Join(names, "\n"))
		return 0
	}
	refs := map[string]string{}
	for _, kv := range strings.FieldsFunc(*refsArg, func(r rune) bool { return r == ',' || r == ' ' || r == '\n' || r == '\t' }) {
		img, ref, ok := strings.Cut(kv, "=")
		if !ok || img == "" || ref == "" {
			_, _ = fmt.Fprintf(stderr, "stand-ns images: «%s» не в форме образ=ссылка\n", kv)
			return 2
		}
		refs[img] = ref
	}
	overlay, census := localimages.PublishedOverlay(folded, refs)
	_, _ = fmt.Fprintf(stderr, "stand-ns images: объявлений %d, переписано %d, вынесенных частей %d, сторонних %d\n",
		census.Declarations, census.Rewritten, census.External, census.Foreign)
	if len(census.Unresolved) > 0 {
		_, _ = fmt.Fprintf(stderr, "НАХОДКА: части этого дерева без ссылки: %s — стенд исполнял бы смесь двух ревизий\n",
			strings.Join(census.Unresolved, " "))
		return 1
	}
	if census.Rewritten == 0 {
		_, _ = fmt.Fprintln(stderr, "stand-ns images: не переписано ни одного объявления — пустая накладка подняла бы стенд на пинах цепочки")
		return 2
	}
	body, err := yaml.Marshal(overlay)
	if err != nil {
		_, _ = fmt.Fprintf(stderr, "stand-ns images: накладка не сериализуется (%v)\n", err)
		return 2
	}
	_, _ = fmt.Fprintf(stdout, "# generated by 'stand-ns images' — не редактировать, не коммитить\n%s", body)
	return 0
}
