// Copyright (c) PRO-Robotech
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: kacho/cloud/notify/v1/notice_service.proto

package notifyv1

import (
	_ "github.com/PRO-Robotech/corelib/api/corelib/authz/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListNoticesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// project_id — проект, из которого читаются извещения. Обязателен:
	// пустой — `project_id: required`; неверная форма — `invalid project id '<X>'`.
	ProjectId string `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	// page_size — размер страницы: `0` — 50, наибольшее 1000; вне `[0..1000]` —
	// `INVALID_ARGUMENT` с именем поля, без подрезки.
	PageSize int64 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// page_token — непрозрачный курсор из `next_page_token` предыдущего ответа;
	// мусорный — `INVALID_ARGUMENT` с именем поля, а не первая страница.
	PageToken     string `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNoticesRequest) Reset() {
	*x = ListNoticesRequest{}
	mi := &file_kacho_cloud_notify_v1_notice_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNoticesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNoticesRequest) ProtoMessage() {}

func (x *ListNoticesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kacho_cloud_notify_v1_notice_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNoticesRequest.ProtoReflect.Descriptor instead.
func (*ListNoticesRequest) Descriptor() ([]byte, []int) {
	return file_kacho_cloud_notify_v1_notice_service_proto_rawDescGZIP(), []int{0}
}

func (x *ListNoticesRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *ListNoticesRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListNoticesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListNoticesByAccountRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// account_id — аккаунт, из которого читаются извещения. Обязателен:
	// пустой — `account_id: required`; неверная форма — `invalid account id '<X>'`.
	AccountId string `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	// page_size — как у `ListNoticesRequest.page_size`.
	PageSize int64 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// page_token — как у `ListNoticesRequest.page_token`.
	PageToken     string `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNoticesByAccountRequest) Reset() {
	*x = ListNoticesByAccountRequest{}
	mi := &file_kacho_cloud_notify_v1_notice_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNoticesByAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNoticesByAccountRequest) ProtoMessage() {}

func (x *ListNoticesByAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kacho_cloud_notify_v1_notice_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNoticesByAccountRequest.ProtoReflect.Descriptor instead.
func (*ListNoticesByAccountRequest) Descriptor() ([]byte, []int) {
	return file_kacho_cloud_notify_v1_notice_service_proto_rawDescGZIP(), []int{1}
}

func (x *ListNoticesByAccountRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *ListNoticesByAccountRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListNoticesByAccountRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListNoticesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// notices — страница извещений в порядке `(created_at, id)` по возрастанию
	// (порядок значим). `affected_resources` элементов не заполняется.
	Notices []*Notice `protobuf:"bytes,1,rep,name=notices,proto3" json:"notices,omitempty"`
	// next_page_token — курсор следующей страницы; пустой на странице с
	// последним извещением.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNoticesResponse) Reset() {
	*x = ListNoticesResponse{}
	mi := &file_kacho_cloud_notify_v1_notice_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNoticesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNoticesResponse) ProtoMessage() {}

func (x *ListNoticesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kacho_cloud_notify_v1_notice_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNoticesResponse.ProtoReflect.Descriptor instead.
func (*ListNoticesResponse) Descriptor() ([]byte, []int) {
	return file_kacho_cloud_notify_v1_notice_service_proto_rawDescGZIP(), []int{2}
}

func (x *ListNoticesResponse) GetNotices() []*Notice {
	if x != nil {
		return x.Notices
	}
	return nil
}

func (x *ListNoticesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type GetNoticeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// notice_id — идентификатор извещения (`ntc-…`). Неверная форма —
	// `invalid notice id '<X>'`.
	NoticeId string `protobuf:"bytes,1,opt,name=notice_id,json=noticeId,proto3" json:"notice_id,omitempty"`
	// project_id — проект, из которого читается извещение. Обязателен:
	// пустой — `project_id: required`; неверная форма — `invalid project id '<X>'`.
	ProjectId     string `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNoticeRequest) Reset() {
	*x = GetNoticeRequest{}
	mi := &file_kacho_cloud_notify_v1_notice_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNoticeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNoticeRequest) ProtoMessage() {}

func (x *GetNoticeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kacho_cloud_notify_v1_notice_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNoticeRequest.ProtoReflect.Descriptor instead.
func (*GetNoticeRequest) Descriptor() ([]byte, []int) {
	return file_kacho_cloud_notify_v1_notice_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetNoticeRequest) GetNoticeId() string {
	if x != nil {
		return x.NoticeId
	}
	return ""
}

func (x *GetNoticeRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type GetNoticeByAccountRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// notice_id — идентификатор извещения (`ntc-…`). Неверная форма —
	// `invalid notice id '<X>'`.
	NoticeId string `protobuf:"bytes,1,opt,name=notice_id,json=noticeId,proto3" json:"notice_id,omitempty"`
	// account_id — аккаунт, из которого читается извещение. Обязателен:
	// пустой — `account_id: required`; неверная форма — `invalid account id '<X>'`.
	AccountId     string `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNoticeByAccountRequest) Reset() {
	*x = GetNoticeByAccountRequest{}
	mi := &file_kacho_cloud_notify_v1_notice_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNoticeByAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNoticeByAccountRequest) ProtoMessage() {}

func (x *GetNoticeByAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kacho_cloud_notify_v1_notice_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNoticeByAccountRequest.ProtoReflect.Descriptor instead.
func (*GetNoticeByAccountRequest) Descriptor() ([]byte, []int) {
	return file_kacho_cloud_notify_v1_notice_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetNoticeByAccountRequest) GetNoticeId() string {
	if x != nil {
		return x.NoticeId
	}
	return ""
}

func (x *GetNoticeByAccountRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

var File_kacho_cloud_notify_v1_notice_service_proto protoreflect.FileDescriptor

const file_kacho_cloud_notify_v1_notice_service_proto_rawDesc = "" +
	"\n" +
	"*kacho/cloud/notify/v1/notice_service.proto\x12\x15kacho.cloud.notify.v1\x1a\x1cgoogle/api/annotations.proto\x1a$corelib/authz/v1/authz_options.proto\x1a\"kacho/cloud/notify/v1/notice.proto\"o\n" +
	"\x12ListNoticesRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x03R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"x\n" +
	"\x1bListNoticesByAccountRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x03R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"v\n" +
	"\x13ListNoticesResponse\x127\n" +
	"\anotices\x18\x01 \x03(\v2\x1d.kacho.cloud.notify.v1.NoticeR\anotices\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"N\n" +
	"\x10GetNoticeRequest\x12\x1b\n" +
	"\tnotice_id\x18\x01 \x01(\tR\bnoticeId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\"W\n" +
	"\x19GetNoticeByAccountRequest\x12\x1b\n" +
	"\tnotice_id\x18\x01 \x01(\tR\bnoticeId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId2\xb2\x05\n" +
	"\rNoticeService\x12\x98\x01\n" +
	"\x04List\x12).kacho.cloud.notify.v1.ListNoticesRequest\x1a*.kacho.cloud.notify.v1.ListNoticesResponse\"9\x8a\xb5\x18\b<exempt>\xba\xb5\x18\x0fHANDLER_DECIDES\x82\xd3\xe4\x93\x02\x14\x12\x12/notify/v1/notices\x12\xb8\x01\n" +
	"\rListByAccount\x122.kacho.cloud.notify.v1.ListNoticesByAccountRequest\x1a*.kacho.cloud.notify.v1.ListNoticesResponse\"G\x8a\xb5\x18\b<exempt>\xba\xb5\x18\x0fHANDLER_DECIDES\x82\xd3\xe4\x93\x02\"\x12 /notify/v1/notices:listByAccount\x12\x94\x01\n" +
	"\x03Get\x12'.kacho.cloud.notify.v1.GetNoticeRequest\x1a\x1d.kacho.cloud.notify.v1.Notice\"E\x8a\xb5\x18\b<exempt>\xba\xb5\x18\x0fHANDLER_DECIDES\x82\xd3\xe4\x93\x02 \x12\x1e/notify/v1/notices/{notice_id}\x12\xb3\x01\n" +
	"\fGetByAccount\x120.kacho.cloud.notify.v1.GetNoticeByAccountRequest\x1a\x1d.kacho.cloud.notify.v1.Notice\"R\x8a\xb5\x18\b<exempt>\xba\xb5\x18\x0fHANDLER_DECIDES\x82\xd3\xe4\x93\x02-\x12+/notify/v1/notices/{notice_id}:getByAccountBFZDgithub.com/PRO-Robotech/kacho/pkg/api/kacho/cloud/notify/v1;notifyv1b\x06proto3"

var (
	file_kacho_cloud_notify_v1_notice_service_proto_rawDescOnce sync.Once
	file_kacho_cloud_notify_v1_notice_service_proto_rawDescData []byte
)

func file_kacho_cloud_notify_v1_notice_service_proto_rawDescGZIP() []byte {
	file_kacho_cloud_notify_v1_notice_service_proto_rawDescOnce.Do(func() {
		file_kacho_cloud_notify_v1_notice_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kacho_cloud_notify_v1_notice_service_proto_rawDesc), len(file_kacho_cloud_notify_v1_notice_service_proto_rawDesc)))
	})
	return file_kacho_cloud_notify_v1_notice_service_proto_rawDescData
}

var file_kacho_cloud_notify_v1_notice_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_kacho_cloud_notify_v1_notice_service_proto_goTypes = []any{
	(*ListNoticesRequest)(nil),          // 0: kacho.cloud.notify.v1.ListNoticesRequest
	(*ListNoticesByAccountRequest)(nil), // 1: kacho.cloud.notify.v1.ListNoticesByAccountRequest
	(*ListNoticesResponse)(nil),         // 2: kacho.cloud.notify.v1.ListNoticesResponse
	(*GetNoticeRequest)(nil),            // 3: kacho.cloud.notify.v1.GetNoticeRequest
	(*GetNoticeByAccountRequest)(nil),   // 4: kacho.cloud.notify.v1.GetNoticeByAccountRequest
	(*Notice)(nil),                      // 5: kacho.cloud.notify.v1.Notice
}
var file_kacho_cloud_notify_v1_notice_service_proto_depIdxs = []int32{
	5, // 0: kacho.cloud.notify.v1.ListNoticesResponse.notices:type_name -> kacho.cloud.notify.v1.Notice
	0, // 1: kacho.cloud.notify.v1.NoticeService.List:input_type -> kacho.cloud.notify.v1.ListNoticesRequest
	1, // 2: kacho.cloud.notify.v1.NoticeService.ListByAccount:input_type -> kacho.cloud.notify.v1.ListNoticesByAccountRequest
	3, // 3: kacho.cloud.notify.v1.NoticeService.Get:input_type -> kacho.cloud.notify.v1.GetNoticeRequest
	4, // 4: kacho.cloud.notify.v1.NoticeService.GetByAccount:input_type -> kacho.cloud.notify.v1.GetNoticeByAccountRequest
	2, // 5: kacho.cloud.notify.v1.NoticeService.List:output_type -> kacho.cloud.notify.v1.ListNoticesResponse
	2, // 6: kacho.cloud.notify.v1.NoticeService.ListByAccount:output_type -> kacho.cloud.notify.v1.ListNoticesResponse
	5, // 7: kacho.cloud.notify.v1.NoticeService.Get:output_type -> kacho.cloud.notify.v1.Notice
	5, // 8: kacho.cloud.notify.v1.NoticeService.GetByAccount:output_type -> kacho.cloud.notify.v1.Notice
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_kacho_cloud_notify_v1_notice_service_proto_init() }
func file_kacho_cloud_notify_v1_notice_service_proto_init() {
	if File_kacho_cloud_notify_v1_notice_service_proto != nil {
		return
	}
	file_kacho_cloud_notify_v1_notice_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kacho_cloud_notify_v1_notice_service_proto_rawDesc), len(file_kacho_cloud_notify_v1_notice_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kacho_cloud_notify_v1_notice_service_proto_goTypes,
		DependencyIndexes: file_kacho_cloud_notify_v1_notice_service_proto_depIdxs,
		MessageInfos:      file_kacho_cloud_notify_v1_notice_service_proto_msgTypes,
	}.Build()
	File_kacho_cloud_notify_v1_notice_service_proto = out.File
	file_kacho_cloud_notify_v1_notice_service_proto_goTypes = nil
	file_kacho_cloud_notify_v1_notice_service_proto_depIdxs = nil
}
