// Copyright (c) PRO-Robotech
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: kacho/cloud/compute/v1/instance.proto

package computev1

import (
	reference "github.com/PRO-Robotech/kacho/pkg/api/kacho/cloud/reference"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// InstanceKind — the strong first discriminator (F1). VM and CONTAINER have distinct
// lifecycles; the value gates exactly one nested spec and is immutable after Create.
type InstanceKind int32

const (
	InstanceKind_INSTANCE_KIND_UNSPECIFIED InstanceKind = 0
	// Virtual machine: persistent OS from a storage.image, vm_spec.
	InstanceKind_VM InstanceKind = 1
	// Container job: ephemeral rootfs from a registry.image, container_spec.
	//
	// NOT CREATABLE TODAY, and the refusal is explicit rather than silent. A
	// container job takes its rootfs from a registry image, and a registry image
	// has no durable address here: the repository carries no immutable id and is
	// addressed by (registry, name), while the name is renamed by its own verb. A
	// reference pinned into a machine would therefore go stale on someone else's
	// rename — the relaunch a month later would take a different image, or none.
	//
	// Create with this kind is refused synchronously, naming THIS field —
	// `instance_kind` — regardless of which boot_source accompanies it. The
	// field is named explicitly here because "naming the field" once read as the
	// OS-entry field: the refusal used to hang on boot_source.type alone, so
	// CONTAINER paired with a storage.image passed input validation whole and
	// produced a machine that no branch of the model describes.
	//
	// That is the second of the three lawful outcomes: accepting the value and
	// never resolving it would promise a capability that does not exist.
	//
	// The value stays on the contract because the direction is decided and its
	// return has a predicate: an immutable repository id lands at the owner. It
	// is not deferred work with nobody responsible — the owner is named and the
	// condition is checkable.
	InstanceKind_CONTAINER InstanceKind = 2
)

// Enum value maps for InstanceKind.
var (
	InstanceKind_name = map[int32]string{
		0: "INSTANCE_KIND_UNSPECIFIED",
		1: "VM",
		2: "CONTAINER",
	}
	InstanceKind_value = map[string]int32{
		"INSTANCE_KIND_UNSPECIFIED": 0,
		"VM":                        1,
		"CONTAINER":                 2,
	}
)

func (x InstanceKind) Enum() *InstanceKind {
	p := new(InstanceKind)
	*p = x
	return p
}

func (x InstanceKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InstanceKind) Descriptor() protoreflect.EnumDescriptor {
	return file_kacho_cloud_compute_v1_instance_proto_enumTypes[0].Descriptor()
}

func (InstanceKind) Type() protoreflect.EnumType {
	return &file_kacho_cloud_compute_v1_instance_proto_enumTypes[0]
}

func (x InstanceKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InstanceKind.Descriptor instead.
func (InstanceKind) EnumDescriptor() ([]byte, []int) {
	return file_kacho_cloud_compute_v1_instance_proto_rawDescGZIP(), []int{0}
}

// ImageKind — the formal imageKind discriminator (B13). Distinguishes a storage.image
// (OS/disk image) from a registry.image (OCI artifact) at the type level.
type ImageKind int32

const (
	ImageKind_IMAGE_KIND_UNSPECIFIED ImageKind = 0
	// storage.image — an OS/disk image owned by kacho-storage (img-).
	ImageKind_STORAGE_IMAGE ImageKind = 1
	// registry.image — an OCI artifact owned by kacho-registry.
	ImageKind_OCI_IMAGE ImageKind = 2
)

// Enum value maps for ImageKind.
var (
	ImageKind_name = map[int32]string{
		0: "IMAGE_KIND_UNSPECIFIED",
		1: "STORAGE_IMAGE",
		2: "OCI_IMAGE",
	}
	ImageKind_value = map[string]int32{
		"IMAGE_KIND_UNSPECIFIED": 0,
		"STORAGE_IMAGE":          1,
		"OCI_IMAGE":              2,
	}
)

func (x ImageKind) Enum() *ImageKind {
	p := new(ImageKind)
	*p = x
	return p
}

func (x ImageKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ImageKind) Descriptor() protoreflect.EnumDescriptor {
	return file_kacho_cloud_compute_v1_instance_proto_enumTypes[1].Descriptor()
}

func (ImageKind) Type() protoreflect.EnumType {
	return &file_kacho_cloud_compute_v1_instance_proto_enumTypes[1]
}

func (x ImageKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ImageKind.Descriptor instead.
func (ImageKind) EnumDescriptor() ([]byte, []int) {
	return file_kacho_cloud_compute_v1_instance_proto_rawDescGZIP(), []int{1}
}

// RestartPolicy — CONTAINER restart policy.
type RestartPolicy int32

const (
	RestartPolicy_RESTART_POLICY_UNSPECIFIED RestartPolicy = 0
	// Never restart (default).
	RestartPolicy_NEVER RestartPolicy = 1
	// Restart on non-zero exit.
	RestartPolicy_ON_FAILURE RestartPolicy = 2
	// Always restart.
	RestartPolicy_ALWAYS RestartPolicy = 3
)

// Enum value maps for RestartPolicy.
var (
	RestartPolicy_name = map[int32]string{
		0: "RESTART_POLICY_UNSPECIFIED",
		1: "NEVER",
		2: "ON_FAILURE",
		3: "ALWAYS",
	}
	RestartPolicy_value = map[string]int32{
		"RESTART_POLICY_UNSPECIFIED": 0,
		"NEVER":                      1,
		"ON_FAILURE":                 2,
		"ALWAYS":                     3,
	}
)

func (x RestartPolicy) Enum() *RestartPolicy {
	p := new(RestartPolicy)
	*p = x
	return p
}

func (x RestartPolicy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RestartPolicy) Descriptor() protoreflect.EnumDescriptor {
	return file_kacho_cloud_compute_v1_instance_proto_enumTypes[2].Descriptor()
}

func (RestartPolicy) Type() protoreflect.EnumType {
	return &file_kacho_cloud_compute_v1_instance_proto_enumTypes[2]
}

func (x RestartPolicy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RestartPolicy.Descriptor instead.
func (RestartPolicy) EnumDescriptor() ([]byte, []int) {
	return file_kacho_cloud_compute_v1_instance_proto_rawDescGZIP(), []int{2}
}

type IpVersion int32

const (
	IpVersion_IP_VERSION_UNSPECIFIED IpVersion = 0
	// IPv4 address, for example 192.0.2.235.
	IpVersion_IPV4 IpVersion = 1
	// IPv6 address. Not available yet.
	IpVersion_IPV6 IpVersion = 2
)

// Enum value maps for IpVersion.
var (
	IpVersion_name = map[int32]string{
		0: "IP_VERSION_UNSPECIFIED",
		1: "IPV4",
		2: "IPV6",
	}
	IpVersion_value = map[string]int32{
		"IP_VERSION_UNSPECIFIED": 0,
		"IPV4":                   1,
		"IPV6":                   2,
	}
)

func (x IpVersion) Enum() *IpVersion {
	p := new(IpVersion)
	*p = x
	return p
}

func (x IpVersion) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IpVersion) Descriptor() protoreflect.EnumDescriptor {
	return file_kacho_cloud_compute_v1_instance_proto_enumTypes[3].Descriptor()
}

func (IpVersion) Type() protoreflect.EnumType {
	return &file_kacho_cloud_compute_v1_instance_proto_enumTypes[3]
}

func (x IpVersion) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IpVersion.Descriptor instead.
func (IpVersion) EnumDescriptor() ([]byte, []int) {
	return file_kacho_cloud_compute_v1_instance_proto_rawDescGZIP(), []int{3}
}

type MetadataOption int32

const (
	MetadataOption_METADATA_OPTION_UNSPECIFIED MetadataOption = 0
	// Option is enabled
	MetadataOption_ENABLED MetadataOption = 1
	// Option is disabled
	MetadataOption_DISABLED MetadataOption = 2
)

// Enum value maps for MetadataOption.
var (
	MetadataOption_name = map[int32]string{
		0: "METADATA_OPTION_UNSPECIFIED",
		1: "ENABLED",
		2: "DISABLED",
	}
	MetadataOption_value = map[string]int32{
		"METADATA_OPTION_UNSPECIFIED": 0,
		"ENABLED":                     1,
		"DISABLED":                    2,
	}
)

func (x MetadataOption) Enum() *MetadataOption {
	p := new(MetadataOption)
	*p = x
	return p
}

func (x MetadataOption) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MetadataOption) Descriptor() protoreflect.EnumDescriptor {
	return file_kacho_cloud_compute_v1_instance_proto_enumTypes[4].Descriptor()
}

func (MetadataOption) Type() protoreflect.EnumType {
	return &file_kacho_cloud_compute_v1_instance_proto_enumTypes[4]
}

func (x MetadataOption) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MetadataOption.Descriptor instead.
func (MetadataOption) EnumDescriptor() ([]byte, []int) {
	return file_kacho_cloud_compute_v1_instance_proto_rawDescGZIP(), []int{4}
}

type Instance_Status int32

const (
	Instance_STATUS_UNSPECIFIED Instance_Status = 0
	// Instance is waiting for resources to be allocated.
	Instance_PROVISIONING Instance_Status = 1
	// Instance is running normally.
	Instance_RUNNING Instance_Status = 2
	// Instance is being stopped.
	Instance_STOPPING Instance_Status = 3
	// Instance stopped.
	Instance_STOPPED Instance_Status = 4
	// Instance is being started.
	Instance_STARTING Instance_Status = 5
	// Instance is being restarted.
	Instance_RESTARTING Instance_Status = 6
	// Instance is being updated.
	Instance_UPDATING Instance_Status = 7
	// Instance encountered a problem and cannot operate.
	Instance_ERROR Instance_Status = 8
	// Instance crashed and will be restarted automatically.
	Instance_CRASHED Instance_Status = 9
	// Instance is being deleted.
	Instance_DELETING Instance_Status = 10
)

// Enum value maps for Instance_Status.
var (
	Instance_Status_name = map[int32]string{
		0:  "STATUS_UNSPECIFIED",
		1:  "PROVISIONING",
		2:  "RUNNING",
		3:  "STOPPING",
		4:  "STOPPED",
		5:  "STARTING",
		6:  "RESTARTING",
		7:  "UPDATING",
		8:  "ERROR",
		9:  "CRASHED",
		10: "DELETING",
	}
	Instance_Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"PROVISIONING":       1,
		"RUNNING":            2,
		"STOPPING":           3,
		"STOPPED":            4,
		"STARTING":           5,
		"RESTARTING":         6,
		"UPDATING":           7,
		"ERROR":              8,
		"CRASHED":            9,
		"DELETING":           10,
	}
)

func (x Instance_Status) Enum() *Instance_Status {
	p := new(Instance_Status)
	*p = x
	return p
}

func (x Instance_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Instance_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_kacho_cloud_compute_v1_instance_proto_enumTypes[5].Descriptor()
}

func (Instance_Status) Type() protoreflect.EnumType {
	return &file_kacho_cloud_compute_v1_instance_proto_enumTypes[5]
}

func (x Instance_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Instance_Status.Descriptor instead.
func (Instance_Status) EnumDescriptor() ([]byte, []int) {
	return file_kacho_cloud_compute_v1_instance_proto_rawDescGZIP(), []int{0, 0}
}

type AttachedDisk_Mode int32

const (
	AttachedDisk_MODE_UNSPECIFIED AttachedDisk_Mode = 0
	// Read-only access.
	AttachedDisk_READ_ONLY AttachedDisk_Mode = 1
	// Read/Write access.
	AttachedDisk_READ_WRITE AttachedDisk_Mode = 2
)

// Enum value maps for AttachedDisk_Mode.
var (
	AttachedDisk_Mode_name = map[int32]string{
		0: "MODE_UNSPECIFIED",
		1: "READ_ONLY",
		2: "READ_WRITE",
	}
	AttachedDisk_Mode_value = map[string]int32{
		"MODE_UNSPECIFIED": 0,
		"READ_ONLY":        1,
		"READ_WRITE":       2,
	}
)

func (x AttachedDisk_Mode) Enum() *AttachedDisk_Mode {
	p := new(AttachedDisk_Mode)
	*p = x
	return p
}

func (x AttachedDisk_Mode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AttachedDisk_Mode) Descriptor() protoreflect.EnumDescriptor {
	return file_kacho_cloud_compute_v1_instance_proto_enumTypes[6].Descriptor()
}

func (AttachedDisk_Mode) Type() protoreflect.EnumType {
	return &file_kacho_cloud_compute_v1_instance_proto_enumTypes[6]
}

func (x AttachedDisk_Mode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AttachedDisk_Mode.Descriptor instead.
func (AttachedDisk_Mode) EnumDescriptor() ([]byte, []int) {
	return file_kacho_cloud_compute_v1_instance_proto_rawDescGZIP(), []int{6, 0}
}

type NetworkSettings_Type int32

const (
	NetworkSettings_TYPE_UNSPECIFIED NetworkSettings_Type = 0
	// Standard network.
	NetworkSettings_STANDARD NetworkSettings_Type = 1
	// Software accelerated network.
	NetworkSettings_SOFTWARE_ACCELERATED NetworkSettings_Type = 2
	// Hardware accelerated network (not available yet, reserved for future use).
	NetworkSettings_HARDWARE_ACCELERATED NetworkSettings_Type = 3
)

// Enum value maps for NetworkSettings_Type.
var (
	NetworkSettings_Type_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "STANDARD",
		2: "SOFTWARE_ACCELERATED",
		3: "HARDWARE_ACCELERATED",
	}
	NetworkSettings_Type_value = map[string]int32{
		"TYPE_UNSPECIFIED":     0,
		"STANDARD":             1,
		"SOFTWARE_ACCELERATED": 2,
		"HARDWARE_ACCELERATED": 3,
	}
)

func (x NetworkSettings_Type) Enum() *NetworkSettings_Type {
	p := new(NetworkSettings_Type)
	*p = x
	return p
}

func (x NetworkSettings_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NetworkSettings_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_kacho_cloud_compute_v1_instance_proto_enumTypes[7].Descriptor()
}

func (NetworkSettings_Type) Type() protoreflect.EnumType {
	return &file_kacho_cloud_compute_v1_instance_proto_enumTypes[7]
}

func (x NetworkSettings_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NetworkSettings_Type.Descriptor instead.
func (NetworkSettings_Type) EnumDescriptor() ([]byte, []int) {
	return file_kacho_cloud_compute_v1_instance_proto_rawDescGZIP(), []int{10, 0}
}

type SerialPortSettings_SSHAuthorization int32

const (
	SerialPortSettings_SSH_AUTHORIZATION_UNSPECIFIED SerialPortSettings_SSHAuthorization = 0
	// Authentication and authorization using SSH keys in instance metadata
	SerialPortSettings_INSTANCE_METADATA SerialPortSettings_SSHAuthorization = 1
	// Authentication and authorization using Oslogin service
	SerialPortSettings_OS_LOGIN SerialPortSettings_SSHAuthorization = 2
)

// Enum value maps for SerialPortSettings_SSHAuthorization.
var (
	SerialPortSettings_SSHAuthorization_name = map[int32]string{
		0: "SSH_AUTHORIZATION_UNSPECIFIED",
		1: "INSTANCE_METADATA",
		2: "OS_LOGIN",
	}
	SerialPortSettings_SSHAuthorization_value = map[string]int32{
		"SSH_AUTHORIZATION_UNSPECIFIED": 0,
		"INSTANCE_METADATA":             1,
		"OS_LOGIN":                      2,
	}
)

func (x SerialPortSettings_SSHAuthorization) Enum() *SerialPortSettings_SSHAuthorization {
	p := new(SerialPortSettings_SSHAuthorization)
	*p = x
	return p
}

func (x SerialPortSettings_SSHAuthorization) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SerialPortSettings_SSHAuthorization) Descriptor() protoreflect.EnumDescriptor {
	return file_kacho_cloud_compute_v1_instance_proto_enumTypes[8].Descriptor()
}

func (SerialPortSettings_SSHAuthorization) Type() protoreflect.EnumType {
	return &file_kacho_cloud_compute_v1_instance_proto_enumTypes[8]
}

func (x SerialPortSettings_SSHAuthorization) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SerialPortSettings_SSHAuthorization.Descriptor instead.
func (SerialPortSettings_SSHAuthorization) EnumDescriptor() ([]byte, []int) {
	return file_kacho_cloud_compute_v1_instance_proto_rawDescGZIP(), []int{12, 0}
}

// An Instance resource (COMP-1 redesign). A flat control-plane record for a single
// compute workload. `instance_kind` is the strong first discriminator gating exactly
// one of `vm_spec`/`container_spec`; sizing flows through the single `machine_type_id`
// channel (raw ResourcesSpec/platform_id retired, ban #2); the OS enters through the
// single `boot_source{type,id}` channel with an imageKind discriminator (storage.image
// vs registry.image, B13). Infra-sensitive placement (host/host-group/scheduler) is
// NOT on this public projection (two-projection; security §infra-sensitive) — the
// Internal* infra projection is a follow-on (COMP-4).
type Instance struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the instance (canonical "ins-<base32>").
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// ID of the project that the instance belongs to.
	ProjectId string `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	// The date and time when the instance was created (truncated to seconds on the wire).
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Name of the instance. 1-63 characters long.
	Name string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	// Description of the instance. 0-256 characters long.
	Description string `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	// Resource labels as `key:value` pairs. Maximum of 64 per resource.
	Labels map[string]string `protobuf:"bytes,6,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// ID of the availability zone where the instance resides.
	ZoneId string `protobuf:"bytes,7,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	// Status of the instance. Rests at PROVISIONING after Create (durable; the launch
	// sagas + transition to RUNNING are a follow-on, COMP-2).
	Status Instance_Status `protobuf:"varint,10,opt,name=status,proto3,enum=kacho.cloud.compute.v1.Instance_Status" json:"status,omitempty"`
	// Output-only launch mirrors — materialized by the COMP-2 attach sagas; empty in
	// COMP-1, which persists the durable record without materialize.
	BootDisk          *AttachedDisk       `protobuf:"bytes,12,opt,name=boot_disk,json=bootDisk,proto3" json:"boot_disk,omitempty"`
	SecondaryDisks    []*AttachedDisk     `protobuf:"bytes,13,rep,name=secondary_disks,json=secondaryDisks,proto3" json:"secondary_disks,omitempty"`
	NetworkInterfaces []*NetworkInterface `protobuf:"bytes,14,rep,name=network_interfaces,json=networkInterfaces,proto3" json:"network_interfaces,omitempty"`
	// A domain name of the instance. Output-only (server-derived).
	Fqdn string `protobuf:"bytes,16,opt,name=fqdn,proto3" json:"fqdn,omitempty"`
	// Guaranteed CPU baseline per vCPU, in percent.
	//
	//	0        = best-effort / burstable (no guarantee);
	//	1..100   = guaranteed percentage (CHECK 0..100).
	//
	// Family-gated: applies only to STANDARD/COMPUTE/MEMORY; accepted-and-ignored for
	// GPU. Sizing is mutable only while the instance is STOPPED.
	CpuGuaranteePercent int32 `protobuf:"varint,36,opt,name=cpu_guarantee_percent,json=cpuGuaranteePercent,proto3" json:"cpu_guarantee_percent,omitempty"`
	// Strong first discriminator (F1): VM XOR CONTAINER. Immutable after Create.
	InstanceKind InstanceKind `protobuf:"varint,37,opt,name=instance_kind,json=instanceKind,proto3,enum=kacho.cloud.compute.v1.InstanceKind" json:"instance_kind,omitempty"`
	// The single sizing channel (F2): canonical "mt-" slug. A stable name is accepted
	// on input (resolved in the project scope) and echoed here as the mt- slug.
	MachineTypeId string `protobuf:"bytes,38,opt,name=machine_type_id,json=machineTypeId,proto3" json:"machine_type_id,omitempty"`
	// Output-only authoritative size mirror resolved from the MachineType catalog (F2).
	EffectiveResources *EffectiveResources `protobuf:"bytes,39,opt,name=effective_resources,json=effectiveResources,proto3" json:"effective_resources,omitempty"`
	// The single OS entry (F3): {type,id} on input; name°/resolved_digest°/
	// materialized_volume° are output-only (resolve/materialize → COMP-2).
	BootSource *BootSource `protobuf:"bytes,40,opt,name=boot_source,json=bootSource,proto3" json:"boot_source,omitempty"`
	// Opaque placement-group slug (COMP-1 passthrough; existence/coherence → COMP-3).
	PlacementGroupId string `protobuf:"bytes,41,opt,name=placement_group_id,json=placementGroupId,proto3" json:"placement_group_id,omitempty"`
	// Output-only human reason for the current status / a deferred change
	// ("takes effect on next boot").
	StatusReason string `protobuf:"bytes,42,opt,name=status_reason,json=statusReason,proto3" json:"status_reason,omitempty"`
	// Service account used inside the instance (F4, B2): class-C graceful-dangling
	// reference.Referrer{type:"iam.service_account"}. Empty for public images.
	ServiceAccount *reference.Referrer `protobuf:"bytes,43,opt,name=service_account,json=serviceAccount,proto3" json:"service_account,omitempty"`
	// kind-gated spec (F1): exactly one, matching instance_kind (spoken-exclusion XOR).
	//
	// Types that are valid to be assigned to Spec:
	//
	//	*Instance_VmSpec
	//	*Instance_ContainerSpec
	Spec isInstance_Spec `protobuf_oneof:"spec"`
	// Ключи входа гостя, действующие на этой машине.
	//
	// ССЫЛКИ ПО НЕИЗМЕНЯЕМОМУ ИДЕНТИФИКАТОРУ, а не материал ключа. Материал,
	// положенный сюда, жил бы ровно столько, сколько машина: его нельзя ни
	// отозвать, ни заменить, ни узнать, где ещё он используется. Ключ — отдельный
	// ресурс (`GuestAccessKeyService`), и здесь стоит связь с ним.
	//
	// Набор ЗАМЕНЯЕТСЯ целиком при правке: «добавить один» и «оставить как есть»
	// выразимы через полный набор, а частичные глаголы на списке ссылок дали бы
	// два способа сказать одно.
	GuestAccessKeyIds []string `protobuf:"bytes,46,rep,name=guest_access_key_ids,json=guestAccessKeyIds,proto3" json:"guest_access_key_ids,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Instance) Reset() {
	*x = Instance{}
	mi := &file_kacho_cloud_compute_v1_instance_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Instance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Instance) ProtoMessage() {}

func (x *Instance) ProtoReflect() protoreflect.Message {
	mi := &file_kacho_cloud_compute_v1_instance_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Instance.ProtoReflect.Descriptor instead.
func (*Instance) Descriptor() ([]byte, []int) {
	return file_kacho_cloud_compute_v1_instance_proto_rawDescGZIP(), []int{0}
}

func (x *Instance) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Instance) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *Instance) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Instance) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Instance) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Instance) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Instance) GetZoneId() string {
	if x != nil {
		return x.ZoneId
	}
	return ""
}

func (x *Instance) GetStatus() Instance_Status {
	if x != nil {
		return x.Status
	}
	return Instance_STATUS_UNSPECIFIED
}

func (x *Instance) GetBootDisk() *AttachedDisk {
	if x != nil {
		return x.BootDisk
	}
	return nil
}

func (x *Instance) GetSecondaryDisks() []*AttachedDisk {
	if x != nil {
		return x.SecondaryDisks
	}
	return nil
}

func (x *Instance) GetNetworkInterfaces() []*NetworkInterface {
	if x != nil {
		return x.NetworkInterfaces
	}
	return nil
}

func (x *Instance) GetFqdn() string {
	if x != nil {
		return x.Fqdn
	}
	return ""
}

func (x *Instance) GetCpuGuaranteePercent() int32 {
	if x != nil {
		return x.CpuGuaranteePercent
	}
	return 0
}

func (x *Instance) GetInstanceKind() InstanceKind {
	if x != nil {
		return x.InstanceKind
	}
	return InstanceKind_INSTANCE_KIND_UNSPECIFIED
}

func (x *Instance) GetMachineTypeId() string {
	if x != nil {
		return x.MachineTypeId
	}
	return ""
}

func (x *Instance) GetEffectiveResources() *EffectiveResources {
	if x != nil {
		return x.EffectiveResources
	}
	return nil
}

func (x *Instance) GetBootSource() *BootSource {
	if x != nil {
		return x.BootSource
	}
	return nil
}

func (x *Instance) GetPlacementGroupId() string {
	if x != nil {
		return x.PlacementGroupId
	}
	return ""
}

func (x *Instance) GetStatusReason() string {
	if x != nil {
		return x.StatusReason
	}
	return ""
}

func (x *Instance) GetServiceAccount() *reference.Referrer {
	if x != nil {
		return x.ServiceAccount
	}
	return nil
}

func (x *Instance) GetSpec() isInstance_Spec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *Instance) GetVmSpec() *VmSpec {
	if x != nil {
		if x, ok := x.Spec.(*Instance_VmSpec); ok {
			return x.VmSpec
		}
	}
	return nil
}

func (x *Instance) GetContainerSpec() *ContainerSpec {
	if x != nil {
		if x, ok := x.Spec.(*Instance_ContainerSpec); ok {
			return x.ContainerSpec
		}
	}
	return nil
}

func (x *Instance) GetGuestAccessKeyIds() []string {
	if x != nil {
		return x.GuestAccessKeyIds
	}
	return nil
}

type isInstance_Spec interface {
	isInstance_Spec()
}

type Instance_VmSpec struct {
	// VM configuration (instance_kind = VM).
	VmSpec *VmSpec `protobuf:"bytes,44,opt,name=vm_spec,json=vmSpec,proto3,oneof"`
}

type Instance_ContainerSpec struct {
	// CONTAINER configuration (instance_kind = CONTAINER).
	ContainerSpec *ContainerSpec `protobuf:"bytes,45,opt,name=container_spec,json=containerSpec,proto3,oneof"`
}

func (*Instance_VmSpec) isInstance_Spec() {}

func (*Instance_ContainerSpec) isInstance_Spec() {}

// BootSource — the single OS entry (F3, B13). On INPUT only {type,id} are accepted;
// name°/resolved_digest°/materialized_volume°/image_kind° are output-only (the
// resolve/materialize saga is COMP-2). tag/digest live INSIDE id (one grammar for
// all inputs). A request that sets any of the four is refused synchronously with
// INVALID_ARGUMENT naming all four — accepted-and-ignored is not a lawful outcome.
type BootSource struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Owner discriminator: "storage.image" (OS/disk image, VM) or "registry.image"
	// (OCI container image, CONTAINER). Routes the resolve to storage vs registry.
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// Image id with a tag or digest inside: "img-<base32>:<tag>" /
	// "img-<base32>@sha256:<hex>" (storage.image) or "repo/name:tag" (registry.image).
	Id string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	// Output-only image display name at bind time (best-effort; filled by resolve, COMP-2).
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// Output-only immutable content digest that `id` was pinned to (filled by resolve, COMP-2).
	ResolvedDigest string `protobuf:"bytes,4,opt,name=resolved_digest,json=resolvedDigest,proto3" json:"resolved_digest,omitempty"`
	// Output-only materialized boot Volume (filled by the boot-Volume saga, COMP-2).
	// Absent by construction for CONTAINER (ephemeral rootfs).
	MaterializedVolume *MaterializedVolume `protobuf:"bytes,5,opt,name=materialized_volume,json=materializedVolume,proto3" json:"materialized_volume,omitempty"`
	// Output-only imageKind discriminator (B13): storage.image vs registry.image.
	// DERIVED BY THE SERVER from `type`; NOT ACCEPTED ON INPUT — a set value is
	// refused with INVALID_ARGUMENT. The marker is spelled out because the enum
	// below publishes a value dictionary, which reads like an input: a caller who
	// filled it in got a refusal that named the other three output-only fields and
	// stayed silent about this one, so removing what the text named changed nothing.
	ImageKind     ImageKind `protobuf:"varint,6,opt,name=image_kind,json=imageKind,proto3,enum=kacho.cloud.compute.v1.ImageKind" json:"image_kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BootSource) Reset() {
	*x = BootSource{}
	mi := &file_kacho_cloud_compute_v1_instance_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BootSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootSource) ProtoMessage() {}

func (x *BootSource) ProtoReflect() protoreflect.Message {
	mi := &file_kacho_cloud_compute_v1_instance_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootSource.ProtoReflect.Descriptor instead.
func (*BootSource) Descriptor() ([]byte, []int) {
	return file_kacho_cloud_compute_v1_instance_proto_rawDescGZIP(), []int{1}
}

func (x *BootSource) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *BootSource) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BootSource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BootSource) GetResolvedDigest() string {
	if x != nil {
		return x.ResolvedDigest
	}
	return ""
}

func (x *BootSource) GetMaterializedVolume() *MaterializedVolume {
	if x != nil {
		return x.MaterializedVolume
	}
	return nil
}

func (x *BootSource) GetImageKind() ImageKind {
	if x != nil {
		return x.ImageKind
	}
	return ImageKind_IMAGE_KIND_UNSPECIFIED
}

// MaterializedVolume — output-only mirror of the boot Volume the OS was materialized
// onto (filled by the COMP-2 boot-Volume saga). Sizes are echoed in both bytes and GiB.
type MaterializedVolume struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the storage Volume the boot image was materialized onto.
	VolumeId string `protobuf:"bytes,1,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"`
	// Size in bytes.
	SizeBytes int64 `protobuf:"varint,2,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	// Size in GiB (human-scale echo).
	SizeGib int64 `protobuf:"varint,3,opt,name=size_gib,json=sizeGib,proto3" json:"size_gib,omitempty"`
	// Volume type the boot Volume was created with.
	VolumeTypeId  string `protobuf:"bytes,4,opt,name=volume_type_id,json=volumeTypeId,proto3" json:"volume_type_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MaterializedVolume) Reset() {
	*x = MaterializedVolume{}
	mi := &file_kacho_cloud_compute_v1_instance_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaterializedVolume) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaterializedVolume) ProtoMessage() {}

func (x *MaterializedVolume) ProtoReflect() protoreflect.Message {
	mi := &file_kacho_cloud_compute_v1_instance_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaterializedVolume.ProtoReflect.Descriptor instead.
func (*MaterializedVolume) Descriptor() ([]byte, []int) {
	return file_kacho_cloud_compute_v1_instance_proto_rawDescGZIP(), []int{2}
}

func (x *MaterializedVolume) GetVolumeId() string {
	if x != nil {
		return x.VolumeId
	}
	return ""
}

func (x *MaterializedVolume) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *MaterializedVolume) GetSizeGib() int64 {
	if x != nil {
		return x.SizeGib
	}
	return 0
}

func (x *MaterializedVolume) GetVolumeTypeId() string {
	if x != nil {
		return x.VolumeTypeId
	}
	return ""
}

// VmSpec — VM configuration (instance_kind = VM).
type VmSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// cloud-config / cloud-init user data.
	UserData string `protobuf:"bytes,1,opt,name=user_data,json=userData,proto3" json:"user_data,omitempty"`
	// Vendor-agnostic metadata-service options.
	MetadataOptions *MetadataOptions `protobuf:"bytes,2,opt,name=metadata_options,json=metadataOptions,proto3" json:"metadata_options,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *VmSpec) Reset() {
	*x = VmSpec{}
	mi := &file_kacho_cloud_compute_v1_instance_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VmSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VmSpec) ProtoMessage() {}

func (x *VmSpec) ProtoReflect() protoreflect.Message {
	mi := &file_kacho_cloud_compute_v1_instance_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VmSpec.ProtoReflect.Descriptor instead.
func (*VmSpec) Descriptor() ([]byte, []int) {
	return file_kacho_cloud_compute_v1_instance_proto_rawDescGZIP(), []int{3}
}

func (x *VmSpec) GetUserData() string {
	if x != nil {
		return x.UserData
	}
	return ""
}

func (x *VmSpec) GetMetadataOptions() *MetadataOptions {
	if x != nil {
		return x.MetadataOptions
	}
	return nil
}

// ContainerSpec — CONTAINER job configuration (instance_kind = CONTAINER). A
// first-class job: SUCCEEDED/FAILED terminal states carry exit_code°.
type ContainerSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Entry point.
	Command []string `protobuf:"bytes,1,rep,name=command,proto3" json:"command,omitempty"`
	// Arguments to the entry point.
	Args []string `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	// Environment variables.
	Env map[string]string `protobuf:"bytes,3,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Working directory.
	WorkingDir string `protobuf:"bytes,4,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`
	// Exposed ports.
	Ports []*ContainerPort `protobuf:"bytes,5,rep,name=ports,proto3" json:"ports,omitempty"`
	// Restart policy (default NEVER).
	RestartPolicy RestartPolicy `protobuf:"varint,6,opt,name=restart_policy,json=restartPolicy,proto3,enum=kacho.cloud.compute.v1.RestartPolicy" json:"restart_policy,omitempty"`
	// Output-only exit code (set on a terminal SUCCEEDED/FAILED job; empty until
	// then). NOT ACCEPTED ON INPUT: `ContainerSpec` also stands in
	// CreateInstanceRequest, and a set value there is refused synchronously with
	// INVALID_ARGUMENT naming `container_spec.exit_code` (accepted-and-ignored is
	// not a lawful outcome).
	ExitCode      int32 `protobuf:"varint,7,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerSpec) Reset() {
	*x = ContainerSpec{}
	mi := &file_kacho_cloud_compute_v1_instance_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerSpec) ProtoMessage() {}

func (x *ContainerSpec) ProtoReflect() protoreflect.Message {
	mi := &file_kacho_cloud_compute_v1_instance_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerSpec.ProtoReflect.Descriptor instead.
func (*ContainerSpec) Descriptor() ([]byte, []int) {
	return file_kacho_cloud_compute_v1_instance_proto_rawDescGZIP(), []int{4}
}

func (x *ContainerSpec) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *ContainerSpec) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ContainerSpec) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *ContainerSpec) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

func (x *ContainerSpec) GetPorts() []*ContainerPort {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *ContainerSpec) GetRestartPolicy() RestartPolicy {
	if x != nil {
		return x.RestartPolicy
	}
	return RestartPolicy_RESTART_POLICY_UNSPECIFIED
}

func (x *ContainerSpec) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

// ContainerPort — a container port declaration.
type ContainerPort struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Container port number.
	ContainerPort int32 `protobuf:"varint,1,opt,name=container_port,json=containerPort,proto3" json:"container_port,omitempty"`
	// Protocol ("TCP"/"UDP"; empty = TCP).
	Protocol      string `protobuf:"bytes,2,opt,name=protocol,proto3" json:"protocol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerPort) Reset() {
	*x = ContainerPort{}
	mi := &file_kacho_cloud_compute_v1_instance_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerPort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerPort) ProtoMessage() {}

func (x *ContainerPort) ProtoReflect() protoreflect.Message {
	mi := &file_kacho_cloud_compute_v1_instance_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerPort.ProtoReflect.Descriptor instead.
func (*ContainerPort) Descriptor() ([]byte, []int) {
	return file_kacho_cloud_compute_v1_instance_proto_rawDescGZIP(), []int{5}
}

func (x *ContainerPort) GetContainerPort() int32 {
	if x != nil {
		return x.ContainerPort
	}
	return 0
}

func (x *ContainerPort) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

type AttachedDisk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Access mode to the Disk resource.
	Mode AttachedDisk_Mode `protobuf:"varint,1,opt,name=mode,proto3,enum=kacho.cloud.compute.v1.AttachedDisk_Mode" json:"mode,omitempty"`
	// Serial number that is reflected into the /dev/disk/by-id/ tree
	// of a Linux operating system running within the instance.
	//
	// This value can be used to reference the device for mounting, resizing, and so on, from within the instance.
	DeviceName string `protobuf:"bytes,2,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	// Specifies whether the disk will be auto-deleted when the instance is deleted.
	AutoDelete bool `protobuf:"varint,3,opt,name=auto_delete,json=autoDelete,proto3" json:"auto_delete,omitempty"`
	// ID of the storage Volume (`kacho.cloud.storage.v1.Volume`, prefix "vol") that
	// is attached to the instance. Cross-service reference (no FK); source of truth
	// is the storage `volume_attachments` row.
	VolumeId      string `protobuf:"bytes,4,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachedDisk) Reset() {
	*x = AttachedDisk{}
	mi := &file_kacho_cloud_compute_v1_instance_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachedDisk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachedDisk) ProtoMessage() {}

func (x *AttachedDisk) ProtoReflect() protoreflect.Message {
	mi := &file_kacho_cloud_compute_v1_instance_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachedDisk.ProtoReflect.Descriptor instead.
func (*AttachedDisk) Descriptor() ([]byte, []int) {
	return file_kacho_cloud_compute_v1_instance_proto_rawDescGZIP(), []int{6}
}

func (x *AttachedDisk) GetMode() AttachedDisk_Mode {
	if x != nil {
		return x.Mode
	}
	return AttachedDisk_MODE_UNSPECIFIED
}

func (x *AttachedDisk) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *AttachedDisk) GetAutoDelete() bool {
	if x != nil {
		return x.AutoDelete
	}
	return false
}

func (x *AttachedDisk) GetVolumeId() string {
	if x != nil {
		return x.VolumeId
	}
	return ""
}

type NetworkInterface struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The index of the network interface, will be generated by the server, 0,1,2... etc if not specified.
	Index string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	// MAC address that is assigned to the network interface.
	MacAddress string `protobuf:"bytes,2,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`
	// ID of the subnet.
	SubnetId string `protobuf:"bytes,3,opt,name=subnet_id,json=subnetId,proto3" json:"subnet_id,omitempty"`
	// Primary IPv4 address that is assigned to the instance for this network interface.
	PrimaryV4Address *PrimaryAddress `protobuf:"bytes,4,opt,name=primary_v4_address,json=primaryV4Address,proto3" json:"primary_v4_address,omitempty"`
	// Primary IPv6 address that is assigned to the instance for this network interface. IPv6 not available yet.
	PrimaryV6Address *PrimaryAddress `protobuf:"bytes,5,opt,name=primary_v6_address,json=primaryV6Address,proto3" json:"primary_v6_address,omitempty"`
	// ID's of security groups attached to the interface
	SecurityGroupIds []string `protobuf:"bytes,6,rep,name=security_group_ids,json=securityGroupIds,proto3" json:"security_group_ids,omitempty"`
	// ID of the kacho-vpc NetworkInterface (NIC) resource backing this interface.
	// The NIC resource is the source of truth for the interface (address, security
	// groups, data-plane wiring); `subnet_id` / `primary_v4_address` above are a
	// read-only denormalised mirror of it. See vpc/v1/network_interface.proto.
	NicId         string `protobuf:"bytes,7,opt,name=nic_id,json=nicId,proto3" json:"nic_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkInterface) Reset() {
	*x = NetworkInterface{}
	mi := &file_kacho_cloud_compute_v1_instance_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkInterface) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkInterface) ProtoMessage() {}

func (x *NetworkInterface) ProtoReflect() protoreflect.Message {
	mi := &file_kacho_cloud_compute_v1_instance_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkInterface.ProtoReflect.Descriptor instead.
func (*NetworkInterface) Descriptor() ([]byte, []int) {
	return file_kacho_cloud_compute_v1_instance_proto_rawDescGZIP(), []int{7}
}

func (x *NetworkInterface) GetIndex() string {
	if x != nil {
		return x.Index
	}
	return ""
}

func (x *NetworkInterface) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

func (x *NetworkInterface) GetSubnetId() string {
	if x != nil {
		return x.SubnetId
	}
	return ""
}

func (x *NetworkInterface) GetPrimaryV4Address() *PrimaryAddress {
	if x != nil {
		return x.PrimaryV4Address
	}
	return nil
}

func (x *NetworkInterface) GetPrimaryV6Address() *PrimaryAddress {
	if x != nil {
		return x.PrimaryV6Address
	}
	return nil
}

func (x *NetworkInterface) GetSecurityGroupIds() []string {
	if x != nil {
		return x.SecurityGroupIds
	}
	return nil
}

func (x *NetworkInterface) GetNicId() string {
	if x != nil {
		return x.NicId
	}
	return ""
}

type PrimaryAddress struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// An IPv4 internal network address that is assigned to the instance for this network interface.
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// One-to-one NAT configuration. If missing, NAT has not been set up.
	OneToOneNat   *OneToOneNat `protobuf:"bytes,2,opt,name=one_to_one_nat,json=oneToOneNat,proto3" json:"one_to_one_nat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrimaryAddress) Reset() {
	*x = PrimaryAddress{}
	mi := &file_kacho_cloud_compute_v1_instance_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrimaryAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrimaryAddress) ProtoMessage() {}

func (x *PrimaryAddress) ProtoReflect() protoreflect.Message {
	mi := &file_kacho_cloud_compute_v1_instance_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrimaryAddress.ProtoReflect.Descriptor instead.
func (*PrimaryAddress) Descriptor() ([]byte, []int) {
	return file_kacho_cloud_compute_v1_instance_proto_rawDescGZIP(), []int{8}
}

func (x *PrimaryAddress) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *PrimaryAddress) GetOneToOneNat() *OneToOneNat {
	if x != nil {
		return x.OneToOneNat
	}
	return nil
}

type OneToOneNat struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// An external IP address associated with this instance.
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// IP version for the external IP address.
	IpVersion     IpVersion `protobuf:"varint,2,opt,name=ip_version,json=ipVersion,proto3,enum=kacho.cloud.compute.v1.IpVersion" json:"ip_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OneToOneNat) Reset() {
	*x = OneToOneNat{}
	mi := &file_kacho_cloud_compute_v1_instance_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OneToOneNat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OneToOneNat) ProtoMessage() {}

func (x *OneToOneNat) ProtoReflect() protoreflect.Message {
	mi := &file_kacho_cloud_compute_v1_instance_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OneToOneNat.ProtoReflect.Descriptor instead.
func (*OneToOneNat) Descriptor() ([]byte, []int) {
	return file_kacho_cloud_compute_v1_instance_proto_rawDescGZIP(), []int{9}
}

func (x *OneToOneNat) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *OneToOneNat) GetIpVersion() IpVersion {
	if x != nil {
		return x.IpVersion
	}
	return IpVersion_IP_VERSION_UNSPECIFIED
}

type NetworkSettings struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Network Type
	Type          NetworkSettings_Type `protobuf:"varint,1,opt,name=type,proto3,enum=kacho.cloud.compute.v1.NetworkSettings_Type" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkSettings) Reset() {
	*x = NetworkSettings{}
	mi := &file_kacho_cloud_compute_v1_instance_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkSettings) ProtoMessage() {}

func (x *NetworkSettings) ProtoReflect() protoreflect.Message {
	mi := &file_kacho_cloud_compute_v1_instance_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkSettings.ProtoReflect.Descriptor instead.
func (*NetworkSettings) Descriptor() ([]byte, []int) {
	return file_kacho_cloud_compute_v1_instance_proto_rawDescGZIP(), []int{10}
}

func (x *NetworkSettings) GetType() NetworkSettings_Type {
	if x != nil {
		return x.Type
	}
	return NetworkSettings_TYPE_UNSPECIFIED
}

// MetadataOptions — vendor-agnostic metadata-service options (F9, ban #2). The
// brand-flavored gce_*/aws_* surface is retired (field numbers + names reserved so
// they can never be reused). Lives under vm_spec.
type MetadataOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the instance metadata endpoint is reachable from the guest.
	MetadataEndpoint MetadataOption `protobuf:"varint,7,opt,name=metadata_endpoint,json=metadataEndpoint,proto3,enum=kacho.cloud.compute.v1.MetadataOption" json:"metadata_endpoint,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MetadataOptions) Reset() {
	*x = MetadataOptions{}
	mi := &file_kacho_cloud_compute_v1_instance_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataOptions) ProtoMessage() {}

func (x *MetadataOptions) ProtoReflect() protoreflect.Message {
	mi := &file_kacho_cloud_compute_v1_instance_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataOptions.ProtoReflect.Descriptor instead.
func (*MetadataOptions) Descriptor() ([]byte, []int) {
	return file_kacho_cloud_compute_v1_instance_proto_rawDescGZIP(), []int{11}
}

func (x *MetadataOptions) GetMetadataEndpoint() MetadataOption {
	if x != nil {
		return x.MetadataEndpoint
	}
	return MetadataOption_METADATA_OPTION_UNSPECIFIED
}

type SerialPortSettings struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Authentication and authorization in serial console when using SSH protocol
	SshAuthorization SerialPortSettings_SSHAuthorization `protobuf:"varint,1,opt,name=ssh_authorization,json=sshAuthorization,proto3,enum=kacho.cloud.compute.v1.SerialPortSettings_SSHAuthorization" json:"ssh_authorization,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SerialPortSettings) Reset() {
	*x = SerialPortSettings{}
	mi := &file_kacho_cloud_compute_v1_instance_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SerialPortSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SerialPortSettings) ProtoMessage() {}

func (x *SerialPortSettings) ProtoReflect() protoreflect.Message {
	mi := &file_kacho_cloud_compute_v1_instance_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SerialPortSettings.ProtoReflect.Descriptor instead.
func (*SerialPortSettings) Descriptor() ([]byte, []int) {
	return file_kacho_cloud_compute_v1_instance_proto_rawDescGZIP(), []int{12}
}

func (x *SerialPortSettings) GetSshAuthorization() SerialPortSettings_SSHAuthorization {
	if x != nil {
		return x.SshAuthorization
	}
	return SerialPortSettings_SSH_AUTHORIZATION_UNSPECIFIED
}

var File_kacho_cloud_compute_v1_instance_proto protoreflect.FileDescriptor

const file_kacho_cloud_compute_v1_instance_proto_rawDesc = "" +
	"\n" +
	"%kacho/cloud/compute/v1/instance.proto\x12\x16kacho.cloud.compute.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a)kacho/cloud/compute/v1/machine_type.proto\x1a%kacho/cloud/reference/reference.proto\"\xbc\x0f\n" +
	"\bInstance\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12D\n" +
	"\x06labels\x18\x06 \x03(\v2,.kacho.cloud.compute.v1.Instance.LabelsEntryR\x06labels\x12\x17\n" +
	"\azone_id\x18\a \x01(\tR\x06zoneId\x12?\n" +
	"\x06status\x18\n" +
	" \x01(\x0e2'.kacho.cloud.compute.v1.Instance.StatusR\x06status\x12A\n" +
	"\tboot_disk\x18\f \x01(\v2$.kacho.cloud.compute.v1.AttachedDiskR\bbootDisk\x12M\n" +
	"\x0fsecondary_disks\x18\r \x03(\v2$.kacho.cloud.compute.v1.AttachedDiskR\x0esecondaryDisks\x12W\n" +
	"\x12network_interfaces\x18\x0e \x03(\v2(.kacho.cloud.compute.v1.NetworkInterfaceR\x11networkInterfaces\x12\x12\n" +
	"\x04fqdn\x18\x10 \x01(\tR\x04fqdn\x122\n" +
	"\x15cpu_guarantee_percent\x18$ \x01(\x05R\x13cpuGuaranteePercent\x12I\n" +
	"\rinstance_kind\x18% \x01(\x0e2$.kacho.cloud.compute.v1.InstanceKindR\finstanceKind\x12&\n" +
	"\x0fmachine_type_id\x18& \x01(\tR\rmachineTypeId\x12[\n" +
	"\x13effective_resources\x18' \x01(\v2*.kacho.cloud.compute.v1.EffectiveResourcesR\x12effectiveResources\x12C\n" +
	"\vboot_source\x18( \x01(\v2\".kacho.cloud.compute.v1.BootSourceR\n" +
	"bootSource\x12,\n" +
	"\x12placement_group_id\x18) \x01(\tR\x10placementGroupId\x12#\n" +
	"\rstatus_reason\x18* \x01(\tR\fstatusReason\x12H\n" +
	"\x0fservice_account\x18+ \x01(\v2\x1f.kacho.cloud.reference.ReferrerR\x0eserviceAccount\x129\n" +
	"\avm_spec\x18, \x01(\v2\x1e.kacho.cloud.compute.v1.VmSpecH\x00R\x06vmSpec\x12N\n" +
	"\x0econtainer_spec\x18- \x01(\v2%.kacho.cloud.compute.v1.ContainerSpecH\x00R\rcontainerSpec\x12/\n" +
	"\x14guest_access_key_ids\x18. \x03(\tR\x11guestAccessKeyIds\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xac\x01\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fPROVISIONING\x10\x01\x12\v\n" +
	"\aRUNNING\x10\x02\x12\f\n" +
	"\bSTOPPING\x10\x03\x12\v\n" +
	"\aSTOPPED\x10\x04\x12\f\n" +
	"\bSTARTING\x10\x05\x12\x0e\n" +
	"\n" +
	"RESTARTING\x10\x06\x12\f\n" +
	"\bUPDATING\x10\a\x12\t\n" +
	"\x05ERROR\x10\b\x12\v\n" +
	"\aCRASHED\x10\t\x12\f\n" +
	"\bDELETING\x10\n" +
	"B\x06\n" +
	"\x04specJ\x04\b\b\x10\tJ\x04\b\t\x10\n" +
	"J\x04\b\x11\x10\x12J\x04\b\x12\x10\x13J\x04\b\x14\x10\x15J\x04\b\x17\x10\x18J\x04\b\x1a\x10\x1bJ\x04\b \x10!J\x04\b!\x10\"J\x04\b\"\x10#J\x04\b#\x10$J\x04\b\x0f\x10\x10J\x04\b\x19\x10\x1aJ\x04\b\x1b\x10\x1cJ\x04\b\x1c\x10\x1dJ\x04\b\v\x10\fJ\x04\b\x13\x10\x14J\x04\b\x15\x10\x16J\x04\b\x16\x10\x17J\x04\b\x18\x10\x19J\x04\b\x1d\x10\x1eJ\x04\b\x1e\x10\x1fJ\x04\b\x1f\x10 R\vplatform_idR\tresourcesR\x11scheduling_policyR\x12service_account_idR\x10placement_policyR\x10metadata_optionsR\fgpu_settingsR\x19reserved_instance_pool_idR\vapplicationR\x05imageR\fimage_digestR\rhost_group_idR\ahost_idR\bmetadataR\x10network_settingsR\vfilesystemsR\vlocal_disksR\x14serial_port_settingsR\x12maintenance_policyR\x18maintenance_grace_periodR\x13hardware_generation\"\x8c\x02\n" +
	"\n" +
	"BootSource\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12'\n" +
	"\x0fresolved_digest\x18\x04 \x01(\tR\x0eresolvedDigest\x12[\n" +
	"\x13materialized_volume\x18\x05 \x01(\v2*.kacho.cloud.compute.v1.MaterializedVolumeR\x12materializedVolume\x12@\n" +
	"\n" +
	"image_kind\x18\x06 \x01(\x0e2!.kacho.cloud.compute.v1.ImageKindR\timageKind\"\x91\x01\n" +
	"\x12MaterializedVolume\x12\x1b\n" +
	"\tvolume_id\x18\x01 \x01(\tR\bvolumeId\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x02 \x01(\x03R\tsizeBytes\x12\x19\n" +
	"\bsize_gib\x18\x03 \x01(\x03R\asizeGib\x12$\n" +
	"\x0evolume_type_id\x18\x04 \x01(\tR\fvolumeTypeId\"y\n" +
	"\x06VmSpec\x12\x1b\n" +
	"\tuser_data\x18\x01 \x01(\tR\buserData\x12R\n" +
	"\x10metadata_options\x18\x02 \x01(\v2'.kacho.cloud.compute.v1.MetadataOptionsR\x0fmetadataOptions\"\x80\x03\n" +
	"\rContainerSpec\x12\x18\n" +
	"\acommand\x18\x01 \x03(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x02 \x03(\tR\x04args\x12@\n" +
	"\x03env\x18\x03 \x03(\v2..kacho.cloud.compute.v1.ContainerSpec.EnvEntryR\x03env\x12\x1f\n" +
	"\vworking_dir\x18\x04 \x01(\tR\n" +
	"workingDir\x12;\n" +
	"\x05ports\x18\x05 \x03(\v2%.kacho.cloud.compute.v1.ContainerPortR\x05ports\x12L\n" +
	"\x0erestart_policy\x18\x06 \x01(\x0e2%.kacho.cloud.compute.v1.RestartPolicyR\rrestartPolicy\x12\x1b\n" +
	"\texit_code\x18\a \x01(\x05R\bexitCode\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"R\n" +
	"\rContainerPort\x12%\n" +
	"\x0econtainer_port\x18\x01 \x01(\x05R\rcontainerPort\x12\x1a\n" +
	"\bprotocol\x18\x02 \x01(\tR\bprotocol\"\xe9\x01\n" +
	"\fAttachedDisk\x12=\n" +
	"\x04mode\x18\x01 \x01(\x0e2).kacho.cloud.compute.v1.AttachedDisk.ModeR\x04mode\x12\x1f\n" +
	"\vdevice_name\x18\x02 \x01(\tR\n" +
	"deviceName\x12\x1f\n" +
	"\vauto_delete\x18\x03 \x01(\bR\n" +
	"autoDelete\x12\x1b\n" +
	"\tvolume_id\x18\x04 \x01(\tR\bvolumeId\";\n" +
	"\x04Mode\x12\x14\n" +
	"\x10MODE_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tREAD_ONLY\x10\x01\x12\x0e\n" +
	"\n" +
	"READ_WRITE\x10\x02\"\xd7\x02\n" +
	"\x10NetworkInterface\x12\x14\n" +
	"\x05index\x18\x01 \x01(\tR\x05index\x12\x1f\n" +
	"\vmac_address\x18\x02 \x01(\tR\n" +
	"macAddress\x12\x1b\n" +
	"\tsubnet_id\x18\x03 \x01(\tR\bsubnetId\x12T\n" +
	"\x12primary_v4_address\x18\x04 \x01(\v2&.kacho.cloud.compute.v1.PrimaryAddressR\x10primaryV4Address\x12T\n" +
	"\x12primary_v6_address\x18\x05 \x01(\v2&.kacho.cloud.compute.v1.PrimaryAddressR\x10primaryV6Address\x12,\n" +
	"\x12security_group_ids\x18\x06 \x03(\tR\x10securityGroupIds\x12\x15\n" +
	"\x06nic_id\x18\a \x01(\tR\x05nicId\"\x87\x01\n" +
	"\x0ePrimaryAddress\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12H\n" +
	"\x0eone_to_one_nat\x18\x02 \x01(\v2#.kacho.cloud.compute.v1.OneToOneNatR\voneToOneNatJ\x04\b\x03\x10\x04R\vdns_records\"|\n" +
	"\vOneToOneNat\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12@\n" +
	"\n" +
	"ip_version\x18\x02 \x01(\x0e2!.kacho.cloud.compute.v1.IpVersionR\tipVersionJ\x04\b\x03\x10\x04R\vdns_records\"\xb3\x01\n" +
	"\x0fNetworkSettings\x12@\n" +
	"\x04type\x18\x01 \x01(\x0e2,.kacho.cloud.compute.v1.NetworkSettings.TypeR\x04type\"^\n" +
	"\x04Type\x12\x14\n" +
	"\x10TYPE_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bSTANDARD\x10\x01\x12\x18\n" +
	"\x14SOFTWARE_ACCELERATED\x10\x02\x12\x18\n" +
	"\x14HARDWARE_ACCELERATED\x10\x03\"\x9e\x02\n" +
	"\x0fMetadataOptions\x12S\n" +
	"\x11metadata_endpoint\x18\a \x01(\x0e2&.kacho.cloud.compute.v1.MetadataOptionR\x10metadataEndpointJ\x04\b\x01\x10\x02J\x04\b\x02\x10\x03J\x04\b\x03\x10\x04J\x04\b\x04\x10\x05J\x04\b\x05\x10\x06J\x04\b\x06\x10\aJ\x04\b\b\x10\tR\x11gce_http_endpointR\x14aws_v1_http_endpointR\x0egce_http_tokenR\x11aws_v1_http_tokenR\x14aws_v2_http_endpointR\x11aws_v2_http_tokenR\x17metadata_token_required\"\xda\x01\n" +
	"\x12SerialPortSettings\x12h\n" +
	"\x11ssh_authorization\x18\x01 \x01(\x0e2;.kacho.cloud.compute.v1.SerialPortSettings.SSHAuthorizationR\x10sshAuthorization\"Z\n" +
	"\x10SSHAuthorization\x12!\n" +
	"\x1dSSH_AUTHORIZATION_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11INSTANCE_METADATA\x10\x01\x12\f\n" +
	"\bOS_LOGIN\x10\x02*D\n" +
	"\fInstanceKind\x12\x1d\n" +
	"\x19INSTANCE_KIND_UNSPECIFIED\x10\x00\x12\x06\n" +
	"\x02VM\x10\x01\x12\r\n" +
	"\tCONTAINER\x10\x02*I\n" +
	"\tImageKind\x12\x1a\n" +
	"\x16IMAGE_KIND_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rSTORAGE_IMAGE\x10\x01\x12\r\n" +
	"\tOCI_IMAGE\x10\x02*V\n" +
	"\rRestartPolicy\x12\x1e\n" +
	"\x1aRESTART_POLICY_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05NEVER\x10\x01\x12\x0e\n" +
	"\n" +
	"ON_FAILURE\x10\x02\x12\n" +
	"\n" +
	"\x06ALWAYS\x10\x03*;\n" +
	"\tIpVersion\x12\x1a\n" +
	"\x16IP_VERSION_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04IPV4\x10\x01\x12\b\n" +
	"\x04IPV6\x10\x02*L\n" +
	"\x0eMetadataOption\x12\x1f\n" +
	"\x1bMETADATA_OPTION_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aENABLED\x10\x01\x12\f\n" +
	"\bDISABLED\x10\x02BHZFgithub.com/PRO-Robotech/kacho/pkg/api/kacho/cloud/compute/v1;computev1b\x06proto3"

var (
	file_kacho_cloud_compute_v1_instance_proto_rawDescOnce sync.Once
	file_kacho_cloud_compute_v1_instance_proto_rawDescData []byte
)

func file_kacho_cloud_compute_v1_instance_proto_rawDescGZIP() []byte {
	file_kacho_cloud_compute_v1_instance_proto_rawDescOnce.Do(func() {
		file_kacho_cloud_compute_v1_instance_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kacho_cloud_compute_v1_instance_proto_rawDesc), len(file_kacho_cloud_compute_v1_instance_proto_rawDesc)))
	})
	return file_kacho_cloud_compute_v1_instance_proto_rawDescData
}

var file_kacho_cloud_compute_v1_instance_proto_enumTypes = make([]protoimpl.EnumInfo, 9)
var file_kacho_cloud_compute_v1_instance_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_kacho_cloud_compute_v1_instance_proto_goTypes = []any{
	(InstanceKind)(0),                        // 0: kacho.cloud.compute.v1.InstanceKind
	(ImageKind)(0),                           // 1: kacho.cloud.compute.v1.ImageKind
	(RestartPolicy)(0),                       // 2: kacho.cloud.compute.v1.RestartPolicy
	(IpVersion)(0),                           // 3: kacho.cloud.compute.v1.IpVersion
	(MetadataOption)(0),                      // 4: kacho.cloud.compute.v1.MetadataOption
	(Instance_Status)(0),                     // 5: kacho.cloud.compute.v1.Instance.Status
	(AttachedDisk_Mode)(0),                   // 6: kacho.cloud.compute.v1.AttachedDisk.Mode
	(NetworkSettings_Type)(0),                // 7: kacho.cloud.compute.v1.NetworkSettings.Type
	(SerialPortSettings_SSHAuthorization)(0), // 8: kacho.cloud.compute.v1.SerialPortSettings.SSHAuthorization
	(*Instance)(nil),                         // 9: kacho.cloud.compute.v1.Instance
	(*BootSource)(nil),                       // 10: kacho.cloud.compute.v1.BootSource
	(*MaterializedVolume)(nil),               // 11: kacho.cloud.compute.v1.MaterializedVolume
	(*VmSpec)(nil),                           // 12: kacho.cloud.compute.v1.VmSpec
	(*ContainerSpec)(nil),                    // 13: kacho.cloud.compute.v1.ContainerSpec
	(*ContainerPort)(nil),                    // 14: kacho.cloud.compute.v1.ContainerPort
	(*AttachedDisk)(nil),                     // 15: kacho.cloud.compute.v1.AttachedDisk
	(*NetworkInterface)(nil),                 // 16: kacho.cloud.compute.v1.NetworkInterface
	(*PrimaryAddress)(nil),                   // 17: kacho.cloud.compute.v1.PrimaryAddress
	(*OneToOneNat)(nil),                      // 18: kacho.cloud.compute.v1.OneToOneNat
	(*NetworkSettings)(nil),                  // 19: kacho.cloud.compute.v1.NetworkSettings
	(*MetadataOptions)(nil),                  // 20: kacho.cloud.compute.v1.MetadataOptions
	(*SerialPortSettings)(nil),               // 21: kacho.cloud.compute.v1.SerialPortSettings
	nil,                                      // 22: kacho.cloud.compute.v1.Instance.LabelsEntry
	nil,                                      // 23: kacho.cloud.compute.v1.ContainerSpec.EnvEntry
	(*timestamppb.Timestamp)(nil),            // 24: google.protobuf.Timestamp
	(*EffectiveResources)(nil),               // 25: kacho.cloud.compute.v1.EffectiveResources
	(*reference.Referrer)(nil),               // 26: kacho.cloud.reference.Referrer
}
var file_kacho_cloud_compute_v1_instance_proto_depIdxs = []int32{
	24, // 0: kacho.cloud.compute.v1.Instance.created_at:type_name -> google.protobuf.Timestamp
	22, // 1: kacho.cloud.compute.v1.Instance.labels:type_name -> kacho.cloud.compute.v1.Instance.LabelsEntry
	5,  // 2: kacho.cloud.compute.v1.Instance.status:type_name -> kacho.cloud.compute.v1.Instance.Status
	15, // 3: kacho.cloud.compute.v1.Instance.boot_disk:type_name -> kacho.cloud.compute.v1.AttachedDisk
	15, // 4: kacho.cloud.compute.v1.Instance.secondary_disks:type_name -> kacho.cloud.compute.v1.AttachedDisk
	16, // 5: kacho.cloud.compute.v1.Instance.network_interfaces:type_name -> kacho.cloud.compute.v1.NetworkInterface
	0,  // 6: kacho.cloud.compute.v1.Instance.instance_kind:type_name -> kacho.cloud.compute.v1.InstanceKind
	25, // 7: kacho.cloud.compute.v1.Instance.effective_resources:type_name -> kacho.cloud.compute.v1.EffectiveResources
	10, // 8: kacho.cloud.compute.v1.Instance.boot_source:type_name -> kacho.cloud.compute.v1.BootSource
	26, // 9: kacho.cloud.compute.v1.Instance.service_account:type_name -> kacho.cloud.reference.Referrer
	12, // 10: kacho.cloud.compute.v1.Instance.vm_spec:type_name -> kacho.cloud.compute.v1.VmSpec
	13, // 11: kacho.cloud.compute.v1.Instance.container_spec:type_name -> kacho.cloud.compute.v1.ContainerSpec
	11, // 12: kacho.cloud.compute.v1.BootSource.materialized_volume:type_name -> kacho.cloud.compute.v1.MaterializedVolume
	1,  // 13: kacho.cloud.compute.v1.BootSource.image_kind:type_name -> kacho.cloud.compute.v1.ImageKind
	20, // 14: kacho.cloud.compute.v1.VmSpec.metadata_options:type_name -> kacho.cloud.compute.v1.MetadataOptions
	23, // 15: kacho.cloud.compute.v1.ContainerSpec.env:type_name -> kacho.cloud.compute.v1.ContainerSpec.EnvEntry
	14, // 16: kacho.cloud.compute.v1.ContainerSpec.ports:type_name -> kacho.cloud.compute.v1.ContainerPort
	2,  // 17: kacho.cloud.compute.v1.ContainerSpec.restart_policy:type_name -> kacho.cloud.compute.v1.RestartPolicy
	6,  // 18: kacho.cloud.compute.v1.AttachedDisk.mode:type_name -> kacho.cloud.compute.v1.AttachedDisk.Mode
	17, // 19: kacho.cloud.compute.v1.NetworkInterface.primary_v4_address:type_name -> kacho.cloud.compute.v1.PrimaryAddress
	17, // 20: kacho.cloud.compute.v1.NetworkInterface.primary_v6_address:type_name -> kacho.cloud.compute.v1.PrimaryAddress
	18, // 21: kacho.cloud.compute.v1.PrimaryAddress.one_to_one_nat:type_name -> kacho.cloud.compute.v1.OneToOneNat
	3,  // 22: kacho.cloud.compute.v1.OneToOneNat.ip_version:type_name -> kacho.cloud.compute.v1.IpVersion
	7,  // 23: kacho.cloud.compute.v1.NetworkSettings.type:type_name -> kacho.cloud.compute.v1.NetworkSettings.Type
	4,  // 24: kacho.cloud.compute.v1.MetadataOptions.metadata_endpoint:type_name -> kacho.cloud.compute.v1.MetadataOption
	8,  // 25: kacho.cloud.compute.v1.SerialPortSettings.ssh_authorization:type_name -> kacho.cloud.compute.v1.SerialPortSettings.SSHAuthorization
	26, // [26:26] is the sub-list for method output_type
	26, // [26:26] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_kacho_cloud_compute_v1_instance_proto_init() }
func file_kacho_cloud_compute_v1_instance_proto_init() {
	if File_kacho_cloud_compute_v1_instance_proto != nil {
		return
	}
	file_kacho_cloud_compute_v1_machine_type_proto_init()
	file_kacho_cloud_compute_v1_instance_proto_msgTypes[0].OneofWrappers = []any{
		(*Instance_VmSpec)(nil),
		(*Instance_ContainerSpec)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kacho_cloud_compute_v1_instance_proto_rawDesc), len(file_kacho_cloud_compute_v1_instance_proto_rawDesc)),
			NumEnums:      9,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kacho_cloud_compute_v1_instance_proto_goTypes,
		DependencyIndexes: file_kacho_cloud_compute_v1_instance_proto_depIdxs,
		EnumInfos:         file_kacho_cloud_compute_v1_instance_proto_enumTypes,
		MessageInfos:      file_kacho_cloud_compute_v1_instance_proto_msgTypes,
	}.Build()
	File_kacho_cloud_compute_v1_instance_proto = out.File
	file_kacho_cloud_compute_v1_instance_proto_goTypes = nil
	file_kacho_cloud_compute_v1_instance_proto_depIdxs = nil
}
