// Copyright (c) PRO-Robotech
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: kacho/cloud/compute/v1/internal_realization_service.proto

package computev1

import (
	_ "github.com/PRO-Robotech/kacho/pkg/api/kacho/iam/authz/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ObservedState — то, что узел ВИДИТ, а не то, что мы просили.
//
// Набор закрыт и совпадает с ограничением схемы поэлементно: значение, которое
// код умеет прислать, а база не умеет принять, даёт отказ хранилища без имени
// поля — сигнал, по которому нельзя понять, что именно не так.
type ObservedState int32

const (
	ObservedState_OBSERVED_STATE_UNSPECIFIED ObservedState = 0
	// Узел взял машину в работу: ресурсы выделены, запуск идёт.
	ObservedState_OBSERVED_STARTING ObservedState = 1
	// Машина исполняется.
	ObservedState_OBSERVED_RUNNING ObservedState = 2
	// Идёт остановка, инициированная нами либо гостем.
	ObservedState_OBSERVED_STOPPING ObservedState = 3
	// Машина остановлена и её ресурсы освобождены.
	ObservedState_OBSERVED_STOPPED ObservedState = 4
	// Машина завершилась НЕОЖИДАННО: не по нашей команде и не по штатному
	// выключению гостя. Отдельное значение от остановки, потому что решения по
	// ним разные — остановленную не перезапускают, эту, возможно, да.
	ObservedState_OBSERVED_TERMINATED_UNEXPECTEDLY ObservedState = 5
)

// Enum value maps for ObservedState.
var (
	ObservedState_name = map[int32]string{
		0: "OBSERVED_STATE_UNSPECIFIED",
		1: "OBSERVED_STARTING",
		2: "OBSERVED_RUNNING",
		3: "OBSERVED_STOPPING",
		4: "OBSERVED_STOPPED",
		5: "OBSERVED_TERMINATED_UNEXPECTEDLY",
	}
	ObservedState_value = map[string]int32{
		"OBSERVED_STATE_UNSPECIFIED":       0,
		"OBSERVED_STARTING":                1,
		"OBSERVED_RUNNING":                 2,
		"OBSERVED_STOPPING":                3,
		"OBSERVED_STOPPED":                 4,
		"OBSERVED_TERMINATED_UNEXPECTEDLY": 5,
	}
)

func (x ObservedState) Enum() *ObservedState {
	p := new(ObservedState)
	*p = x
	return p
}

func (x ObservedState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ObservedState) Descriptor() protoreflect.EnumDescriptor {
	return file_kacho_cloud_compute_v1_internal_realization_service_proto_enumTypes[0].Descriptor()
}

func (ObservedState) Type() protoreflect.EnumType {
	return &file_kacho_cloud_compute_v1_internal_realization_service_proto_enumTypes[0]
}

func (x ObservedState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ObservedState.Descriptor instead.
func (ObservedState) EnumDescriptor() ([]byte, []int) {
	return file_kacho_cloud_compute_v1_internal_realization_service_proto_rawDescGZIP(), []int{0}
}

// ReportInstanceRealizationRequest — один отчёт об одной машине.
type ReportInstanceRealizationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Машина, о которой отчёт. Область права берётся отсюда: агент получает
	// право писать о КОНКРЕТНОЙ машине, а не обо всех сразу.
	InstanceId string `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	// Что узел наблюдает.
	ObservedState ObservedState `protobuf:"varint,2,opt,name=observed_state,json=observedState,proto3,enum=kacho.cloud.compute.v1.ObservedState" json:"observed_state,omitempty"`
	// Номер события доставки, по которому агент получил намерение. Меньший
	// молча отбрасывается, неизвестный отвергается.
	DeliverySequenceNo int64 `protobuf:"varint,3,opt,name=delivery_sequence_no,json=deliverySequenceNo,proto3" json:"delivery_sequence_no,omitempty"`
	// Момент наблюдения ПО ЧАСАМ УЗЛА. Мы не подменяем его своим временем: узел
	// мог наблюдать факт заметно раньше, чем сумел о нём сообщить, и подмена
	// стёрла бы эту разницу — единственный след того, что связь была потеряна.
	ObservedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=observed_at,json=observedAt,proto3" json:"observed_at,omitempty"`
	// Человекочитаемая причина, если наблюдаемое требует пояснения (отказ
	// запуска, неожиданное завершение). Пустая строка законна.
	Reason        string `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportInstanceRealizationRequest) Reset() {
	*x = ReportInstanceRealizationRequest{}
	mi := &file_kacho_cloud_compute_v1_internal_realization_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportInstanceRealizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportInstanceRealizationRequest) ProtoMessage() {}

func (x *ReportInstanceRealizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kacho_cloud_compute_v1_internal_realization_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportInstanceRealizationRequest.ProtoReflect.Descriptor instead.
func (*ReportInstanceRealizationRequest) Descriptor() ([]byte, []int) {
	return file_kacho_cloud_compute_v1_internal_realization_service_proto_rawDescGZIP(), []int{0}
}

func (x *ReportInstanceRealizationRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *ReportInstanceRealizationRequest) GetObservedState() ObservedState {
	if x != nil {
		return x.ObservedState
	}
	return ObservedState_OBSERVED_STATE_UNSPECIFIED
}

func (x *ReportInstanceRealizationRequest) GetDeliverySequenceNo() int64 {
	if x != nil {
		return x.DeliverySequenceNo
	}
	return 0
}

func (x *ReportInstanceRealizationRequest) GetObservedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ObservedAt
	}
	return nil
}

func (x *ReportInstanceRealizationRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// ReportInstanceRealizationResponse — подтверждение приёма.
type ReportInstanceRealizationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Отчёт принят и применён. False означает «принят и отброшен как устаревший»
	// — это не отказ: агент не обязан знать, что его обогнал более свежий отчёт,
	// и повторять ему нечего.
	Applied bool `protobuf:"varint,1,opt,name=applied,proto3" json:"applied,omitempty"`
	// Номер события, к которому относится ДЕЙСТВУЮЩЕЕ наблюдаемое состояние
	// после обработки этого отчёта. Агент, увидев номер больше своего, узнаёт,
	// что отстал, не задавая второго вопроса.
	CurrentSequenceNo int64 `protobuf:"varint,2,opt,name=current_sequence_no,json=currentSequenceNo,proto3" json:"current_sequence_no,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ReportInstanceRealizationResponse) Reset() {
	*x = ReportInstanceRealizationResponse{}
	mi := &file_kacho_cloud_compute_v1_internal_realization_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportInstanceRealizationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportInstanceRealizationResponse) ProtoMessage() {}

func (x *ReportInstanceRealizationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kacho_cloud_compute_v1_internal_realization_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportInstanceRealizationResponse.ProtoReflect.Descriptor instead.
func (*ReportInstanceRealizationResponse) Descriptor() ([]byte, []int) {
	return file_kacho_cloud_compute_v1_internal_realization_service_proto_rawDescGZIP(), []int{1}
}

func (x *ReportInstanceRealizationResponse) GetApplied() bool {
	if x != nil {
		return x.Applied
	}
	return false
}

func (x *ReportInstanceRealizationResponse) GetCurrentSequenceNo() int64 {
	if x != nil {
		return x.CurrentSequenceNo
	}
	return 0
}

var File_kacho_cloud_compute_v1_internal_realization_service_proto protoreflect.FileDescriptor

const file_kacho_cloud_compute_v1_internal_realization_service_proto_rawDesc = "" +
	"\n" +
	"9kacho/cloud/compute/v1/internal_realization_service.proto\x12\x16kacho.cloud.compute.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a&kacho/iam/authz/v1/authz_options.proto\"\x98\x02\n" +
	" ReportInstanceRealizationRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12L\n" +
	"\x0eobserved_state\x18\x02 \x01(\x0e2%.kacho.cloud.compute.v1.ObservedStateR\robservedState\x120\n" +
	"\x14delivery_sequence_no\x18\x03 \x01(\x03R\x12deliverySequenceNo\x12;\n" +
	"\vobserved_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"observedAt\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\"m\n" +
	"!ReportInstanceRealizationResponse\x12\x18\n" +
	"\aapplied\x18\x01 \x01(\bR\aapplied\x12.\n" +
	"\x13current_sequence_no\x18\x02 \x01(\x03R\x11currentSequenceNo*\xaf\x01\n" +
	"\rObservedState\x12\x1e\n" +
	"\x1aOBSERVED_STATE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11OBSERVED_STARTING\x10\x01\x12\x14\n" +
	"\x10OBSERVED_RUNNING\x10\x02\x12\x15\n" +
	"\x11OBSERVED_STOPPING\x10\x03\x12\x14\n" +
	"\x10OBSERVED_STOPPED\x10\x04\x12$\n" +
	" OBSERVED_TERMINATED_UNEXPECTEDLY\x10\x052\x96\x02\n" +
	"\x1aInternalRealizationService\x12\xf7\x01\n" +
	"\x19ReportInstanceRealization\x128.kacho.cloud.compute.v1.ReportInstanceRealizationRequest\x1a9.kacho.cloud.compute.v1.ReportInstanceRealizationResponse\"e\x8a\xb5\x18#compute.instances.reportRealization\x92\xb5\x18\x12realization_writer\x9a\xb5\x18\x1f\n" +
	"\x10compute_instance\x12\vinstance_id\xa2\xb5\x18\x011BHZFgithub.com/PRO-Robotech/kacho/pkg/api/kacho/cloud/compute/v1;computev1b\x06proto3"

var (
	file_kacho_cloud_compute_v1_internal_realization_service_proto_rawDescOnce sync.Once
	file_kacho_cloud_compute_v1_internal_realization_service_proto_rawDescData []byte
)

func file_kacho_cloud_compute_v1_internal_realization_service_proto_rawDescGZIP() []byte {
	file_kacho_cloud_compute_v1_internal_realization_service_proto_rawDescOnce.Do(func() {
		file_kacho_cloud_compute_v1_internal_realization_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kacho_cloud_compute_v1_internal_realization_service_proto_rawDesc), len(file_kacho_cloud_compute_v1_internal_realization_service_proto_rawDesc)))
	})
	return file_kacho_cloud_compute_v1_internal_realization_service_proto_rawDescData
}

var file_kacho_cloud_compute_v1_internal_realization_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_kacho_cloud_compute_v1_internal_realization_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_kacho_cloud_compute_v1_internal_realization_service_proto_goTypes = []any{
	(ObservedState)(0),                        // 0: kacho.cloud.compute.v1.ObservedState
	(*ReportInstanceRealizationRequest)(nil),  // 1: kacho.cloud.compute.v1.ReportInstanceRealizationRequest
	(*ReportInstanceRealizationResponse)(nil), // 2: kacho.cloud.compute.v1.ReportInstanceRealizationResponse
	(*timestamppb.Timestamp)(nil),             // 3: google.protobuf.Timestamp
}
var file_kacho_cloud_compute_v1_internal_realization_service_proto_depIdxs = []int32{
	0, // 0: kacho.cloud.compute.v1.ReportInstanceRealizationRequest.observed_state:type_name -> kacho.cloud.compute.v1.ObservedState
	3, // 1: kacho.cloud.compute.v1.ReportInstanceRealizationRequest.observed_at:type_name -> google.protobuf.Timestamp
	1, // 2: kacho.cloud.compute.v1.InternalRealizationService.ReportInstanceRealization:input_type -> kacho.cloud.compute.v1.ReportInstanceRealizationRequest
	2, // 3: kacho.cloud.compute.v1.InternalRealizationService.ReportInstanceRealization:output_type -> kacho.cloud.compute.v1.ReportInstanceRealizationResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_kacho_cloud_compute_v1_internal_realization_service_proto_init() }
func file_kacho_cloud_compute_v1_internal_realization_service_proto_init() {
	if File_kacho_cloud_compute_v1_internal_realization_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kacho_cloud_compute_v1_internal_realization_service_proto_rawDesc), len(file_kacho_cloud_compute_v1_internal_realization_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kacho_cloud_compute_v1_internal_realization_service_proto_goTypes,
		DependencyIndexes: file_kacho_cloud_compute_v1_internal_realization_service_proto_depIdxs,
		EnumInfos:         file_kacho_cloud_compute_v1_internal_realization_service_proto_enumTypes,
		MessageInfos:      file_kacho_cloud_compute_v1_internal_realization_service_proto_msgTypes,
	}.Build()
	File_kacho_cloud_compute_v1_internal_realization_service_proto = out.File
	file_kacho_cloud_compute_v1_internal_realization_service_proto_goTypes = nil
	file_kacho_cloud_compute_v1_internal_realization_service_proto_depIdxs = nil
}
