// Copyright (c) PRO-Robotech
// SPDX-License-Identifier: BUSL-1.1

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: kacho/cloud/compute/v1/machine_type.proto

package computev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Family — coarse machine-type class. Determines whether cpuGuaranteePercent
// applies (only STANDARD/COMPUTE/MEMORY) and whether GPUs are authoritative (GPU).
type MachineType_Family int32

const (
	MachineType_FAMILY_UNSPECIFIED MachineType_Family = 0
	// General-purpose balanced vCPU/memory.
	MachineType_STANDARD MachineType_Family = 1
	// Compute-optimized (higher vCPU per memory).
	MachineType_COMPUTE MachineType_Family = 2
	// Memory-optimized (higher memory per vCPU).
	MachineType_MEMORY MachineType_Family = 3
	// GPU-accelerated; gpus/gpuType in effectiveResources are authoritative.
	MachineType_GPU MachineType_Family = 4
)

// Enum value maps for MachineType_Family.
var (
	MachineType_Family_name = map[int32]string{
		0: "FAMILY_UNSPECIFIED",
		1: "STANDARD",
		2: "COMPUTE",
		3: "MEMORY",
		4: "GPU",
	}
	MachineType_Family_value = map[string]int32{
		"FAMILY_UNSPECIFIED": 0,
		"STANDARD":           1,
		"COMPUTE":            2,
		"MEMORY":             3,
		"GPU":                4,
	}
)

func (x MachineType_Family) Enum() *MachineType_Family {
	p := new(MachineType_Family)
	*p = x
	return p
}

func (x MachineType_Family) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MachineType_Family) Descriptor() protoreflect.EnumDescriptor {
	return file_kacho_cloud_compute_v1_machine_type_proto_enumTypes[0].Descriptor()
}

func (MachineType_Family) Type() protoreflect.EnumType {
	return &file_kacho_cloud_compute_v1_machine_type_proto_enumTypes[0]
}

func (x MachineType_Family) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MachineType_Family.Descriptor instead.
func (MachineType_Family) EnumDescriptor() ([]byte, []int) {
	return file_kacho_cloud_compute_v1_machine_type_proto_rawDescGZIP(), []int{0, 0}
}

// Status — catalog availability. AVAILABLE launches; DEPRECATED launches on
// existing/new (compat) but is discouraged; RETIRED is rejected on Create.
type MachineType_Status int32

const (
	MachineType_STATUS_UNSPECIFIED MachineType_Status = 0
	// Bookable; can be used on Create.
	MachineType_AVAILABLE MachineType_Status = 1
	// Still usable but discouraged (compat window).
	MachineType_DEPRECATED MachineType_Status = 2
	// No longer bookable; rejected on Instance.Create.
	MachineType_RETIRED MachineType_Status = 3
)

// Enum value maps for MachineType_Status.
var (
	MachineType_Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "AVAILABLE",
		2: "DEPRECATED",
		3: "RETIRED",
	}
	MachineType_Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"AVAILABLE":          1,
		"DEPRECATED":         2,
		"RETIRED":            3,
	}
)

func (x MachineType_Status) Enum() *MachineType_Status {
	p := new(MachineType_Status)
	*p = x
	return p
}

func (x MachineType_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MachineType_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_kacho_cloud_compute_v1_machine_type_proto_enumTypes[1].Descriptor()
}

func (MachineType_Status) Type() protoreflect.EnumType {
	return &file_kacho_cloud_compute_v1_machine_type_proto_enumTypes[1]
}

func (x MachineType_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MachineType_Status.Descriptor instead.
func (MachineType_Status) EnumDescriptor() ([]byte, []int) {
	return file_kacho_cloud_compute_v1_machine_type_proto_rawDescGZIP(), []int{0, 1}
}

// MachineType — sync catalog resource: the single channel for Instance sizing
// (COMP-1 F2/F7). Flat resource; a tenant picks a size via MachineTypeService.List
// before launch. GPU count is expressed by catalog granularity (gpu-a100-1/-2/-4/
// -8), NOT by a request field. The catalog is admin-managed: public Get/List
// (ambient, cluster-scoped read) live on MachineTypeService; admin CRUD lives on
// InternalMachineTypeService (:9091, system_admin) — never on the external mux
// (ban #6). effectiveResources / availableZones are output-only (server-derived).
type MachineType struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the machine type (canonical "mt-<base32>"). Server-assigned, immutable PK.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Stable human-readable name (e.g. "std-v3-2"). Unique within the catalog and
	// accepted as an alternate reference on Instance.machineTypeId (canonical echo
	// is always the mt- slug).
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Free-form description.
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Coarse machine-type class.
	Family MachineType_Family `protobuf:"varint,4,opt,name=family,proto3,enum=kacho.cloud.compute.v1.MachineType_Family" json:"family,omitempty"`
	// Output-only authoritative size mirror (server-derived from the catalog entry).
	EffectiveResources *EffectiveResources `protobuf:"bytes,5,opt,name=effective_resources,json=effectiveResources,proto3" json:"effective_resources,omitempty"`
	// Output-only capacity hint: zones where this machine type is bookable.
	AvailableZones []string `protobuf:"bytes,6,rep,name=available_zones,json=availableZones,proto3" json:"available_zones,omitempty"`
	// Catalog availability.
	Status MachineType_Status `protobuf:"varint,7,opt,name=status,proto3,enum=kacho.cloud.compute.v1.MachineType_Status" json:"status,omitempty"`
	// Labels (key/value).
	Labels map[string]string `protobuf:"bytes,8,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Creation timestamp (truncated to seconds on the wire).
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MachineType) Reset() {
	*x = MachineType{}
	mi := &file_kacho_cloud_compute_v1_machine_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineType) ProtoMessage() {}

func (x *MachineType) ProtoReflect() protoreflect.Message {
	mi := &file_kacho_cloud_compute_v1_machine_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineType.ProtoReflect.Descriptor instead.
func (*MachineType) Descriptor() ([]byte, []int) {
	return file_kacho_cloud_compute_v1_machine_type_proto_rawDescGZIP(), []int{0}
}

func (x *MachineType) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MachineType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MachineType) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MachineType) GetFamily() MachineType_Family {
	if x != nil {
		return x.Family
	}
	return MachineType_FAMILY_UNSPECIFIED
}

func (x *MachineType) GetEffectiveResources() *EffectiveResources {
	if x != nil {
		return x.EffectiveResources
	}
	return nil
}

func (x *MachineType) GetAvailableZones() []string {
	if x != nil {
		return x.AvailableZones
	}
	return nil
}

func (x *MachineType) GetStatus() MachineType_Status {
	if x != nil {
		return x.Status
	}
	return MachineType_STATUS_UNSPECIFIED
}

func (x *MachineType) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *MachineType) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// EffectiveResources — output-only authoritative size derived from the catalog
// entry. Memory is expressed in MiB (not bytes). Mirrored onto Instance.
type EffectiveResources struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Number of vCPUs.
	VCpu int32 `protobuf:"varint,1,opt,name=v_cpu,json=vCpu,proto3" json:"v_cpu,omitempty"`
	// Memory in MiB (mebibytes), NOT bytes.
	MemoryMib int64 `protobuf:"varint,2,opt,name=memory_mib,json=memoryMib,proto3" json:"memory_mib,omitempty"`
	// Number of GPUs (0 unless family=GPU).
	Gpus int32 `protobuf:"varint,3,opt,name=gpus,proto3" json:"gpus,omitempty"`
	// GPU silicon model (empty unless family=GPU), e.g. "a100-80g".
	GpuType       string `protobuf:"bytes,4,opt,name=gpu_type,json=gpuType,proto3" json:"gpu_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EffectiveResources) Reset() {
	*x = EffectiveResources{}
	mi := &file_kacho_cloud_compute_v1_machine_type_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EffectiveResources) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EffectiveResources) ProtoMessage() {}

func (x *EffectiveResources) ProtoReflect() protoreflect.Message {
	mi := &file_kacho_cloud_compute_v1_machine_type_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EffectiveResources.ProtoReflect.Descriptor instead.
func (*EffectiveResources) Descriptor() ([]byte, []int) {
	return file_kacho_cloud_compute_v1_machine_type_proto_rawDescGZIP(), []int{1}
}

func (x *EffectiveResources) GetVCpu() int32 {
	if x != nil {
		return x.VCpu
	}
	return 0
}

func (x *EffectiveResources) GetMemoryMib() int64 {
	if x != nil {
		return x.MemoryMib
	}
	return 0
}

func (x *EffectiveResources) GetGpus() int32 {
	if x != nil {
		return x.Gpus
	}
	return 0
}

func (x *EffectiveResources) GetGpuType() string {
	if x != nil {
		return x.GpuType
	}
	return ""
}

var File_kacho_cloud_compute_v1_machine_type_proto protoreflect.FileDescriptor

const file_kacho_cloud_compute_v1_machine_type_proto_rawDesc = "" +
	"\n" +
	")kacho/cloud/compute/v1/machine_type.proto\x12\x16kacho.cloud.compute.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc0\x05\n" +
	"\vMachineType\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12B\n" +
	"\x06family\x18\x04 \x01(\x0e2*.kacho.cloud.compute.v1.MachineType.FamilyR\x06family\x12[\n" +
	"\x13effective_resources\x18\x05 \x01(\v2*.kacho.cloud.compute.v1.EffectiveResourcesR\x12effectiveResources\x12'\n" +
	"\x0favailable_zones\x18\x06 \x03(\tR\x0eavailableZones\x12B\n" +
	"\x06status\x18\a \x01(\x0e2*.kacho.cloud.compute.v1.MachineType.StatusR\x06status\x12G\n" +
	"\x06labels\x18\b \x03(\v2/.kacho.cloud.compute.v1.MachineType.LabelsEntryR\x06labels\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"P\n" +
	"\x06Family\x12\x16\n" +
	"\x12FAMILY_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bSTANDARD\x10\x01\x12\v\n" +
	"\aCOMPUTE\x10\x02\x12\n" +
	"\n" +
	"\x06MEMORY\x10\x03\x12\a\n" +
	"\x03GPU\x10\x04\"L\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tAVAILABLE\x10\x01\x12\x0e\n" +
	"\n" +
	"DEPRECATED\x10\x02\x12\v\n" +
	"\aRETIRED\x10\x03\"w\n" +
	"\x12EffectiveResources\x12\x13\n" +
	"\x05v_cpu\x18\x01 \x01(\x05R\x04vCpu\x12\x1d\n" +
	"\n" +
	"memory_mib\x18\x02 \x01(\x03R\tmemoryMib\x12\x12\n" +
	"\x04gpus\x18\x03 \x01(\x05R\x04gpus\x12\x19\n" +
	"\bgpu_type\x18\x04 \x01(\tR\agpuTypeBHZFgithub.com/PRO-Robotech/kacho/pkg/api/kacho/cloud/compute/v1;computev1b\x06proto3"

var (
	file_kacho_cloud_compute_v1_machine_type_proto_rawDescOnce sync.Once
	file_kacho_cloud_compute_v1_machine_type_proto_rawDescData []byte
)

func file_kacho_cloud_compute_v1_machine_type_proto_rawDescGZIP() []byte {
	file_kacho_cloud_compute_v1_machine_type_proto_rawDescOnce.Do(func() {
		file_kacho_cloud_compute_v1_machine_type_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kacho_cloud_compute_v1_machine_type_proto_rawDesc), len(file_kacho_cloud_compute_v1_machine_type_proto_rawDesc)))
	})
	return file_kacho_cloud_compute_v1_machine_type_proto_rawDescData
}

var file_kacho_cloud_compute_v1_machine_type_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_kacho_cloud_compute_v1_machine_type_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_kacho_cloud_compute_v1_machine_type_proto_goTypes = []any{
	(MachineType_Family)(0),       // 0: kacho.cloud.compute.v1.MachineType.Family
	(MachineType_Status)(0),       // 1: kacho.cloud.compute.v1.MachineType.Status
	(*MachineType)(nil),           // 2: kacho.cloud.compute.v1.MachineType
	(*EffectiveResources)(nil),    // 3: kacho.cloud.compute.v1.EffectiveResources
	nil,                           // 4: kacho.cloud.compute.v1.MachineType.LabelsEntry
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_kacho_cloud_compute_v1_machine_type_proto_depIdxs = []int32{
	0, // 0: kacho.cloud.compute.v1.MachineType.family:type_name -> kacho.cloud.compute.v1.MachineType.Family
	3, // 1: kacho.cloud.compute.v1.MachineType.effective_resources:type_name -> kacho.cloud.compute.v1.EffectiveResources
	1, // 2: kacho.cloud.compute.v1.MachineType.status:type_name -> kacho.cloud.compute.v1.MachineType.Status
	4, // 3: kacho.cloud.compute.v1.MachineType.labels:type_name -> kacho.cloud.compute.v1.MachineType.LabelsEntry
	5, // 4: kacho.cloud.compute.v1.MachineType.created_at:type_name -> google.protobuf.Timestamp
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_kacho_cloud_compute_v1_machine_type_proto_init() }
func file_kacho_cloud_compute_v1_machine_type_proto_init() {
	if File_kacho_cloud_compute_v1_machine_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kacho_cloud_compute_v1_machine_type_proto_rawDesc), len(file_kacho_cloud_compute_v1_machine_type_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kacho_cloud_compute_v1_machine_type_proto_goTypes,
		DependencyIndexes: file_kacho_cloud_compute_v1_machine_type_proto_depIdxs,
		EnumInfos:         file_kacho_cloud_compute_v1_machine_type_proto_enumTypes,
		MessageInfos:      file_kacho_cloud_compute_v1_machine_type_proto_msgTypes,
	}.Build()
	File_kacho_cloud_compute_v1_machine_type_proto = out.File
	file_kacho_cloud_compute_v1_machine_type_proto_goTypes = nil
	file_kacho_cloud_compute_v1_machine_type_proto_depIdxs = nil
}
