// Copyright (c) PRO-Robotech
// SPDX-License-Identifier: BUSL-1.1

package repohygiene

import (
	"fmt"
	"regexp"
	"sort"
	"strings"

	"github.com/PRO-Robotech/kacho/pkg/treecorpus"
)

// Страница сайта достижима из меню, а пункт меню ведёт на существующую страницу.
//
// ПРЕДМЕТ. Страница, которой нет в боковом меню, для клиента не существует:
// сборка сайта на неё не жалуется, адрес у неё есть, но прийти по нему можно
// только зная его заранее — то есть от нас. Ровно этим обесценивается работа,
// только что закрывшая молчание про отказ по исчерпанию предела: страница
// пределов, не подключённая к меню, отвечает на вопрос, которого клиент не
// сможет задать. Обратная сторона того же предмета: пункт меню без страницы —
// это `404` по ссылке, которую продукт показал сам.
//
// ПОЧЕМУ ГЕЙТ, А НЕ ВНИМАНИЕ. Заведение страницы и её подключение к меню — две
// правки в РАЗНЫХ файлах, и вторая не нужна ни для сборки, ни для проб: сайт
// собирается с потерянной страницей молча. Коммит, заводящий сразу шесть
// страниц (по одной на домен), обязан внести шесть записей в шесть меню, и
// пропуск любой из них выглядит как выполненная работа.
//
// ЧТО СЧИТАЕТСЯ ССЫЛКОЙ НА СТРАНИЦУ. Меню Docusaurus — объявление на TypeScript,
// в котором строки означают разное: `'api/network'` в массиве — идентификатор
// страницы, `label: 'Архитектура'` — подпись раздела, `type: 'category'` —
// вид узла. Различает их не форма строки, а ЧТО СТОИТ ПЕРЕД НЕЙ: открывающая
// скобка или запятая — ссылка на страницу; двоеточие — значение свойства, и
// ссылкой оно является ровно для одного ключа (`id` у узла вида `doc`).
// Предикат «всякая строка в кавычках — идентификатор» дал бы находку на каждой
// подписи раздела, и гейт сняли бы первым.
//
// ЧЕМ ЭТОТ ГЕЙТ НЕ ЯВЛЯЕТСЯ. Он не судит ПОРЯДОК пунктов и их вложенность —
// это решение автора сайта. Он не разбирает автособираемое меню
// (`type: 'autogenerated'`): состав такого меню знает генератор, а не дерево, —
// сайт с ним из проверки достижимости выводится, и перепись это НАЗЫВАЕТ, чтобы
// «ноль находок» не читалось шире, чем есть. Он не проверяет, что страница
// упомянута где-то ещё в тексте: меню и проза — разные обещания.

var (
	// Строка в кавычках. Две ветви, а не обратная ссылка на открывающую кавычку:
	// RE2 обратных ссылок не имеет by construction, и попытка их применить роняет
	// ВЕСЬ пакет проверок при инициализации, а не одну эту.
	docsReachQuotedRe = regexp.MustCompile(`'[^'\n]*'|"[^"\n]*"`)

	// Автособираемое меню: состав знает генератор, дерево его не судит.
	docsReachAutogenRe = regexp.MustCompile(`['"]autogenerated['"]`)

	// Расширения страниц сайта.
	docsReachPageSuffixes = []string{".mdx", ".md"}
)

// docsReachSite — один сайт документации.
type docsReachSite struct {
	Base       string // services/<домен>/docs либо gateway/docs
	HasSidebar bool
	Autogen    bool     // меню собирается генератором — достижимость не судится
	Pages      []string // идентификаторы страниц (путь под content без расширения)
	MenuRefs   []string // идентификаторы, названные меню
}

// docsReachCensus — объём осмотренного.
type docsReachCensus struct {
	Sites       []docsReachSite
	Judged      int // сайтов, чью достижимость гейт судит
	AutogenSkip int // сайтов с автособираемым меню
	Pages       int
	MenuRefs    int
}

// collectDocsPageReach — какие страницы есть и на какие ссылается меню.
//
// Состав дерева приходит СОСТАВЛЕННЫМ (`treecorpus.Tree`): гейт берёт индекс
// git, инъекционная проба — синтетическое дерево.
func collectDocsPageReach(tree *treecorpus.Tree) (docsReachCensus, error) {
	var c docsReachCensus

	bases := map[string]bool{}
	for rel := range tree.Files() {
		switch {
		case strings.HasPrefix(rel, "services/"):
			seg := strings.Split(rel, "/")
			if len(seg) >= 3 && seg[2] == "docs" {
				bases[seg[0]+"/"+seg[1]+"/docs"] = true
			}
		case strings.HasPrefix(rel, "gateway/docs/"):
			bases["gateway/docs"] = true
		}
	}
	names := make([]string, 0, len(bases))
	for b := range bases {
		names = append(names, b)
	}
	sort.Strings(names)

	for _, base := range names {
		site := docsReachSite{Base: base}
		contentDir := base + "/content"
		for _, rel := range clientTruthTreeFiles(tree, contentDir, true, docsReachPageSuffixes...) {
			id := strings.TrimPrefix(rel, contentDir+"/")
			for _, sfx := range docsReachPageSuffixes {
				id = strings.TrimSuffix(id, sfx)
			}
			site.Pages = append(site.Pages, id)
		}

		sidebarRel := base + "/sidebars.ts"
		if tree.HasFile(sidebarRel) {
			site.HasSidebar = true
			body, err := clientTruthReadTreeFile(tree, sidebarRel)
			if err != nil {
				return c, err
			}
			site.Autogen = docsReachAutogenRe.Match(body)
			site.MenuRefs = docsReachMenuRefs(string(body))
		}

		c.Pages += len(site.Pages)
		c.MenuRefs += len(site.MenuRefs)
		switch {
		case site.Autogen:
			c.AutogenSkip++
		case site.HasSidebar:
			c.Judged++
		}
		c.Sites = append(c.Sites, site)
	}
	return c, nil
}

// docsReachMenuRefs — идентификаторы страниц, названные объявлением меню.
//
// Различает не форма строки, а КОНТЕКСТ: перед ссылкой на страницу стоит
// открывающая скобка или запятая; перед значением свойства — двоеточие, и
// ссылкой такое значение является ровно для ключа `id`. Без этого различения
// подпись раздела `label: 'Архитектура'` читалась бы как идентификатор страницы,
// и каждая подпись давала бы находку.
func docsReachMenuRefs(body string) []string {
	seen := map[string]bool{}
	var out []string
	for _, m := range docsReachQuotedRe.FindAllStringIndex(body, -1) {
		j := m[0] - 1
		for j >= 0 && (body[j] == ' ' || body[j] == '\t' || body[j] == '\n' || body[j] == '\r') {
			j--
		}
		if j < 0 {
			continue
		}
		switch body[j] {
		case '[', ',':
			// Элемент массива — идентификатор страницы.
		case ':':
			k := j - 1
			for k >= 0 && (body[k] == ' ' || body[k] == '\t' || body[k] == '\n' || body[k] == '\r') {
				k--
			}
			end := k
			for k >= 0 && (body[k] == '_' || body[k] >= 'a' && body[k] <= 'z' ||
				body[k] >= 'A' && body[k] <= 'Z' || body[k] >= '0' && body[k] <= '9') {
				k--
			}
			if body[k+1:end+1] != "id" {
				continue
			}
		default:
			continue
		}
		v := body[m[0]+1 : m[1]-1] // без обрамляющих кавычек
		if v == "" || seen[v] {
			continue
		}
		seen[v] = true
		out = append(out, v)
	}
	sort.Strings(out)
	return out
}

// docsPageReachFindings — что не сходится.
func docsPageReachFindings(c docsReachCensus) []string {
	var out []string
	for _, s := range c.Sites {
		if len(s.Pages) == 0 {
			continue // каталога страниц у сайта нет — предмета достижимости тоже
		}
		if !s.HasSidebar {
			out = append(out, fmt.Sprintf(
				"%s: страниц %d, а объявления меню (sidebars.ts) нет — прийти на них "+
					"клиент может только зная адрес заранее",
				s.Base, len(s.Pages)))
			continue
		}
		if s.Autogen {
			continue // состав такого меню знает генератор; названо в переписи
		}
		inMenu := map[string]bool{}
		for _, r := range s.MenuRefs {
			inMenu[r] = true
		}
		hasPage := map[string]bool{}
		for _, p := range s.Pages {
			hasPage[p] = true
		}
		for _, p := range s.Pages {
			if !inMenu[p] {
				out = append(out, fmt.Sprintf(
					"%s/content/%s: страница есть, а в меню (%s/sidebars.ts) её нет — "+
						"для клиента она не существует",
					s.Base, p, s.Base))
			}
		}
		for _, r := range s.MenuRefs {
			if !hasPage[r] {
				out = append(out, fmt.Sprintf(
					"%s/sidebars.ts: пункт меню %q ведёт на страницу, которой в дереве нет — "+
						"клиент получит 404 по ссылке, которую показал сам продукт",
					s.Base, r))
			}
		}
	}
	sort.Strings(out)
	return out
}
