// Copyright (c) PRO-Robotech
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: kacho/cloud/quota/v1/quota.proto

package quotav1

import (
	v1 "github.com/PRO-Robotech/kacho/pkg/api/kacho/cloud/iam/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Quota — one ceiling as the tenant sees it: the limit, what is already spent
// against it, and WHERE the limit came from.
//
// WHY THIS MESSAGE IS SHARED AND THE SERVICE IS NOT. The value lives in iam and
// the counting lives with the owner of the resource type (`iam.v1.Limit`). A
// single summary endpoint at iam would need `iam -> owner` calls to learn what is
// spent, and iam is a leaf domain every service already calls — that edge would
// close a cycle. So each owner answers about ITS OWN kinds, from its own database,
// and the SHAPE of the answer is stated once, here, so eight domains cannot drift
// into eight dialects of the same three numbers.
//
// WHY `source_scope` IS IMPORTED AND NOT RESTATED. A tenant who hits a ceiling
// needs to know whose ceiling it is before they know who can raise it. That is
// exactly what `iam.v1.Limit.Scope` already says, and a second enumeration about
// one subject drifts silently — one side gains an arm, the other keeps compiling.
// All contracts live in one tree under one `buf`, so the import costs nothing by
// construction.
//
// READ-ONLY BY CONSTRUCTION. This message never appears in a request body. The
// tenant reads; only the cloud administrator changes a value, through
// `iam.v1.InternalLimitService` on the internal listener. The split is a
// permission boundary, not a convenience: a tenant able to raise their own
// ceiling has no ceiling.
type Quota struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The kind this row governs — a dotted `domain.resource` token from the
	// platform's closed catalogue (`vpc.network`, `vpc.subnet`, …). The same token
	// the administrator states a `Limit` on, so the two are joinable without a
	// translation table.
	Kind string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	// The effective ceiling: how many of this kind the carrier may hold. Zero is a
	// legal, meaningful value — "none of this kind may be created" — and is NOT to
	// be read as "unset".
	Limit int64 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	// How many are held right now. Counted by the owner in the very statement that
	// inserts or deletes the row, so it cannot drift from the rows it counts.
	Used int64 `protobuf:"varint,3,opt,name=used,proto3" json:"used,omitempty"`
	// Scope the winning value was stated at — PROJECT beats ACCOUNT beats DEFAULT.
	//
	// Without it "you are at 16 of 16" does not tell the tenant whether the number
	// is their own override, their account's, or the platform's, and therefore does
	// not tell them who can change it.
	SourceScope v1.Limit_Scope `protobuf:"varint,4,opt,name=source_scope,json=sourceScope,proto3,enum=kacho.cloud.iam.v1.Limit_Scope" json:"source_scope,omitempty"`
	// Id of the object the winning scope names: an account id for ACCOUNT, a
	// project id for PROJECT. Empty when the winner is DEFAULT, and empty ONLY
	// then — the pairing mirrors `iam.v1.Limit`, where a DB CHECK enforces it.
	SourceScopeId string `protobuf:"bytes,5,opt,name=source_scope_id,json=sourceScopeId,proto3" json:"source_scope_id,omitempty"`
	// What the count is kept against. Today `project` for every kind of every
	// domain; a kind whose ceiling belongs to a PARENT resource rather than to the
	// project (children of one object) carries that parent's type here.
	//
	// Stated rather than assumed, because "quota is per project" is true of the
	// present catalogue and not of the mechanism: reading it off the request would
	// make the response describe the question instead of the resource.
	CarrierType string `protobuf:"bytes,6,opt,name=carrier_type,json=carrierType,proto3" json:"carrier_type,omitempty"`
	// Id of the carrier — the project id when `carrier_type` is `project`.
	CarrierId     string `protobuf:"bytes,7,opt,name=carrier_id,json=carrierId,proto3" json:"carrier_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Quota) Reset() {
	*x = Quota{}
	mi := &file_kacho_cloud_quota_v1_quota_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Quota) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Quota) ProtoMessage() {}

func (x *Quota) ProtoReflect() protoreflect.Message {
	mi := &file_kacho_cloud_quota_v1_quota_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Quota.ProtoReflect.Descriptor instead.
func (*Quota) Descriptor() ([]byte, []int) {
	return file_kacho_cloud_quota_v1_quota_proto_rawDescGZIP(), []int{0}
}

func (x *Quota) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Quota) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *Quota) GetUsed() int64 {
	if x != nil {
		return x.Used
	}
	return 0
}

func (x *Quota) GetSourceScope() v1.Limit_Scope {
	if x != nil {
		return x.SourceScope
	}
	return v1.Limit_Scope(0)
}

func (x *Quota) GetSourceScopeId() string {
	if x != nil {
		return x.SourceScopeId
	}
	return ""
}

func (x *Quota) GetCarrierType() string {
	if x != nil {
		return x.CarrierType
	}
	return ""
}

func (x *Quota) GetCarrierId() string {
	if x != nil {
		return x.CarrierId
	}
	return ""
}

var File_kacho_cloud_quota_v1_quota_proto protoreflect.FileDescriptor

const file_kacho_cloud_quota_v1_quota_proto_rawDesc = "" +
	"\n" +
	" kacho/cloud/quota/v1/quota.proto\x12\x14kacho.cloud.quota.v1\x1a\x1ekacho/cloud/iam/v1/limit.proto\"\xf3\x01\n" +
	"\x05Quota\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x03R\x05limit\x12\x12\n" +
	"\x04used\x18\x03 \x01(\x03R\x04used\x12B\n" +
	"\fsource_scope\x18\x04 \x01(\x0e2\x1f.kacho.cloud.iam.v1.Limit.ScopeR\vsourceScope\x12&\n" +
	"\x0fsource_scope_id\x18\x05 \x01(\tR\rsourceScopeId\x12!\n" +
	"\fcarrier_type\x18\x06 \x01(\tR\vcarrierType\x12\x1d\n" +
	"\n" +
	"carrier_id\x18\a \x01(\tR\tcarrierIdBDZBgithub.com/PRO-Robotech/kacho/pkg/api/kacho/cloud/quota/v1;quotav1b\x06proto3"

var (
	file_kacho_cloud_quota_v1_quota_proto_rawDescOnce sync.Once
	file_kacho_cloud_quota_v1_quota_proto_rawDescData []byte
)

func file_kacho_cloud_quota_v1_quota_proto_rawDescGZIP() []byte {
	file_kacho_cloud_quota_v1_quota_proto_rawDescOnce.Do(func() {
		file_kacho_cloud_quota_v1_quota_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kacho_cloud_quota_v1_quota_proto_rawDesc), len(file_kacho_cloud_quota_v1_quota_proto_rawDesc)))
	})
	return file_kacho_cloud_quota_v1_quota_proto_rawDescData
}

var file_kacho_cloud_quota_v1_quota_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_kacho_cloud_quota_v1_quota_proto_goTypes = []any{
	(*Quota)(nil),       // 0: kacho.cloud.quota.v1.Quota
	(v1.Limit_Scope)(0), // 1: kacho.cloud.iam.v1.Limit.Scope
}
var file_kacho_cloud_quota_v1_quota_proto_depIdxs = []int32{
	1, // 0: kacho.cloud.quota.v1.Quota.source_scope:type_name -> kacho.cloud.iam.v1.Limit.Scope
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_kacho_cloud_quota_v1_quota_proto_init() }
func file_kacho_cloud_quota_v1_quota_proto_init() {
	if File_kacho_cloud_quota_v1_quota_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kacho_cloud_quota_v1_quota_proto_rawDesc), len(file_kacho_cloud_quota_v1_quota_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kacho_cloud_quota_v1_quota_proto_goTypes,
		DependencyIndexes: file_kacho_cloud_quota_v1_quota_proto_depIdxs,
		MessageInfos:      file_kacho_cloud_quota_v1_quota_proto_msgTypes,
	}.Build()
	File_kacho_cloud_quota_v1_quota_proto = out.File
	file_kacho_cloud_quota_v1_quota_proto_goTypes = nil
	file_kacho_cloud_quota_v1_quota_proto_depIdxs = nil
}
