// Code generated by notifygen. DO NOT EDIT.
// Шаблон resource-event, ревизия 1.

package storage

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5"

	"github.com/PRO-Robotech/corelib/notify/feed"
	"github.com/PRO-Robotech/corelib/notify/form"
)

// ResourceEventAttrs — атрибуты шаблона resource-event. Нулевое поле optional — «не задан».
type ResourceEventAttrs struct {
	Change     string
	Kind       string
	Name       string
	OccurredAt time.Time
	ResourceId string
	Scope      string
}

var resourceEventDesc = feed.TemplateDesc{
	Name:      "resource-event",
	Class:     feed.ClassNotice,
	SchemaRev: 1,
	TTL:       259200 * time.Second,
	Recipient: feed.RecipientFanout,
	Limits:    []feed.Limit{},
	Attrs: []feed.AttrDesc{
		{Name: "change", Kind: form.KindText, Presence: feed.PresenceRequired, Subject: true},
		{Name: "kind", Kind: form.KindText, Presence: feed.PresenceRequired, Subject: true},
		{Name: "name", Kind: form.KindText, Presence: feed.PresenceOptional, Subject: false},
		{Name: "occurred_at", Kind: form.KindTimestamp, Presence: feed.PresenceRequired, Subject: false},
		{Name: "resource_id", Kind: form.KindText, Presence: feed.PresenceRequired, Subject: true},
		{Name: "scope", Kind: form.KindText, Presence: feed.PresenceRequired, Subject: false},
	},
}

// SendResourceEvent ставит письмо шаблона resource-event в транзакции tx (feed.PutID) и отвечает
// id записанной строки ленты; флаг выключен у notice — строки и id нет.
func SendResourceEvent(ctx context.Context, tx pgx.Tx, a ResourceEventAttrs) (feed.Queued, error) {
	values := feed.Values{Attrs: make(map[string]any, 6)}
	values.Attrs["change"] = a.Change
	values.Attrs["kind"] = a.Kind
	if _, present, err := form.Presence(form.KindText, a.Name); err != nil || present == form.Given {
		values.Attrs["name"] = a.Name
	}
	values.Attrs["occurred_at"] = a.OccurredAt
	values.Attrs["resource_id"] = a.ResourceId
	values.Attrs["scope"] = a.Scope
	return feed.PutID(ctx, tx, resourceEventDesc, "", values)
}
