-- Copyright (c) PRO-Robotech
-- SPDX-License-Identifier: BUSL-1.1

-- 0006: transactional-outbox для регистрации owner-tuple storage-ресурсов в FGA
-- (SEC-D). Намерение «register/unregister owner-tuple» пишется строкой в ТОЙ ЖЕ
-- writer-TX, что вставляет/удаляет Volume/Snapshot (один commit, без dual-write).
-- Отдельный register-drainer (corelib outbox/drainer) применяет каждое намерение
-- через kacho-iam InternalIAMService.RegisterResource/UnregisterResource по mTLS.
--
-- ОТДЕЛЬНАЯ таблица — независимая от доменного storage_outbox (0005, Watch/domain
-- события с колонками sequence_no/processed_at) — изолирует FGA-relay drainer от
-- доменного консюмера И несёт схему, ТОЧНО совпадающую с claim/mark SQL
-- corelib-drainer'а:
--   id (bigint IDENTITY PK), event_type, payload (jsonb), created_at, sent_at,
--   last_error, attempt_count
-- (drainer.claimRows: RETURNING id, event_type, payload, attempt_count;
--  markSuccess: SET sent_at=now(); markFailure/Poison: SET last_error, attempt_count).
-- Доменный storage_outbox драйнеру НЕ подходит (PK sequence_no, processed_at, нет
-- attempt_count/last_error) — потому здесь заведена совместимая таблица.
--
-- Одна строка == один tuple: drainer забирает/применяет строки независимо, поэтому
-- poison/transient tuple не блокирует остальные. LISTEN/NOTIFY-канал
-- `kacho_storage_fga_register_outbox` (NEW.id) будит drainer на INSERT.
--
-- Within-service инвариант (DB-уровень): exactly-once claim обеспечивает атомарный
-- `UPDATE ... WHERE sent_at IS NULL AND attempt_count < $max ... FOR UPDATE SKIP
-- LOCKED RETURNING ...` corelib-drainer'а — без software TOCTOU. Домен event_type
-- гарантируется CHECK. resource_kind/resource_id — трассировочные (drainer не читает).

-- +goose Up
CREATE TABLE kacho_storage.fga_register_outbox (
    id            bigint                   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type    text                     NOT NULL,
    payload       jsonb                    NOT NULL,
    created_at    timestamp with time zone NOT NULL DEFAULT now(),
    sent_at       timestamp with time zone,
    last_error    text,
    attempt_count integer                  NOT NULL DEFAULT 0,
    resource_kind text                     NOT NULL DEFAULT '',
    resource_id   text                     NOT NULL DEFAULT '',
    CONSTRAINT fga_register_outbox_event_type_check
        CHECK (event_type IN ('fga.register', 'fga.unregister'))
);

-- Pending-rows partial index — drainer claim сканирует (sent_at IS NULL).
CREATE INDEX fga_register_outbox_pending_idx
    ON kacho_storage.fga_register_outbox (id)
    WHERE sent_at IS NULL;

-- LISTEN/NOTIFY wake-up: pg_notify на каждый INSERT (payload = NEW.id::text),
-- совпадает с corelib drainer Config.Channel = "kacho_storage_fga_register_outbox".
-- +goose StatementBegin
CREATE OR REPLACE FUNCTION kacho_storage.fga_register_outbox_notify() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    PERFORM pg_notify('kacho_storage_fga_register_outbox', NEW.id::text);
    RETURN NEW;
END;
$$;
-- +goose StatementEnd

CREATE TRIGGER fga_register_outbox_notify_trg
    AFTER INSERT ON kacho_storage.fga_register_outbox
    FOR EACH ROW EXECUTE FUNCTION kacho_storage.fga_register_outbox_notify();

-- +goose Down
DROP TRIGGER IF EXISTS fga_register_outbox_notify_trg ON kacho_storage.fga_register_outbox;
DROP FUNCTION IF EXISTS kacho_storage.fga_register_outbox_notify();
DROP INDEX IF EXISTS kacho_storage.fga_register_outbox_pending_idx;
DROP TABLE IF EXISTS kacho_storage.fga_register_outbox;
