// Copyright (c) PRO-Robotech
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: kacho/cloud/vpc/v1/address_pool_service.proto

package vpcv1

import (
	context "context"
	operation "github.com/PRO-Robotech/kacho/pkg/api/kacho/cloud/operation"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AddressPoolService_Get_FullMethodName                  = "/kacho.cloud.vpc.v1.AddressPoolService/Get"
	AddressPoolService_List_FullMethodName                 = "/kacho.cloud.vpc.v1.AddressPoolService/List"
	AddressPoolService_ListAddresses_FullMethodName        = "/kacho.cloud.vpc.v1.AddressPoolService/ListAddresses"
	AddressPoolService_GetUtilization_FullMethodName       = "/kacho.cloud.vpc.v1.AddressPoolService/GetUtilization"
	AddressPoolService_Create_FullMethodName               = "/kacho.cloud.vpc.v1.AddressPoolService/Create"
	AddressPoolService_Update_FullMethodName               = "/kacho.cloud.vpc.v1.AddressPoolService/Update"
	AddressPoolService_Delete_FullMethodName               = "/kacho.cloud.vpc.v1.AddressPoolService/Delete"
	AddressPoolService_AddCidrBlocks_FullMethodName        = "/kacho.cloud.vpc.v1.AddressPoolService/AddCidrBlocks"
	AddressPoolService_RemoveCidrBlocks_FullMethodName     = "/kacho.cloud.vpc.v1.AddressPoolService/RemoveCidrBlocks"
	AddressPoolService_BindAsNetworkDefault_FullMethodName = "/kacho.cloud.vpc.v1.AddressPoolService/BindAsNetworkDefault"
	AddressPoolService_UnbindNetworkDefault_FullMethodName = "/kacho.cloud.vpc.v1.AddressPoolService/UnbindNetworkDefault"
)

// AddressPoolServiceClient is the client API for AddressPoolService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AddressPoolService — управление пулами адресов на ПУБЛИЧНОЙ поверхности, под
// правом администратора кластера (под-фаза ADM-1, корзина А2).
//
// # Почему административный ресурс живёт на публичном сервисе
//
// Граница проходит по ДАННЫМ и ПРАВУ, а не по тому, кто зовёт. Имя `Internal`
// означало сразу две несовместимые вещи: «данные, раскрытие которых помогает
// картировать физику» — это про данные и обязано остаться разделением по краю,
// потому что право не спасает, если поле уже в ответе; и «действие, дозволенное
// не всякому» — это про право, и краем оно выражается плохо: край отвечает на
// вопрос «откуда пришёл запрос», тогда как спрашивать надо «что этому
// вызывающему разрешено».
//
// Пул адресов — второй случай. Инфра-полей по перечню `security.md` он не несёт;
// закрыто должно быть не место вызова, а вызывающий без права. Запрет 6 при этом
// не смягчается ни в одной букве: `Internal*`-сервисы на внешнем крае
// по-прежнему не публикуются, и предикат, который это ловит
// (`HasInternalSuffix`), не тронут — меняется СОСТАВ того, что кладут в
// `Internal.*`, а не поверхность разрешённого для него.
//
// # Отношение — `system_admin`, и это не вкусовщина
//
// `viewer` @ `cluster` выполняется подстановочным кортежем `user:*` НАМЕРЕННО —
// так глобальный справочник читает каждый аутентифицированный арендатор. Значит
// запись каталога, стоящая на `viewer`, означает «аутентифицирован», а не
// «авторизован», и для административного глагола она была бы формой проверки без
// содержания. `system_admin` объявлен `[user, service_account]`, подстановки не
// несёт. Не `admin`/`editor` @ `cluster`: те выводятся из `system_admin`, но
// допускают и прямую выдачу в обход кластерного администрирования.
//
// # Пути те же, что у внутреннего сервиса — и почему
//
// Конвенция даёт ресурсу один канонический адрес `/vpc/v1/addressPools`; второй
// адрес того же предмета — это «два места об одном предмете, из которых верно
// одно». Пока идёт окно расширения (S1→S3), публичный и внутренний глаголы
// сосуществуют на одной паре (метод, путь): снаружи виден публичный (обе ветки
// диспетчера края на внешнем слушателе ведут в `publicMux`), изнутри —
// внутренний (`runtime.ServeMux.Handle` предваряет список, внутренние
// регистрации идут после публичных).
//
// # Форма ответа приведена к конвенции
//
// Мутации возвращают `operation.Operation` (запрет 9), а не ресурс синхронно.
// Внутренний сервис отвечает ресурсом — ему не приходилось соблюдать конвенцию,
// его не видел ни один арендатский клиент. Клиент публичного API вправе
// рассчитывать на один и тот же контракт у всех мутаций, а консоль — на один и
// тот же способ дождаться результата.
type AddressPoolServiceClient interface {
	Get(ctx context.Context, in *GetAddressPoolRequest, opts ...grpc.CallOption) (*AddressPool, error)
	// List — межпроектный по построению: пул адресов глобален, `project_id` у него
	// нет вовсе. Поэтому список гейтится ОДНИМ вопросом `system_admin` @ `cluster`,
	// а не сужается пообъектно: сужать нечего, объект один и он кластерный.
	// Арендатор без права получает отказ, а не пустую страницу — пустая страница
	// означала бы «чтение открыто, данных нет», то есть другое утверждение о
	// системе.
	List(ctx context.Context, in *ListAddressPoolsRequest, opts ...grpc.CallOption) (*ListAddressPoolsResponse, error)
	// ListAddresses — адреса ВСЕХ проектов, получившие IP из этого пула.
	// Межпроектность намеренна и является предметом глагола.
	ListAddresses(ctx context.Context, in *ListAddressPoolAddressesRequest, opts ...grpc.CallOption) (*ListAddressPoolAddressesResponse, error)
	GetUtilization(ctx context.Context, in *GetAddressPoolUtilizationRequest, opts ...grpc.CallOption) (*AddressPoolUtilization, error)
	Create(ctx context.Context, in *CreateAddressPoolRequest, opts ...grpc.CallOption) (*operation.Operation, error)
	Update(ctx context.Context, in *UpdateAddressPoolRequest, opts ...grpc.CallOption) (*operation.Operation, error)
	Delete(ctx context.Context, in *DeleteAddressPoolRequest, opts ...grpc.CallOption) (*operation.Operation, error)
	AddCidrBlocks(ctx context.Context, in *AddAddressPoolCidrBlocksRequest, opts ...grpc.CallOption) (*operation.Operation, error)
	RemoveCidrBlocks(ctx context.Context, in *RemoveAddressPoolCidrBlocksRequest, opts ...grpc.CallOption) (*operation.Operation, error)
	BindAsNetworkDefault(ctx context.Context, in *BindAsNetworkDefaultRequest, opts ...grpc.CallOption) (*operation.Operation, error)
	UnbindNetworkDefault(ctx context.Context, in *UnbindNetworkDefaultRequest, opts ...grpc.CallOption) (*operation.Operation, error)
}

type addressPoolServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAddressPoolServiceClient(cc grpc.ClientConnInterface) AddressPoolServiceClient {
	return &addressPoolServiceClient{cc}
}

func (c *addressPoolServiceClient) Get(ctx context.Context, in *GetAddressPoolRequest, opts ...grpc.CallOption) (*AddressPool, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddressPool)
	err := c.cc.Invoke(ctx, AddressPoolService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *addressPoolServiceClient) List(ctx context.Context, in *ListAddressPoolsRequest, opts ...grpc.CallOption) (*ListAddressPoolsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAddressPoolsResponse)
	err := c.cc.Invoke(ctx, AddressPoolService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *addressPoolServiceClient) ListAddresses(ctx context.Context, in *ListAddressPoolAddressesRequest, opts ...grpc.CallOption) (*ListAddressPoolAddressesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAddressPoolAddressesResponse)
	err := c.cc.Invoke(ctx, AddressPoolService_ListAddresses_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *addressPoolServiceClient) GetUtilization(ctx context.Context, in *GetAddressPoolUtilizationRequest, opts ...grpc.CallOption) (*AddressPoolUtilization, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddressPoolUtilization)
	err := c.cc.Invoke(ctx, AddressPoolService_GetUtilization_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *addressPoolServiceClient) Create(ctx context.Context, in *CreateAddressPoolRequest, opts ...grpc.CallOption) (*operation.Operation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(operation.Operation)
	err := c.cc.Invoke(ctx, AddressPoolService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *addressPoolServiceClient) Update(ctx context.Context, in *UpdateAddressPoolRequest, opts ...grpc.CallOption) (*operation.Operation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(operation.Operation)
	err := c.cc.Invoke(ctx, AddressPoolService_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *addressPoolServiceClient) Delete(ctx context.Context, in *DeleteAddressPoolRequest, opts ...grpc.CallOption) (*operation.Operation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(operation.Operation)
	err := c.cc.Invoke(ctx, AddressPoolService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *addressPoolServiceClient) AddCidrBlocks(ctx context.Context, in *AddAddressPoolCidrBlocksRequest, opts ...grpc.CallOption) (*operation.Operation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(operation.Operation)
	err := c.cc.Invoke(ctx, AddressPoolService_AddCidrBlocks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *addressPoolServiceClient) RemoveCidrBlocks(ctx context.Context, in *RemoveAddressPoolCidrBlocksRequest, opts ...grpc.CallOption) (*operation.Operation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(operation.Operation)
	err := c.cc.Invoke(ctx, AddressPoolService_RemoveCidrBlocks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *addressPoolServiceClient) BindAsNetworkDefault(ctx context.Context, in *BindAsNetworkDefaultRequest, opts ...grpc.CallOption) (*operation.Operation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(operation.Operation)
	err := c.cc.Invoke(ctx, AddressPoolService_BindAsNetworkDefault_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *addressPoolServiceClient) UnbindNetworkDefault(ctx context.Context, in *UnbindNetworkDefaultRequest, opts ...grpc.CallOption) (*operation.Operation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(operation.Operation)
	err := c.cc.Invoke(ctx, AddressPoolService_UnbindNetworkDefault_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AddressPoolServiceServer is the server API for AddressPoolService service.
// All implementations must embed UnimplementedAddressPoolServiceServer
// for forward compatibility.
//
// AddressPoolService — управление пулами адресов на ПУБЛИЧНОЙ поверхности, под
// правом администратора кластера (под-фаза ADM-1, корзина А2).
//
// # Почему административный ресурс живёт на публичном сервисе
//
// Граница проходит по ДАННЫМ и ПРАВУ, а не по тому, кто зовёт. Имя `Internal`
// означало сразу две несовместимые вещи: «данные, раскрытие которых помогает
// картировать физику» — это про данные и обязано остаться разделением по краю,
// потому что право не спасает, если поле уже в ответе; и «действие, дозволенное
// не всякому» — это про право, и краем оно выражается плохо: край отвечает на
// вопрос «откуда пришёл запрос», тогда как спрашивать надо «что этому
// вызывающему разрешено».
//
// Пул адресов — второй случай. Инфра-полей по перечню `security.md` он не несёт;
// закрыто должно быть не место вызова, а вызывающий без права. Запрет 6 при этом
// не смягчается ни в одной букве: `Internal*`-сервисы на внешнем крае
// по-прежнему не публикуются, и предикат, который это ловит
// (`HasInternalSuffix`), не тронут — меняется СОСТАВ того, что кладут в
// `Internal.*`, а не поверхность разрешённого для него.
//
// # Отношение — `system_admin`, и это не вкусовщина
//
// `viewer` @ `cluster` выполняется подстановочным кортежем `user:*` НАМЕРЕННО —
// так глобальный справочник читает каждый аутентифицированный арендатор. Значит
// запись каталога, стоящая на `viewer`, означает «аутентифицирован», а не
// «авторизован», и для административного глагола она была бы формой проверки без
// содержания. `system_admin` объявлен `[user, service_account]`, подстановки не
// несёт. Не `admin`/`editor` @ `cluster`: те выводятся из `system_admin`, но
// допускают и прямую выдачу в обход кластерного администрирования.
//
// # Пути те же, что у внутреннего сервиса — и почему
//
// Конвенция даёт ресурсу один канонический адрес `/vpc/v1/addressPools`; второй
// адрес того же предмета — это «два места об одном предмете, из которых верно
// одно». Пока идёт окно расширения (S1→S3), публичный и внутренний глаголы
// сосуществуют на одной паре (метод, путь): снаружи виден публичный (обе ветки
// диспетчера края на внешнем слушателе ведут в `publicMux`), изнутри —
// внутренний (`runtime.ServeMux.Handle` предваряет список, внутренние
// регистрации идут после публичных).
//
// # Форма ответа приведена к конвенции
//
// Мутации возвращают `operation.Operation` (запрет 9), а не ресурс синхронно.
// Внутренний сервис отвечает ресурсом — ему не приходилось соблюдать конвенцию,
// его не видел ни один арендатский клиент. Клиент публичного API вправе
// рассчитывать на один и тот же контракт у всех мутаций, а консоль — на один и
// тот же способ дождаться результата.
type AddressPoolServiceServer interface {
	Get(context.Context, *GetAddressPoolRequest) (*AddressPool, error)
	// List — межпроектный по построению: пул адресов глобален, `project_id` у него
	// нет вовсе. Поэтому список гейтится ОДНИМ вопросом `system_admin` @ `cluster`,
	// а не сужается пообъектно: сужать нечего, объект один и он кластерный.
	// Арендатор без права получает отказ, а не пустую страницу — пустая страница
	// означала бы «чтение открыто, данных нет», то есть другое утверждение о
	// системе.
	List(context.Context, *ListAddressPoolsRequest) (*ListAddressPoolsResponse, error)
	// ListAddresses — адреса ВСЕХ проектов, получившие IP из этого пула.
	// Межпроектность намеренна и является предметом глагола.
	ListAddresses(context.Context, *ListAddressPoolAddressesRequest) (*ListAddressPoolAddressesResponse, error)
	GetUtilization(context.Context, *GetAddressPoolUtilizationRequest) (*AddressPoolUtilization, error)
	Create(context.Context, *CreateAddressPoolRequest) (*operation.Operation, error)
	Update(context.Context, *UpdateAddressPoolRequest) (*operation.Operation, error)
	Delete(context.Context, *DeleteAddressPoolRequest) (*operation.Operation, error)
	AddCidrBlocks(context.Context, *AddAddressPoolCidrBlocksRequest) (*operation.Operation, error)
	RemoveCidrBlocks(context.Context, *RemoveAddressPoolCidrBlocksRequest) (*operation.Operation, error)
	BindAsNetworkDefault(context.Context, *BindAsNetworkDefaultRequest) (*operation.Operation, error)
	UnbindNetworkDefault(context.Context, *UnbindNetworkDefaultRequest) (*operation.Operation, error)
	mustEmbedUnimplementedAddressPoolServiceServer()
}

// UnimplementedAddressPoolServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAddressPoolServiceServer struct{}

func (UnimplementedAddressPoolServiceServer) Get(context.Context, *GetAddressPoolRequest) (*AddressPool, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedAddressPoolServiceServer) List(context.Context, *ListAddressPoolsRequest) (*ListAddressPoolsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedAddressPoolServiceServer) ListAddresses(context.Context, *ListAddressPoolAddressesRequest) (*ListAddressPoolAddressesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAddresses not implemented")
}
func (UnimplementedAddressPoolServiceServer) GetUtilization(context.Context, *GetAddressPoolUtilizationRequest) (*AddressPoolUtilization, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUtilization not implemented")
}
func (UnimplementedAddressPoolServiceServer) Create(context.Context, *CreateAddressPoolRequest) (*operation.Operation, error) {
	return nil, status.Error(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedAddressPoolServiceServer) Update(context.Context, *UpdateAddressPoolRequest) (*operation.Operation, error) {
	return nil, status.Error(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedAddressPoolServiceServer) Delete(context.Context, *DeleteAddressPoolRequest) (*operation.Operation, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedAddressPoolServiceServer) AddCidrBlocks(context.Context, *AddAddressPoolCidrBlocksRequest) (*operation.Operation, error) {
	return nil, status.Error(codes.Unimplemented, "method AddCidrBlocks not implemented")
}
func (UnimplementedAddressPoolServiceServer) RemoveCidrBlocks(context.Context, *RemoveAddressPoolCidrBlocksRequest) (*operation.Operation, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveCidrBlocks not implemented")
}
func (UnimplementedAddressPoolServiceServer) BindAsNetworkDefault(context.Context, *BindAsNetworkDefaultRequest) (*operation.Operation, error) {
	return nil, status.Error(codes.Unimplemented, "method BindAsNetworkDefault not implemented")
}
func (UnimplementedAddressPoolServiceServer) UnbindNetworkDefault(context.Context, *UnbindNetworkDefaultRequest) (*operation.Operation, error) {
	return nil, status.Error(codes.Unimplemented, "method UnbindNetworkDefault not implemented")
}
func (UnimplementedAddressPoolServiceServer) mustEmbedUnimplementedAddressPoolServiceServer() {}
func (UnimplementedAddressPoolServiceServer) testEmbeddedByValue()                            {}

// UnsafeAddressPoolServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AddressPoolServiceServer will
// result in compilation errors.
type UnsafeAddressPoolServiceServer interface {
	mustEmbedUnimplementedAddressPoolServiceServer()
}

func RegisterAddressPoolServiceServer(s grpc.ServiceRegistrar, srv AddressPoolServiceServer) {
	// If the following call panics, it indicates UnimplementedAddressPoolServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AddressPoolService_ServiceDesc, srv)
}

func _AddressPoolService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAddressPoolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddressPoolServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AddressPoolService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddressPoolServiceServer).Get(ctx, req.(*GetAddressPoolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AddressPoolService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAddressPoolsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddressPoolServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AddressPoolService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddressPoolServiceServer).List(ctx, req.(*ListAddressPoolsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AddressPoolService_ListAddresses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAddressPoolAddressesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddressPoolServiceServer).ListAddresses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AddressPoolService_ListAddresses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddressPoolServiceServer).ListAddresses(ctx, req.(*ListAddressPoolAddressesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AddressPoolService_GetUtilization_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAddressPoolUtilizationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddressPoolServiceServer).GetUtilization(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AddressPoolService_GetUtilization_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddressPoolServiceServer).GetUtilization(ctx, req.(*GetAddressPoolUtilizationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AddressPoolService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAddressPoolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddressPoolServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AddressPoolService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddressPoolServiceServer).Create(ctx, req.(*CreateAddressPoolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AddressPoolService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAddressPoolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddressPoolServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AddressPoolService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddressPoolServiceServer).Update(ctx, req.(*UpdateAddressPoolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AddressPoolService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAddressPoolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddressPoolServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AddressPoolService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddressPoolServiceServer).Delete(ctx, req.(*DeleteAddressPoolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AddressPoolService_AddCidrBlocks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddAddressPoolCidrBlocksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddressPoolServiceServer).AddCidrBlocks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AddressPoolService_AddCidrBlocks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddressPoolServiceServer).AddCidrBlocks(ctx, req.(*AddAddressPoolCidrBlocksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AddressPoolService_RemoveCidrBlocks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveAddressPoolCidrBlocksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddressPoolServiceServer).RemoveCidrBlocks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AddressPoolService_RemoveCidrBlocks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddressPoolServiceServer).RemoveCidrBlocks(ctx, req.(*RemoveAddressPoolCidrBlocksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AddressPoolService_BindAsNetworkDefault_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BindAsNetworkDefaultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddressPoolServiceServer).BindAsNetworkDefault(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AddressPoolService_BindAsNetworkDefault_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddressPoolServiceServer).BindAsNetworkDefault(ctx, req.(*BindAsNetworkDefaultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AddressPoolService_UnbindNetworkDefault_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnbindNetworkDefaultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddressPoolServiceServer).UnbindNetworkDefault(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AddressPoolService_UnbindNetworkDefault_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddressPoolServiceServer).UnbindNetworkDefault(ctx, req.(*UnbindNetworkDefaultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AddressPoolService_ServiceDesc is the grpc.ServiceDesc for AddressPoolService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AddressPoolService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kacho.cloud.vpc.v1.AddressPoolService",
	HandlerType: (*AddressPoolServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _AddressPoolService_Get_Handler,
		},
		{
			MethodName: "List",
			Handler:    _AddressPoolService_List_Handler,
		},
		{
			MethodName: "ListAddresses",
			Handler:    _AddressPoolService_ListAddresses_Handler,
		},
		{
			MethodName: "GetUtilization",
			Handler:    _AddressPoolService_GetUtilization_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _AddressPoolService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _AddressPoolService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _AddressPoolService_Delete_Handler,
		},
		{
			MethodName: "AddCidrBlocks",
			Handler:    _AddressPoolService_AddCidrBlocks_Handler,
		},
		{
			MethodName: "RemoveCidrBlocks",
			Handler:    _AddressPoolService_RemoveCidrBlocks_Handler,
		},
		{
			MethodName: "BindAsNetworkDefault",
			Handler:    _AddressPoolService_BindAsNetworkDefault_Handler,
		},
		{
			MethodName: "UnbindNetworkDefault",
			Handler:    _AddressPoolService_UnbindNetworkDefault_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kacho/cloud/vpc/v1/address_pool_service.proto",
}
