// Copyright (c) PRO-Robotech
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: kacho/cloud/vpc/v1/cidr_group_service.proto

package vpcv1

import (
	_ "github.com/PRO-Robotech/kacho/pkg/api/kacho/cloud/api"
	operation "github.com/PRO-Robotech/kacho/pkg/api/kacho/cloud/operation"
	_ "github.com/PRO-Robotech/kacho/pkg/api/kacho/iam/authz/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCidrGroupRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the CidrGroup resource to return.
	CidrGroupId   string `protobuf:"bytes,1,opt,name=cidr_group_id,json=cidrGroupId,proto3" json:"cidr_group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCidrGroupRequest) Reset() {
	*x = GetCidrGroupRequest{}
	mi := &file_kacho_cloud_vpc_v1_cidr_group_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCidrGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCidrGroupRequest) ProtoMessage() {}

func (x *GetCidrGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kacho_cloud_vpc_v1_cidr_group_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCidrGroupRequest.ProtoReflect.Descriptor instead.
func (*GetCidrGroupRequest) Descriptor() ([]byte, []int) {
	return file_kacho_cloud_vpc_v1_cidr_group_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetCidrGroupRequest) GetCidrGroupId() string {
	if x != nil {
		return x.CidrGroupId
	}
	return ""
}

type ListCidrGroupsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the project to list CIDR groups in.
	ProjectId string `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	// The maximum number of results per page to return. Rejected outside [0..1000]
	// rather than clamped; 0 means the service default.
	PageSize int64 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Page token returned by a previous list request.
	PageToken string `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// A filter expression. Filtering is available on [CidrGroup.name].
	Filter        string `protobuf:"bytes,4,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCidrGroupsRequest) Reset() {
	*x = ListCidrGroupsRequest{}
	mi := &file_kacho_cloud_vpc_v1_cidr_group_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCidrGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCidrGroupsRequest) ProtoMessage() {}

func (x *ListCidrGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kacho_cloud_vpc_v1_cidr_group_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCidrGroupsRequest.ProtoReflect.Descriptor instead.
func (*ListCidrGroupsRequest) Descriptor() ([]byte, []int) {
	return file_kacho_cloud_vpc_v1_cidr_group_service_proto_rawDescGZIP(), []int{1}
}

func (x *ListCidrGroupsRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *ListCidrGroupsRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListCidrGroupsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListCidrGroupsRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

type ListCidrGroupsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of CidrGroup resources.
	CidrGroups []*CidrGroup `protobuf:"bytes,1,rep,name=cidr_groups,json=cidrGroups,proto3" json:"cidr_groups,omitempty"`
	// Token for the next page of results, empty when this page is the last one.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCidrGroupsResponse) Reset() {
	*x = ListCidrGroupsResponse{}
	mi := &file_kacho_cloud_vpc_v1_cidr_group_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCidrGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCidrGroupsResponse) ProtoMessage() {}

func (x *ListCidrGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kacho_cloud_vpc_v1_cidr_group_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCidrGroupsResponse.ProtoReflect.Descriptor instead.
func (*ListCidrGroupsResponse) Descriptor() ([]byte, []int) {
	return file_kacho_cloud_vpc_v1_cidr_group_service_proto_rawDescGZIP(), []int{2}
}

func (x *ListCidrGroupsResponse) GetCidrGroups() []*CidrGroup {
	if x != nil {
		return x.CidrGroups
	}
	return nil
}

func (x *ListCidrGroupsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type CreateCidrGroupRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the project to create the CIDR group in.
	ProjectId string `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	// Name of the CIDR group. Unique within the project.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Description of the CIDR group.
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Resource labels as “ key:value “ pairs.
	Labels map[string]string `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Initial IPv4 members, canonical network form (host bits zero). At most 64
	// per family — the cap is what the set becomes as a rule size at the executor.
	V4CidrBlocks []string `protobuf:"bytes,5,rep,name=v4_cidr_blocks,json=v4CidrBlocks,proto3" json:"v4_cidr_blocks,omitempty"`
	// Initial IPv6 members. Mirror of v4_cidr_blocks.
	V6CidrBlocks  []string `protobuf:"bytes,6,rep,name=v6_cidr_blocks,json=v6CidrBlocks,proto3" json:"v6_cidr_blocks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCidrGroupRequest) Reset() {
	*x = CreateCidrGroupRequest{}
	mi := &file_kacho_cloud_vpc_v1_cidr_group_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCidrGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCidrGroupRequest) ProtoMessage() {}

func (x *CreateCidrGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kacho_cloud_vpc_v1_cidr_group_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCidrGroupRequest.ProtoReflect.Descriptor instead.
func (*CreateCidrGroupRequest) Descriptor() ([]byte, []int) {
	return file_kacho_cloud_vpc_v1_cidr_group_service_proto_rawDescGZIP(), []int{3}
}

func (x *CreateCidrGroupRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *CreateCidrGroupRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCidrGroupRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateCidrGroupRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *CreateCidrGroupRequest) GetV4CidrBlocks() []string {
	if x != nil {
		return x.V4CidrBlocks
	}
	return nil
}

func (x *CreateCidrGroupRequest) GetV6CidrBlocks() []string {
	if x != nil {
		return x.V6CidrBlocks
	}
	return nil
}

type CreateCidrGroupMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the CidrGroup that is being created.
	CidrGroupId   string `protobuf:"bytes,1,opt,name=cidr_group_id,json=cidrGroupId,proto3" json:"cidr_group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCidrGroupMetadata) Reset() {
	*x = CreateCidrGroupMetadata{}
	mi := &file_kacho_cloud_vpc_v1_cidr_group_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCidrGroupMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCidrGroupMetadata) ProtoMessage() {}

func (x *CreateCidrGroupMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_kacho_cloud_vpc_v1_cidr_group_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCidrGroupMetadata.ProtoReflect.Descriptor instead.
func (*CreateCidrGroupMetadata) Descriptor() ([]byte, []int) {
	return file_kacho_cloud_vpc_v1_cidr_group_service_proto_rawDescGZIP(), []int{4}
}

func (x *CreateCidrGroupMetadata) GetCidrGroupId() string {
	if x != nil {
		return x.CidrGroupId
	}
	return ""
}

type UpdateCidrGroupRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the CidrGroup resource to update.
	CidrGroupId string `protobuf:"bytes,1,opt,name=cidr_group_id,json=cidrGroupId,proto3" json:"cidr_group_id,omitempty"`
	// Field mask specifying which fields are updated. Membership fields are not
	// updatable here — use :add-cidr-blocks / :remove-cidr-blocks.
	UpdateMask *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	// Name of the CIDR group.
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// Description of the CIDR group.
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// Resource labels as “ key:value “ pairs.
	Labels        map[string]string `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCidrGroupRequest) Reset() {
	*x = UpdateCidrGroupRequest{}
	mi := &file_kacho_cloud_vpc_v1_cidr_group_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCidrGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCidrGroupRequest) ProtoMessage() {}

func (x *UpdateCidrGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kacho_cloud_vpc_v1_cidr_group_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCidrGroupRequest.ProtoReflect.Descriptor instead.
func (*UpdateCidrGroupRequest) Descriptor() ([]byte, []int) {
	return file_kacho_cloud_vpc_v1_cidr_group_service_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateCidrGroupRequest) GetCidrGroupId() string {
	if x != nil {
		return x.CidrGroupId
	}
	return ""
}

func (x *UpdateCidrGroupRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

func (x *UpdateCidrGroupRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateCidrGroupRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateCidrGroupRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type UpdateCidrGroupMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the CidrGroup resource that is being updated.
	CidrGroupId   string `protobuf:"bytes,1,opt,name=cidr_group_id,json=cidrGroupId,proto3" json:"cidr_group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCidrGroupMetadata) Reset() {
	*x = UpdateCidrGroupMetadata{}
	mi := &file_kacho_cloud_vpc_v1_cidr_group_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCidrGroupMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCidrGroupMetadata) ProtoMessage() {}

func (x *UpdateCidrGroupMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_kacho_cloud_vpc_v1_cidr_group_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCidrGroupMetadata.ProtoReflect.Descriptor instead.
func (*UpdateCidrGroupMetadata) Descriptor() ([]byte, []int) {
	return file_kacho_cloud_vpc_v1_cidr_group_service_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateCidrGroupMetadata) GetCidrGroupId() string {
	if x != nil {
		return x.CidrGroupId
	}
	return ""
}

type AddCidrGroupCidrBlocksRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the CidrGroup whose membership is being extended.
	CidrGroupId string `protobuf:"bytes,1,opt,name=cidr_group_id,json=cidrGroupId,proto3" json:"cidr_group_id,omitempty"`
	// IPv4 block(s) to add, canonical network form (host bits zero).
	V4CidrBlocks []string `protobuf:"bytes,2,rep,name=v4_cidr_blocks,json=v4CidrBlocks,proto3" json:"v4_cidr_blocks,omitempty"`
	// IPv6 block(s) to add.
	V6CidrBlocks  []string `protobuf:"bytes,3,rep,name=v6_cidr_blocks,json=v6CidrBlocks,proto3" json:"v6_cidr_blocks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCidrGroupCidrBlocksRequest) Reset() {
	*x = AddCidrGroupCidrBlocksRequest{}
	mi := &file_kacho_cloud_vpc_v1_cidr_group_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCidrGroupCidrBlocksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCidrGroupCidrBlocksRequest) ProtoMessage() {}

func (x *AddCidrGroupCidrBlocksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kacho_cloud_vpc_v1_cidr_group_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCidrGroupCidrBlocksRequest.ProtoReflect.Descriptor instead.
func (*AddCidrGroupCidrBlocksRequest) Descriptor() ([]byte, []int) {
	return file_kacho_cloud_vpc_v1_cidr_group_service_proto_rawDescGZIP(), []int{7}
}

func (x *AddCidrGroupCidrBlocksRequest) GetCidrGroupId() string {
	if x != nil {
		return x.CidrGroupId
	}
	return ""
}

func (x *AddCidrGroupCidrBlocksRequest) GetV4CidrBlocks() []string {
	if x != nil {
		return x.V4CidrBlocks
	}
	return nil
}

func (x *AddCidrGroupCidrBlocksRequest) GetV6CidrBlocks() []string {
	if x != nil {
		return x.V6CidrBlocks
	}
	return nil
}

type RemoveCidrGroupCidrBlocksRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the CidrGroup whose membership is being reduced.
	CidrGroupId string `protobuf:"bytes,1,opt,name=cidr_group_id,json=cidrGroupId,proto3" json:"cidr_group_id,omitempty"`
	// IPv4 block(s) to remove.
	V4CidrBlocks []string `protobuf:"bytes,2,rep,name=v4_cidr_blocks,json=v4CidrBlocks,proto3" json:"v4_cidr_blocks,omitempty"`
	// IPv6 block(s) to remove.
	V6CidrBlocks  []string `protobuf:"bytes,3,rep,name=v6_cidr_blocks,json=v6CidrBlocks,proto3" json:"v6_cidr_blocks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveCidrGroupCidrBlocksRequest) Reset() {
	*x = RemoveCidrGroupCidrBlocksRequest{}
	mi := &file_kacho_cloud_vpc_v1_cidr_group_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveCidrGroupCidrBlocksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveCidrGroupCidrBlocksRequest) ProtoMessage() {}

func (x *RemoveCidrGroupCidrBlocksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kacho_cloud_vpc_v1_cidr_group_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveCidrGroupCidrBlocksRequest.ProtoReflect.Descriptor instead.
func (*RemoveCidrGroupCidrBlocksRequest) Descriptor() ([]byte, []int) {
	return file_kacho_cloud_vpc_v1_cidr_group_service_proto_rawDescGZIP(), []int{8}
}

func (x *RemoveCidrGroupCidrBlocksRequest) GetCidrGroupId() string {
	if x != nil {
		return x.CidrGroupId
	}
	return ""
}

func (x *RemoveCidrGroupCidrBlocksRequest) GetV4CidrBlocks() []string {
	if x != nil {
		return x.V4CidrBlocks
	}
	return nil
}

func (x *RemoveCidrGroupCidrBlocksRequest) GetV6CidrBlocks() []string {
	if x != nil {
		return x.V6CidrBlocks
	}
	return nil
}

type DeleteCidrGroupRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the CidrGroup resource to delete.
	CidrGroupId   string `protobuf:"bytes,1,opt,name=cidr_group_id,json=cidrGroupId,proto3" json:"cidr_group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCidrGroupRequest) Reset() {
	*x = DeleteCidrGroupRequest{}
	mi := &file_kacho_cloud_vpc_v1_cidr_group_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCidrGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCidrGroupRequest) ProtoMessage() {}

func (x *DeleteCidrGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kacho_cloud_vpc_v1_cidr_group_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCidrGroupRequest.ProtoReflect.Descriptor instead.
func (*DeleteCidrGroupRequest) Descriptor() ([]byte, []int) {
	return file_kacho_cloud_vpc_v1_cidr_group_service_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteCidrGroupRequest) GetCidrGroupId() string {
	if x != nil {
		return x.CidrGroupId
	}
	return ""
}

type DeleteCidrGroupMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the CidrGroup that is being deleted.
	CidrGroupId   string `protobuf:"bytes,1,opt,name=cidr_group_id,json=cidrGroupId,proto3" json:"cidr_group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCidrGroupMetadata) Reset() {
	*x = DeleteCidrGroupMetadata{}
	mi := &file_kacho_cloud_vpc_v1_cidr_group_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCidrGroupMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCidrGroupMetadata) ProtoMessage() {}

func (x *DeleteCidrGroupMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_kacho_cloud_vpc_v1_cidr_group_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCidrGroupMetadata.ProtoReflect.Descriptor instead.
func (*DeleteCidrGroupMetadata) Descriptor() ([]byte, []int) {
	return file_kacho_cloud_vpc_v1_cidr_group_service_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteCidrGroupMetadata) GetCidrGroupId() string {
	if x != nil {
		return x.CidrGroupId
	}
	return ""
}

type ListCidrGroupOperationsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the CidrGroup resource to list operations for.
	CidrGroupId string `protobuf:"bytes,1,opt,name=cidr_group_id,json=cidrGroupId,proto3" json:"cidr_group_id,omitempty"`
	// The maximum number of results per page to return.
	PageSize int64 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Page token returned by a previous list request.
	PageToken     string `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCidrGroupOperationsRequest) Reset() {
	*x = ListCidrGroupOperationsRequest{}
	mi := &file_kacho_cloud_vpc_v1_cidr_group_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCidrGroupOperationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCidrGroupOperationsRequest) ProtoMessage() {}

func (x *ListCidrGroupOperationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kacho_cloud_vpc_v1_cidr_group_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCidrGroupOperationsRequest.ProtoReflect.Descriptor instead.
func (*ListCidrGroupOperationsRequest) Descriptor() ([]byte, []int) {
	return file_kacho_cloud_vpc_v1_cidr_group_service_proto_rawDescGZIP(), []int{11}
}

func (x *ListCidrGroupOperationsRequest) GetCidrGroupId() string {
	if x != nil {
		return x.CidrGroupId
	}
	return ""
}

func (x *ListCidrGroupOperationsRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListCidrGroupOperationsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListCidrGroupOperationsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of operations for the specified CIDR group.
	Operations []*operation.Operation `protobuf:"bytes,1,rep,name=operations,proto3" json:"operations,omitempty"`
	// Token for the next page of results, empty when this page is the last one.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCidrGroupOperationsResponse) Reset() {
	*x = ListCidrGroupOperationsResponse{}
	mi := &file_kacho_cloud_vpc_v1_cidr_group_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCidrGroupOperationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCidrGroupOperationsResponse) ProtoMessage() {}

func (x *ListCidrGroupOperationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kacho_cloud_vpc_v1_cidr_group_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCidrGroupOperationsResponse.ProtoReflect.Descriptor instead.
func (*ListCidrGroupOperationsResponse) Descriptor() ([]byte, []int) {
	return file_kacho_cloud_vpc_v1_cidr_group_service_proto_rawDescGZIP(), []int{12}
}

func (x *ListCidrGroupOperationsResponse) GetOperations() []*operation.Operation {
	if x != nil {
		return x.Operations
	}
	return nil
}

func (x *ListCidrGroupOperationsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

var File_kacho_cloud_vpc_v1_cidr_group_service_proto protoreflect.FileDescriptor

const file_kacho_cloud_vpc_v1_cidr_group_service_proto_rawDesc = "" +
	"\n" +
	"+kacho/cloud/vpc/v1/cidr_group_service.proto\x12\x12kacho.cloud.vpc.v1\x1a\x1cgoogle/api/annotations.proto\x1a google/protobuf/field_mask.proto\x1a\x1fkacho/cloud/api/operation.proto\x1a#kacho/cloud/vpc/v1/cidr_group.proto\x1a%kacho/cloud/operation/operation.proto\x1a&kacho/iam/authz/v1/authz_options.proto\"9\n" +
	"\x13GetCidrGroupRequest\x12\"\n" +
	"\rcidr_group_id\x18\x01 \x01(\tR\vcidrGroupId\"\x8a\x01\n" +
	"\x15ListCidrGroupsRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x03R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\x12\x16\n" +
	"\x06filter\x18\x04 \x01(\tR\x06filter\"\x80\x01\n" +
	"\x16ListCidrGroupsResponse\x12>\n" +
	"\vcidr_groups\x18\x01 \x03(\v2\x1d.kacho.cloud.vpc.v1.CidrGroupR\n" +
	"cidrGroups\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\xc4\x02\n" +
	"\x16CreateCidrGroupRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12N\n" +
	"\x06labels\x18\x04 \x03(\v26.kacho.cloud.vpc.v1.CreateCidrGroupRequest.LabelsEntryR\x06labels\x12$\n" +
	"\x0ev4_cidr_blocks\x18\x05 \x03(\tR\fv4CidrBlocks\x12$\n" +
	"\x0ev6_cidr_blocks\x18\x06 \x03(\tR\fv6CidrBlocks\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"=\n" +
	"\x17CreateCidrGroupMetadata\x12\"\n" +
	"\rcidr_group_id\x18\x01 \x01(\tR\vcidrGroupId\"\xba\x02\n" +
	"\x16UpdateCidrGroupRequest\x12\"\n" +
	"\rcidr_group_id\x18\x01 \x01(\tR\vcidrGroupId\x12;\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12N\n" +
	"\x06labels\x18\x05 \x03(\v26.kacho.cloud.vpc.v1.UpdateCidrGroupRequest.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"=\n" +
	"\x17UpdateCidrGroupMetadata\x12\"\n" +
	"\rcidr_group_id\x18\x01 \x01(\tR\vcidrGroupId\"\x8f\x01\n" +
	"\x1dAddCidrGroupCidrBlocksRequest\x12\"\n" +
	"\rcidr_group_id\x18\x01 \x01(\tR\vcidrGroupId\x12$\n" +
	"\x0ev4_cidr_blocks\x18\x02 \x03(\tR\fv4CidrBlocks\x12$\n" +
	"\x0ev6_cidr_blocks\x18\x03 \x03(\tR\fv6CidrBlocks\"\x92\x01\n" +
	" RemoveCidrGroupCidrBlocksRequest\x12\"\n" +
	"\rcidr_group_id\x18\x01 \x01(\tR\vcidrGroupId\x12$\n" +
	"\x0ev4_cidr_blocks\x18\x02 \x03(\tR\fv4CidrBlocks\x12$\n" +
	"\x0ev6_cidr_blocks\x18\x03 \x03(\tR\fv6CidrBlocks\"<\n" +
	"\x16DeleteCidrGroupRequest\x12\"\n" +
	"\rcidr_group_id\x18\x01 \x01(\tR\vcidrGroupId\"=\n" +
	"\x17DeleteCidrGroupMetadata\x12\"\n" +
	"\rcidr_group_id\x18\x01 \x01(\tR\vcidrGroupId\"\x80\x01\n" +
	"\x1eListCidrGroupOperationsRequest\x12\"\n" +
	"\rcidr_group_id\x18\x01 \x01(\tR\vcidrGroupId\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x03R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"\x8b\x01\n" +
	"\x1fListCidrGroupOperationsResponse\x12@\n" +
	"\n" +
	"operations\x18\x01 \x03(\v2 .kacho.cloud.operation.OperationR\n" +
	"operations\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken2\xee\x0f\n" +
	"\x10CidrGroupService\x12\xc1\x01\n" +
	"\x03Get\x12'.kacho.cloud.vpc.v1.GetCidrGroupRequest\x1a\x1d.kacho.cloud.vpc.v1.CidrGroup\"r\x8a\xb5\x18\x13vpc.cidr_groups.get\x92\xb5\x18\x05v_get\x9a\xb5\x18\x1f\n" +
	"\x0evpc_cidr_group\x12\rcidr_group_id\xa2\xb5\x18\x011\x82\xd3\xe4\x93\x02$\x12\"/vpc/v1/cidrGroups/{cidr_group_id}\x12\xb9\x01\n" +
	"\x04List\x12).kacho.cloud.vpc.v1.ListCidrGroupsRequest\x1a*.kacho.cloud.vpc.v1.ListCidrGroupsResponse\"Z\x8a\xb5\x18\x14vpc.cidr_groups.list\x92\xb5\x18\x06viewer\x9a\xb5\x18\x15\n" +
	"\aproject\x12\n" +
	"project_id\xa2\xb5\x18\x011\x82\xd3\xe4\x93\x02\x14\x12\x12/vpc/v1/cidrGroups\x12\xe0\x01\n" +
	"\x06Create\x12*.kacho.cloud.vpc.v1.CreateCidrGroupRequest\x1a .kacho.cloud.operation.Operation\"\x87\x01\x8a\xb5\x18\x16vpc.cidr_groups.create\x92\xb5\x18\x06editor\x9a\xb5\x18\x15\n" +
	"\aproject\x12\n" +
	"project_id\xa2\xb5\x18\x011\xb2\xd2*$\n" +
	"\x17CreateCidrGroupMetadata\x12\tCidrGroup\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/vpc/v1/cidrGroups\x12\xfc\x01\n" +
	"\x06Update\x12*.kacho.cloud.vpc.v1.UpdateCidrGroupRequest\x1a .kacho.cloud.operation.Operation\"\xa3\x01\x8a\xb5\x18\x16vpc.cidr_groups.update\x92\xb5\x18\bv_update\x9a\xb5\x18\x1f\n" +
	"\x0evpc_cidr_group\x12\rcidr_group_id\xa2\xb5\x18\x011\xb2\xd2*$\n" +
	"\x17UpdateCidrGroupMetadata\x12\tCidrGroup\x82\xd3\xe4\x93\x02':\x01*2\"/vpc/v1/cidrGroups/{cidr_group_id}\x12\xa7\x02\n" +
	"\rAddCidrBlocks\x121.kacho.cloud.vpc.v1.AddCidrGroupCidrBlocksRequest\x1a .kacho.cloud.operation.Operation\"\xc0\x01\x8a\xb5\x18#vpc.cidr_group_blocks.addCidrBlocks\x92\xb5\x18\bv_update\x9a\xb5\x18\x1f\n" +
	"\x0evpc_cidr_group\x12\rcidr_group_id\xa2\xb5\x18\x011\xb2\xd2*$\n" +
	"\x17UpdateCidrGroupMetadata\x12\tCidrGroup\x82\xd3\xe4\x93\x027:\x01*\"2/vpc/v1/cidrGroups/{cidr_group_id}:add-cidr-blocks\x12\xb3\x02\n" +
	"\x10RemoveCidrBlocks\x124.kacho.cloud.vpc.v1.RemoveCidrGroupCidrBlocksRequest\x1a .kacho.cloud.operation.Operation\"\xc6\x01\x8a\xb5\x18&vpc.cidr_group_blocks.removeCidrBlocks\x92\xb5\x18\bv_update\x9a\xb5\x18\x1f\n" +
	"\x0evpc_cidr_group\x12\rcidr_group_id\xa2\xb5\x18\x011\xb2\xd2*$\n" +
	"\x17UpdateCidrGroupMetadata\x12\tCidrGroup\x82\xd3\xe4\x93\x02::\x01*\"5/vpc/v1/cidrGroups/{cidr_group_id}:remove-cidr-blocks\x12\x85\x02\n" +
	"\x06Delete\x12*.kacho.cloud.vpc.v1.DeleteCidrGroupRequest\x1a .kacho.cloud.operation.Operation\"\xac\x01\x8a\xb5\x18\x16vpc.cidr_groups.delete\x92\xb5\x18\bv_delete\x9a\xb5\x18\x1f\n" +
	"\x0evpc_cidr_group\x12\rcidr_group_id\xa2\xb5\x18\x011\xb2\xd2*0\n" +
	"\x17DeleteCidrGroupMetadata\x12\x15google.protobuf.Empty\x82\xd3\xe4\x93\x02$*\"/vpc/v1/cidrGroups/{cidr_group_id}\x12\x8f\x02\n" +
	"\x0eListOperations\x122.kacho.cloud.vpc.v1.ListCidrGroupOperationsRequest\x1a3.kacho.cloud.vpc.v1.ListCidrGroupOperationsResponse\"\x93\x01\x8a\xb5\x18(vpc.cidr_group_operations.listOperations\x92\xb5\x18\x06v_list\x9a\xb5\x18\x1f\n" +
	"\x0evpc_cidr_group\x12\rcidr_group_id\xa2\xb5\x18\x011\x82\xd3\xe4\x93\x02/\x12-/vpc/v1/cidrGroups/{cidr_group_id}/operationsB@Z>github.com/PRO-Robotech/kacho/pkg/api/kacho/cloud/vpc/v1;vpcv1b\x06proto3"

var (
	file_kacho_cloud_vpc_v1_cidr_group_service_proto_rawDescOnce sync.Once
	file_kacho_cloud_vpc_v1_cidr_group_service_proto_rawDescData []byte
)

func file_kacho_cloud_vpc_v1_cidr_group_service_proto_rawDescGZIP() []byte {
	file_kacho_cloud_vpc_v1_cidr_group_service_proto_rawDescOnce.Do(func() {
		file_kacho_cloud_vpc_v1_cidr_group_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kacho_cloud_vpc_v1_cidr_group_service_proto_rawDesc), len(file_kacho_cloud_vpc_v1_cidr_group_service_proto_rawDesc)))
	})
	return file_kacho_cloud_vpc_v1_cidr_group_service_proto_rawDescData
}

var file_kacho_cloud_vpc_v1_cidr_group_service_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_kacho_cloud_vpc_v1_cidr_group_service_proto_goTypes = []any{
	(*GetCidrGroupRequest)(nil),              // 0: kacho.cloud.vpc.v1.GetCidrGroupRequest
	(*ListCidrGroupsRequest)(nil),            // 1: kacho.cloud.vpc.v1.ListCidrGroupsRequest
	(*ListCidrGroupsResponse)(nil),           // 2: kacho.cloud.vpc.v1.ListCidrGroupsResponse
	(*CreateCidrGroupRequest)(nil),           // 3: kacho.cloud.vpc.v1.CreateCidrGroupRequest
	(*CreateCidrGroupMetadata)(nil),          // 4: kacho.cloud.vpc.v1.CreateCidrGroupMetadata
	(*UpdateCidrGroupRequest)(nil),           // 5: kacho.cloud.vpc.v1.UpdateCidrGroupRequest
	(*UpdateCidrGroupMetadata)(nil),          // 6: kacho.cloud.vpc.v1.UpdateCidrGroupMetadata
	(*AddCidrGroupCidrBlocksRequest)(nil),    // 7: kacho.cloud.vpc.v1.AddCidrGroupCidrBlocksRequest
	(*RemoveCidrGroupCidrBlocksRequest)(nil), // 8: kacho.cloud.vpc.v1.RemoveCidrGroupCidrBlocksRequest
	(*DeleteCidrGroupRequest)(nil),           // 9: kacho.cloud.vpc.v1.DeleteCidrGroupRequest
	(*DeleteCidrGroupMetadata)(nil),          // 10: kacho.cloud.vpc.v1.DeleteCidrGroupMetadata
	(*ListCidrGroupOperationsRequest)(nil),   // 11: kacho.cloud.vpc.v1.ListCidrGroupOperationsRequest
	(*ListCidrGroupOperationsResponse)(nil),  // 12: kacho.cloud.vpc.v1.ListCidrGroupOperationsResponse
	nil,                                      // 13: kacho.cloud.vpc.v1.CreateCidrGroupRequest.LabelsEntry
	nil,                                      // 14: kacho.cloud.vpc.v1.UpdateCidrGroupRequest.LabelsEntry
	(*CidrGroup)(nil),                        // 15: kacho.cloud.vpc.v1.CidrGroup
	(*fieldmaskpb.FieldMask)(nil),            // 16: google.protobuf.FieldMask
	(*operation.Operation)(nil),              // 17: kacho.cloud.operation.Operation
}
var file_kacho_cloud_vpc_v1_cidr_group_service_proto_depIdxs = []int32{
	15, // 0: kacho.cloud.vpc.v1.ListCidrGroupsResponse.cidr_groups:type_name -> kacho.cloud.vpc.v1.CidrGroup
	13, // 1: kacho.cloud.vpc.v1.CreateCidrGroupRequest.labels:type_name -> kacho.cloud.vpc.v1.CreateCidrGroupRequest.LabelsEntry
	16, // 2: kacho.cloud.vpc.v1.UpdateCidrGroupRequest.update_mask:type_name -> google.protobuf.FieldMask
	14, // 3: kacho.cloud.vpc.v1.UpdateCidrGroupRequest.labels:type_name -> kacho.cloud.vpc.v1.UpdateCidrGroupRequest.LabelsEntry
	17, // 4: kacho.cloud.vpc.v1.ListCidrGroupOperationsResponse.operations:type_name -> kacho.cloud.operation.Operation
	0,  // 5: kacho.cloud.vpc.v1.CidrGroupService.Get:input_type -> kacho.cloud.vpc.v1.GetCidrGroupRequest
	1,  // 6: kacho.cloud.vpc.v1.CidrGroupService.List:input_type -> kacho.cloud.vpc.v1.ListCidrGroupsRequest
	3,  // 7: kacho.cloud.vpc.v1.CidrGroupService.Create:input_type -> kacho.cloud.vpc.v1.CreateCidrGroupRequest
	5,  // 8: kacho.cloud.vpc.v1.CidrGroupService.Update:input_type -> kacho.cloud.vpc.v1.UpdateCidrGroupRequest
	7,  // 9: kacho.cloud.vpc.v1.CidrGroupService.AddCidrBlocks:input_type -> kacho.cloud.vpc.v1.AddCidrGroupCidrBlocksRequest
	8,  // 10: kacho.cloud.vpc.v1.CidrGroupService.RemoveCidrBlocks:input_type -> kacho.cloud.vpc.v1.RemoveCidrGroupCidrBlocksRequest
	9,  // 11: kacho.cloud.vpc.v1.CidrGroupService.Delete:input_type -> kacho.cloud.vpc.v1.DeleteCidrGroupRequest
	11, // 12: kacho.cloud.vpc.v1.CidrGroupService.ListOperations:input_type -> kacho.cloud.vpc.v1.ListCidrGroupOperationsRequest
	15, // 13: kacho.cloud.vpc.v1.CidrGroupService.Get:output_type -> kacho.cloud.vpc.v1.CidrGroup
	2,  // 14: kacho.cloud.vpc.v1.CidrGroupService.List:output_type -> kacho.cloud.vpc.v1.ListCidrGroupsResponse
	17, // 15: kacho.cloud.vpc.v1.CidrGroupService.Create:output_type -> kacho.cloud.operation.Operation
	17, // 16: kacho.cloud.vpc.v1.CidrGroupService.Update:output_type -> kacho.cloud.operation.Operation
	17, // 17: kacho.cloud.vpc.v1.CidrGroupService.AddCidrBlocks:output_type -> kacho.cloud.operation.Operation
	17, // 18: kacho.cloud.vpc.v1.CidrGroupService.RemoveCidrBlocks:output_type -> kacho.cloud.operation.Operation
	17, // 19: kacho.cloud.vpc.v1.CidrGroupService.Delete:output_type -> kacho.cloud.operation.Operation
	12, // 20: kacho.cloud.vpc.v1.CidrGroupService.ListOperations:output_type -> kacho.cloud.vpc.v1.ListCidrGroupOperationsResponse
	13, // [13:21] is the sub-list for method output_type
	5,  // [5:13] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_kacho_cloud_vpc_v1_cidr_group_service_proto_init() }
func file_kacho_cloud_vpc_v1_cidr_group_service_proto_init() {
	if File_kacho_cloud_vpc_v1_cidr_group_service_proto != nil {
		return
	}
	file_kacho_cloud_vpc_v1_cidr_group_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kacho_cloud_vpc_v1_cidr_group_service_proto_rawDesc), len(file_kacho_cloud_vpc_v1_cidr_group_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kacho_cloud_vpc_v1_cidr_group_service_proto_goTypes,
		DependencyIndexes: file_kacho_cloud_vpc_v1_cidr_group_service_proto_depIdxs,
		MessageInfos:      file_kacho_cloud_vpc_v1_cidr_group_service_proto_msgTypes,
	}.Build()
	File_kacho_cloud_vpc_v1_cidr_group_service_proto = out.File
	file_kacho_cloud_vpc_v1_cidr_group_service_proto_goTypes = nil
	file_kacho_cloud_vpc_v1_cidr_group_service_proto_depIdxs = nil
}
