# Copyright (c) PRO-Robotech
# SPDX-License-Identifier: BUSL-1.1
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-storage-config
data:
  KACHO_STORAGE_AUTH_MODE: {{ .Values.config.authMode | quote }}
  KACHO_STORAGE_GRPC_PORT: {{ .Values.ports.public | quote }}
  KACHO_STORAGE_INTERNAL_PORT: {{ .Values.ports.internal | quote }}
  KACHO_STORAGE_METRICS_ADDR: {{ printf ":%v" .Values.ports.metrics | quote }}
  KACHO_STORAGE_DB_HOST: {{ .Values.config.dbHost | quote }}
  KACHO_STORAGE_DB_PORT: {{ .Values.config.dbPort | quote }}
  KACHO_STORAGE_DB_USER: {{ .Values.config.dbUser | quote }}
  KACHO_STORAGE_DB_NAME: {{ .Values.config.dbName | quote }}
  KACHO_STORAGE_DB_SSLMODE: {{ .Values.config.dbSslMode | quote }}
  KACHO_STORAGE_GEO_GRPC_ADDR: {{ .Values.config.geoGrpcAddr | quote }}
  KACHO_STORAGE_IAM_GRPC_ADDR: {{ .Values.config.iamGrpcAddr | quote }}
  KACHO_STORAGE_AUTHZ_IAM_GRPC_ADDR: {{ .Values.config.authzIamGrpcAddr | quote }}
