# Copyright (c) PRO-Robotech
# SPDX-License-Identifier: BUSL-1.1
# Skeleton secret: DB-пароль. mTLS-материал (per-edge client/server certs) добавляет
# kacho-deploy при интеграции. Значение — placeholder; в проде через external-secrets
# / sealed-secrets, не в git.
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-storage-secret
type: Opaque
stringData:
  KACHO_STORAGE_DB_PASSWORD: {{ .Values.config.dbPassword | default "changeme" | quote }}
