# Copyright (c) PRO-Robotech
# SPDX-License-Identifier: BUSL-1.1
{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-storage
  labels:
    app: {{ .Release.Name }}-storage
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-storage
  endpoints:
    - port: metrics
      path: /metrics
      interval: {{ .Values.serviceMonitor.interval }}
{{- end }}
