# Copyright (c) PRO-Robotech
# SPDX-License-Identifier: BUSL-1.1
{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "storage.fullname" . }}
  labels:
    {{- include "storage.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ include "storage.fullname" . }}
  endpoints:
    - port: metrics
      path: /metrics
      interval: {{ .Values.serviceMonitor.interval }}
{{- end }}
