// Copyright (c) PRO-Robotech
// SPDX-License-Identifier: BUSL-1.1

// Package knownfailingsubject is the repository-wide gate for one rule: a
// declaration that a case is "known failing" must have a SUBJECT.
//
// # What a declaration is, and why it needs a mechanism
//
// A results doc may declare that a case is expected red because the product
// diverges from its contract. That is legitimate and required — testing.md forbids
// skipping such a case, so it stays red and stays visible, and the declaration is
// what tells a reader the red is understood rather than new.
//
// What is not legitimate is a declaration nobody checks. It is not documentation:
// it is an ASSERTION ABOUT THE PRODUCT, written in prose, that no mechanism can
// contradict. Two ways it goes wrong, both observed in this tree:
//
//   - it outlives its fix. The defect is repaired, the row keeps saying the product
//     is broken, and the next reader either plans work already done or discounts a
//     genuine red as "the known one". One such row lived a day past its fix here and
//     queued work that was not needed.
//   - it never had a subject. The named case was renamed or deleted, so the row
//     excuses a case that cannot fail, cannot pass and cannot be looked at. Three of
//     those were standing when this gate was written.
//
// A subtraction in the suite runner used to make these rows load-bearing. That
// mechanism was removed — it keyed on a NAME while claiming to select by REASON, so
// it could not tell its subject from a stranger at any width. Removing it left the
// rows with no mechanism at all, which is what this gate supplies.
//
// # What is checked
//
//  1. SUBJECT EXISTS. Every case id a declaration names must be generated by that
//     suite's collections. A section that declares known-failing and names no
//     checkable subject at all is itself a finding — otherwise the unreadable part of
//     these files is exactly where declarations would go to hide.
//  2. SUBJECT IS STILL RED. Where a run left a report under out/, a declared case
//     that EXECUTED and produced no failed assertion is a finding: the declaration
//     outlived its subject. A case that did not run is NOT a pass — it is announced
//     as unverified and never folded into the verdict.
//  3. THE RECORD CAN EXPIRE. Every declaration names at least one tracker issue WITH
//     its repository (`kacho#11`, `kacho-iam#276`, or an issue URL). A bare `#11` is
//     not accepted: it cannot be resolved, and prose in these files says things like
//     "ban #6" which are not issues at all. A closed issue is a finding.
//
// # The gate's own premise, stated so it can be falsified
//
// Names in these docs are written in backticks; that is what makes a record readable
// by anything other than a human. Of the backticked tokens:
//
//   - a CASE ID is UPPER-KEBAB with at least two dashes (`NLB-CR-CRUD-OK`,
//     `AUTHZ-NIC-LS-OWN-AAB`) and MUST resolve — one that resolves to nothing is the
//     finding in check (1);
//   - any other name-shaped token (at least one dash, none of `._<>(){}@#$ `) is a
//     subject only WHEN IT RESOLVES, against a step name or a whole collection name.
//     Prose wears the same shape (`read-your-writes`, `PRO-Robotech`), so flagging
//     unresolvable ones would teach contributors to write around the matcher.
//
// The hole that asymmetry could leave — a record naming only a step or collection
// that has since been renamed — is closed one level up: a declaring section that
// yields no declaration at all fails.
//
// Sections are H2 and deeper (an H1 is the document title), and a NEUTRAL subsection
// of a declaring section stays declaring, because that is where these files actually
// keep their lists.
//
// A table row, a bullet, a blockquote and a paragraph are all read the same way: a
// declaration must not escape by changing its markdown shape.
//
// Text saying the red is already resolved marks a RECORD rather than a declaration —
// as a heading for a whole section, or inside one row for that row alone. History is
// allowed, and required, to name cases that now pass. Every such skip is counted, so it
// cannot become a quiet way out.
//
// A heading is read case-insensitively ("Closed — was known failing"); one record must
// carry the word as a VERDICT, in capitals (**FIXED 2026-07-29**, RECONCILED, СНЯТО).
// The asymmetry is not cosmetic: read case-insensitively, a record quoting an error
// message that happens to contain "resolved" would exempt itself, and one on this tree
// did exactly that.
//
// # Census
//
// The gate states what it read: suites, docs, collections, reports, declarations,
// resolved subjects, skipped resolution records. Reading nothing is a finding —
// "zero findings" must never be reachable from "zero files".
//
// # Relationship to the per-suite gate in services/storage
//
// services/storage/tools/auditknownfailing asks different questions about the same
// rows for one suite: roster parity with the generated collections, and a two-way
// binding to `# verifies <issue-url>` annotations in cases/. That contract is
// stricter and only that suite adopted it. This gate asks the repository-wide
// question — does the declaration have a subject, and is the subject still red — and
// does not require the annotation. Both check liveness; neither subsumes the other.
package knownfailingsubject

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"time"
)

// IssueState is what the tracker says about a referenced issue.
type IssueState int

const (
	// StateUnknown — the tracker could not be consulted (environment, not verdict).
	StateUnknown IssueState = iota
	// StateOpen — the defect is still open, so the declaration still has a subject.
	StateOpen
	// StateClosed — fixed, or the issue does not exist: nothing left to declare.
	StateClosed
)

// Options configures one run.
type Options struct {
	// Root is the repository root.
	Root string
	// IssueState resolves one issue in one repository slug. nil ⇒ the `gh` CLI.
	IssueState func(repo string, num int) (IssueState, error)
}

// Census is the volume the gate examined. Printed always: "nothing declared" and
// "nothing read" exit the same way and must never print the same thing.
type Census struct {
	Suites            int
	Docs              int
	Collections       int
	Reports           int
	DeclaringSections int
	ArchivedSections  int
	Declarations      int
	SubjectsResolved  int
	IssuesChecked     int
}

// Report is the census, the findings, and the dimensions that could not be resolved.
type Report struct {
	Census     Census
	Findings   []string
	Unverified []string
}

var (
	// caseIDRe is the shape of a case id in these suites: UPPER-KEBAB, ≥2 dashes.
	caseIDRe = regexp.MustCompile(`^[A-Z][A-Z0-9]*(?:-[A-Z0-9]+){2,}$`)
	// tickedRe pulls the backticked tokens out of a record: every name in these docs
	// is written in backticks, which is what makes the record machine-readable.
	tickedRe = regexp.MustCompile("`([^`\n]+)`")
	// issueRe accepts an issue reference that names its repository. A bare "#11" is
	// deliberately NOT accepted — see the package doc.
	issueRe = regexp.MustCompile(`(?:PRO-Robotech/)?(kacho(?:-[a-z]+)?)(?:#|/issues/)(\d+)`)
	// declaringRe matches a heading that declares known-failing cases.
	declaringRe = regexp.MustCompile(`(?i)known[ -]?fail|known[ -]?red|известн\w*[ -]?красн`)
	// archivedHeadingRe matches a HEADING that turns its whole section into a record of
	// something already closed. A heading is a title, so the word is read
	// case-insensitively ("Closed — was known failing").
	archivedHeadingRe = regexp.MustCompile(
		`(?i)\bclosed\b|\bresolved\b|\bfixed\b|\bretired\b|\bremoved\b|\breconciled\b|` +
			`закрыт|исправлен|снят|удал[её]н|устран[её]н`)
	// archivedRecordRe matches ONE record that states its own disposition. Here the word
	// must be a VERDICT, which these docs write in capitals (**FIXED 2026-07-29**,
	// **TEST-ASSERTION FIXED**, RECONCILED, СНЯТО) — deliberately case-SENSITIVE.
	//
	// Case-insensitive would exempt a live declaration on prose: measured on this tree, a
	// flagged IPAM record went unread because the error message it quoted contained the
	// word "resolved". An exemption that fires on the vocabulary of the defect rather than
	// on a decision about it is not an exemption, it is a blind spot.
	archivedRecordRe = regexp.MustCompile(
		`\bFIXED\b|\bRESOLVED\b|\bCLOSED\b|\bRETIRED\b|\bREMOVED\b|\bRECONCILED\b|` +
			`ЗАКРЫТ|ИСПРАВЛЕН|СНЯТ|УДАЛ[ЕЁ]Н|УСТРАНЕН`)
	whitespace = regexp.MustCompile(`\s`)
)

// leafRef locates one request inside one collection, by cursor position.
type leafRef struct {
	collection string
	position   int
}

// issueRef is one tracker reference, repository included.
type issueRef struct {
	repo string
	num  int
}

// declaration is one row, bullet or paragraph that names at least one subject.
type declaration struct {
	doc     string
	line    int
	section int
	// caseIDs are UPPER-KEBAB names, which MUST resolve.
	caseIDs []string
	// softCandidates are name-shaped tokens that are not case ids — a step name or a
	// collection name. They count as subjects only WHEN THEY RESOLVE, because prose in
	// these docs wears the same shape (`read-your-writes`, `PRO-Robotech`).
	softCandidates []string
	issues         []issueRef
}

// Scan runs the gate over Root.
func Scan(o Options) (Report, error) {
	rep := Report{}
	resolve := o.IssueState
	if resolve == nil {
		resolve = ghResolver()
	}

	suites := discoverSuites(o.Root)
	rep.Census.Suites = len(suites)

	issues := map[issueRef][]string{}

	for _, rel := range suites {
		base := filepath.Join(o.Root, rel)
		docRel := filepath.ToSlash(filepath.Join(rel, "docs", "RESULTS.md"))
		// #nosec G304 -- гейт читает документ отчёта своей же сюиты; путь из обхода дерева.
		raw, err := os.ReadFile(filepath.Join(base, "docs", "RESULTS.md"))
		if err != nil {
			continue
		}
		rep.Census.Docs++

		idx, nColl := readSuite(base)
		rep.Census.Collections += nColl
		reports, nReports := readReports(base, idx)
		rep.Census.Reports += nReports

		records, sections, archived := parseRecords(docRel, string(raw))
		rep.Census.DeclaringSections += len(sections)
		rep.Census.ArchivedSections += archived

		perSection := map[int]int{}
		for _, r := range records {
			subjects, named := subjectsOf(r, idx)
			if !named {
				continue // prose inside a declaring section, not a declaration
			}
			rep.Census.Declarations++
			perSection[r.section]++

			if len(r.issues) == 0 {
				rep.Findings = append(rep.Findings, fmt.Sprintf(
					"%s:%d: known-failing declaration names no issue with its repository "+
						"(expected `kacho#N` / `kacho-iam#N` / an issue URL) — a declaration nobody "+
						"can check never expires", r.doc, r.line))
			}
			for _, ir := range r.issues {
				issues[ir] = append(issues[ir], fmt.Sprintf("%s:%d", r.doc, r.line))
			}

			for _, subj := range subjects {
				refs, ok := idx.resolve(subj)
				if !ok {
					rep.Findings = append(rep.Findings, fmt.Sprintf(
						"%s:%d: known-failing declaration names case %q, which this suite does not "+
							"generate — the declaration outlived its subject (delete it, or declare it in "+
							"the suite that generates the case)", r.doc, r.line, subj))
					continue
				}
				rep.Census.SubjectsResolved++
				switch v, where := judge(reports, subj, refs); v {
				case subjectPassed:
					rep.Findings = append(rep.Findings, fmt.Sprintf(
						"%s:%d: known-failing declaration names case %q, which ran and PASSED in %s — a "+
							"declaration that outlived its fix is a false statement about the product; "+
							"delete it", r.doc, r.line, subj, where))
				case subjectNotRun:
					rep.Unverified = append(rep.Unverified, fmt.Sprintf(
						"%s:%d: case %q did not run in %s — \"still red\" is UNPROVEN, not proven",
						r.doc, r.line, subj, where))
				case subjectNoReport:
					rep.Unverified = append(rep.Unverified, fmt.Sprintf(
						"%s:%d: case %q has no run report under %s/out — \"still red\" is UNPROVEN, "+
							"not proven", r.doc, r.line, subj, filepath.ToSlash(rel)))
				}
			}
		}

		for _, s := range sections {
			if perSection[s.line] == 0 {
				rep.Findings = append(rep.Findings, fmt.Sprintf(
					"%s:%d: section %q declares known-failing cases but names no subject this gate can "+
						"check — a declaration whose subject cannot be named is an unfalsifiable statement "+
						"about the product", docRel, s.line, s.title))
			}
		}
	}

	rep.Census.IssuesChecked = len(issues)
	for _, ir := range sortedRefs(issues) {
		state, err := resolve(ir.repo, ir.num)
		switch {
		case err != nil || state == StateUnknown:
			reason := "tracker unreachable"
			if err != nil {
				reason = err.Error()
			}
			rep.Unverified = append(rep.Unverified, fmt.Sprintf(
				"issue %s#%d (%s): %s — \"still open\" is UNPROVEN, not proven",
				ir.repo, ir.num, strings.Join(issues[ir], ", "), reason))
		case state == StateClosed:
			rep.Findings = append(rep.Findings, fmt.Sprintf(
				"issue %s#%d is no longer open, but it is still declared at %s — a known-failing "+
					"declaration that outlived its fix is a false statement about the product; delete it",
				ir.repo, ir.num, strings.Join(issues[ir], ", ")))
		}
	}

	if rep.Census.Docs == 0 {
		rep.Findings = append(rep.Findings, fmt.Sprintf(
			"read 0 results doc(s) across %d suite dir(s) under %s — the gate examined nothing, so it "+
				"proved nothing (zero findings must not be reachable from zero reads)",
			rep.Census.Suites, o.Root))
	}

	if len(rep.Findings) == 0 {
		return rep, nil
	}
	return rep, fmt.Errorf("known-failing-subject: %d finding(s)", len(rep.Findings))
}

// subjectsOf returns the subjects a record names: every UPPER-KEBAB case id, plus
// the lowercase candidates that actually resolve. `named` reports whether the record
// is a declaration at all.
func subjectsOf(r declaration, idx suiteIndex) (subjects []string, named bool) {
	subjects = append(subjects, r.caseIDs...)
	for _, c := range r.softCandidates {
		if _, ok := idx.resolve(c); ok {
			subjects = append(subjects, c)
		}
	}
	return dedupe(subjects), len(subjects) > 0
}

// ─── the documents ───────────────────────────────────────────────────────────

// section is one heading that declares known-failing cases.
type section struct {
	line  int
	title string
}

// parseRecords walks the doc tracking the current heading and returns every record
// inside a declaring section: a table row, a bullet with its indented continuations, a
// blockquote, or a paragraph. All four are treated ALIKE — a declaration must not be
// able to escape the gate by changing its markdown shape. Records naming no candidate
// token are dropped by the caller; records that say the red is already resolved are
// dropped here, because a record of a fix is allowed to name a case that now passes.
//
// Sections are H2 and deeper: an H1 is the document's title, not a section declaring
// cases. A neutral SUBSECTION of a declaring section stays declaring — that is where
// these files actually put their lists — while an archival subsection closes it.
func parseRecords(doc, body string) (records []declaration, declaring []section, archived int) {
	lines := strings.Split(body, "\n")
	current := section{}
	declLevel := 0

	i := 0
	for i < len(lines) {
		trimmed := strings.TrimSpace(lines[i])

		if lvl := headingLevel(trimmed); lvl > 0 {
			title := strings.TrimSpace(strings.TrimLeft(trimmed, "# "))
			switch {
			case lvl == 1:
				declLevel = 0
			case archivedHeadingRe.MatchString(title):
				if declaringRe.MatchString(title) || declLevel > 0 {
					archived++
				}
				declLevel = 0
			case declaringRe.MatchString(title):
				declLevel = lvl
				current = section{line: i + 1, title: title}
				declaring = append(declaring, current)
			case declLevel > 0 && lvl > declLevel:
				// A neutral subsection of a declaring section belongs to it.
			default:
				declLevel = 0
			}
			i++
			continue
		}

		if declLevel == 0 || trimmed == "" {
			i++
			continue
		}

		start := i
		text := lines[i]
		switch {
		case strings.HasPrefix(trimmed, "|"):
			// One table row is one record. Header and separator rows carry no
			// backticked name, so they drop out by themselves.
		case strings.HasPrefix(trimmed, "- "), strings.HasPrefix(trimmed, "* "):
			for i+1 < len(lines) && isContinuation(lines[i+1]) {
				i++
				text += "\n" + lines[i]
			}
		case strings.HasPrefix(trimmed, ">"):
			for i+1 < len(lines) && strings.HasPrefix(strings.TrimSpace(lines[i+1]), ">") {
				i++
				text += "\n" + lines[i]
			}
		default:
			// A paragraph. Present-tense declarations in these files are sometimes
			// written as one, so a paragraph is a record like any other.
			for i+1 < len(lines) {
				nxt := strings.TrimSpace(lines[i+1])
				if nxt == "" || strings.HasPrefix(nxt, "#") || strings.HasPrefix(nxt, "|") ||
					strings.HasPrefix(nxt, "- ") || strings.HasPrefix(nxt, "* ") ||
					strings.HasPrefix(nxt, ">") {
					break
				}
				i++
				text += "\n" + lines[i]
			}
		}

		if archivedRecordRe.MatchString(unwrap(text)) {
			archived++
			i++
			continue
		}

		rec := declaration{doc: doc, line: start + 1, section: current.line}
		for _, m := range tickedRe.FindAllStringSubmatch(unwrap(text), -1) {
			for _, tok := range tokens(m[1]) {
				switch {
				case caseIDRe.MatchString(tok):
					rec.caseIDs = append(rec.caseIDs, tok)
				case nameShaped(tok):
					rec.softCandidates = append(rec.softCandidates, tok)
				}
			}
		}
		for _, m := range issueRe.FindAllStringSubmatch(text, -1) {
			if n, err := strconv.Atoi(m[2]); err == nil {
				rec.issues = append(rec.issues, issueRef{repo: "PRO-Robotech/" + m[1], num: n})
			}
		}
		rec.caseIDs = dedupe(rec.caseIDs)
		rec.softCandidates = dedupe(rec.softCandidates)
		records = append(records, rec)
		i++
	}
	return records, declaring, archived
}

// unwrap folds a multi-line record into one line, dropping blockquote markers and
// leading indentation. It is what makes backtick pairing reliable: these docs are
// hard-wrapped, so a backticked span — usually a quoted error message — routinely
// straddles a line break. Matched line by line, that span never closes, EVERY following
// pair is offset by one, and the case id after it is read as prose. Measured here: a
// flagged record named three cases and only the first was ever seen.
func unwrap(text string) string {
	lines := strings.Split(text, "\n")
	for i, l := range lines {
		l = strings.TrimSpace(l)
		l = strings.TrimPrefix(l, ">")
		lines[i] = strings.TrimSpace(l)
	}
	return strings.Join(lines, " ")
}

// tokens splits one backticked span into candidate names.
func tokens(span string) []string {
	parts := strings.FieldsFunc(span, func(r rune) bool {
		return r == ' ' || r == '/' || r == ',' || r == ':' || r == '\n' || r == '\t'
	})
	out := make([]string, 0, len(parts))
	for _, p := range parts {
		out = append(out, strings.Trim(p, "*_.,;()[]`"))
	}
	return out
}

// isContinuation reports whether a line continues the bullet above it.
func isContinuation(line string) bool {
	if strings.TrimSpace(line) == "" {
		return false
	}
	if !strings.HasPrefix(line, " ") && !strings.HasPrefix(line, "\t") {
		return false
	}
	t := strings.TrimSpace(line)
	return !strings.HasPrefix(t, "- ") && !strings.HasPrefix(t, "* ")
}

// nameShaped is the shape a step or collection name wears: at least one dash and none
// of the characters those names never carry. Membership here is NOT enough to be a
// subject — it must also resolve against the generated collections (see the package
// doc), which is what keeps prose out.
func nameShaped(tok string) bool {
	return !strings.ContainsAny(tok, "._<>{}()@#$ ") && strings.Contains(tok, "-")
}

// headingLevel returns 1..6 for an ATX heading line, 0 for anything else.
func headingLevel(trimmed string) int {
	n := 0
	for n < len(trimmed) && trimmed[n] == '#' {
		n++
	}
	if n == 0 || n > 6 {
		return 0
	}
	if n < len(trimmed) && trimmed[n] != ' ' {
		return 0
	}
	return n
}

// ─── the suites ──────────────────────────────────────────────────────────────

// suiteIndex is what a suite generates: the names a declaration may name, mapped to
// the requests they cover, plus each collection's leaf count.
type suiteIndex struct {
	folders       map[string][]leafRef
	steps         map[string][]leafRef
	collections   map[string][]leafRef
	perCollection map[string]int
}

func (s suiteIndex) resolve(subject string) ([]leafRef, bool) {
	if refs, ok := s.folders[subject]; ok {
		return refs, true
	}
	if refs, ok := s.steps[subject]; ok {
		return refs, true
	}
	// A declaration may name a whole collection ("the registry-repository suite is
	// red"), which is a real granularity: the report for that collection answers it.
	if refs, ok := s.collections[subject]; ok {
		return refs, true
	}
	return nil, false
}

// readSuite flattens every generated collection of one suite in cursor order.
func readSuite(base string) (suiteIndex, int) {
	idx := suiteIndex{
		folders:       map[string][]leafRef{},
		steps:         map[string][]leafRef{},
		collections:   map[string][]leafRef{},
		perCollection: map[string]int{},
	}
	entries, err := os.ReadDir(filepath.Join(base, "collections"))
	if err != nil {
		return idx, 0
	}
	count := 0
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".postman_collection.json") {
			continue
		}
		name := strings.TrimSuffix(e.Name(), ".postman_collection.json")
		// #nosec G304 -- гейт читает свой же каталог коллекций; путь из обхода дерева.
		raw, rerr := os.ReadFile(filepath.Join(base, "collections", e.Name()))
		if rerr != nil {
			continue
		}
		var c struct {
			Item []json.RawMessage `json:"item"`
		}
		if json.Unmarshal(raw, &c) != nil {
			continue
		}
		count++
		pos := 0
		for _, it := range c.Item {
			pos = walkItem(&idx, name, it, pos)
		}
		idx.perCollection[name] = pos
		for p := 0; p < pos; p++ {
			idx.collections[name] = append(idx.collections[name], leafRef{collection: name, position: p})
		}
	}
	return idx, count
}

// walkItem descends one collection item, recording leaves in cursor order. Every
// named group on the way down claims the leaves under it, because a declaration may
// name an outer case folder or an inner group, and newman books a failure under the
// name of the group that owns the request.
func walkItem(idx *suiteIndex, collection string, raw json.RawMessage, pos int) int {
	var it struct {
		Name    string            `json:"name"`
		Item    []json.RawMessage `json:"item"`
		Request json.RawMessage   `json:"request"`
	}
	if json.Unmarshal(raw, &it) != nil {
		return pos
	}
	if len(it.Item) > 0 {
		start := pos
		for _, sub := range it.Item {
			pos = walkItem(idx, collection, sub, pos)
		}
		if key := firstToken(it.Name); key != "" {
			for p := start; p < pos; p++ {
				idx.folders[key] = append(idx.folders[key], leafRef{collection: collection, position: p})
			}
		}
		return pos
	}
	if len(it.Request) == 0 {
		return pos
	}
	ref := leafRef{collection: collection, position: pos}
	idx.steps[it.Name] = append(idx.steps[it.Name], ref)
	if key := firstToken(it.Name); key != it.Name && key != "" {
		idx.steps[key] = append(idx.steps[key], ref)
	}
	return pos + 1
}

// firstToken is the case id part of a folder name ("<CASE-ID> — description").
func firstToken(name string) string {
	parts := whitespace.Split(strings.TrimSpace(name), 2)
	if len(parts) == 0 {
		return ""
	}
	return parts[0]
}

// ─── the reports ─────────────────────────────────────────────────────────────

// runReport is what one newman JSON report says about one collection.
type runReport struct {
	path string
	// executed holds cursor positions that produced a response. A position newman
	// attempted that never answered is deliberately NOT in here: an unanswered request
	// is not evidence that the case ran, so it falls through to "did not run".
	executed map[int]bool
	// failed holds the names a failed assertion was booked under (folder and step).
	failed map[string]bool
}

// readReports loads out/*.json for one suite, keyed by collection name. A report
// whose cursors describe a different number of requests than the committed
// collection is stale and its execution evidence is dropped — a stale report must
// not be able to declare a case "passed".
func readReports(base string, idx suiteIndex) (map[string]*runReport, int) {
	out := map[string]*runReport{}
	entries, err := os.ReadDir(filepath.Join(base, "out"))
	if err != nil {
		return out, 0
	}
	n := 0
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".json") {
			continue
		}
		name := strings.TrimSuffix(e.Name(), ".json")
		path := filepath.Join(base, "out", e.Name())
		// #nosec G304 -- гейт читает отчёты прогона своей же сюиты; путь из обхода дерева.
		raw, rerr := os.ReadFile(path)
		if rerr != nil {
			continue
		}
		var doc struct {
			Run struct {
				Executions []struct {
					Cursor struct {
						Position *int `json:"position"`
						Length   *int `json:"length"`
					} `json:"cursor"`
					Response     json.RawMessage `json:"response"`
					RequestError json.RawMessage `json:"requestError"`
				} `json:"executions"`
				Failures []struct {
					Source struct {
						Name string `json:"name"`
					} `json:"source"`
					Parent struct {
						Name string `json:"name"`
					} `json:"parent"`
				} `json:"failures"`
			} `json:"run"`
		}
		if json.Unmarshal(raw, &doc) != nil {
			continue
		}
		n++
		r := &runReport{
			path: filepath.ToSlash(path), executed: map[int]bool{}, failed: map[string]bool{},
		}
		length := 0
		for _, ex := range doc.Run.Executions {
			if ex.Cursor.Length != nil {
				length = *ex.Cursor.Length
			}
			if ex.Cursor.Position == nil {
				continue
			}
			if len(ex.Response) > 0 && string(ex.Response) != "null" && len(ex.RequestError) == 0 {
				r.executed[*ex.Cursor.Position] = true
			}
		}
		for _, f := range doc.Run.Failures {
			r.failed[firstToken(f.Parent.Name)] = true
			r.failed[f.Source.Name] = true
			r.failed[firstToken(f.Source.Name)] = true
		}
		if length != 0 && idx.perCollection[name] != 0 && length != idx.perCollection[name] {
			r.executed = map[int]bool{}
		}
		out[name] = r
	}
	return out, n
}

type verdict int

const (
	subjectNoReport verdict = iota
	subjectNotRun
	subjectStillRed
	subjectPassed
)

// judge decides what the reports say about one declared subject. Only the report of
// the collection the subject lives in is consulted: another suite's green report is
// not evidence about this case.
func judge(reports map[string]*runReport, subject string, refs []leafRef) (verdict, string) {
	var own []*runReport
	seen := map[string]bool{}
	for _, ref := range refs {
		if seen[ref.collection] {
			continue
		}
		seen[ref.collection] = true
		if r, ok := reports[ref.collection]; ok {
			own = append(own, r)
		}
	}
	if len(own) == 0 {
		return subjectNoReport, ""
	}
	for _, r := range own {
		if r.failed[subject] {
			return subjectStillRed, r.path
		}
	}
	for _, r := range own {
		for _, ref := range refs {
			if ref.collection != "" && r.executed[ref.position] {
				return subjectPassed, r.path
			}
		}
	}
	return subjectNotRun, own[0].path
}

// ─── discovery, tracker, output ──────────────────────────────────────────────

// discoverSuites finds every newman suite in the tree.
func discoverSuites(root string) []string {
	var out []string
	if _, err := os.Stat(filepath.Join(root, "gateway", "tests", "newman")); err == nil {
		out = append(out, filepath.Join("gateway", "tests", "newman"))
	}
	entries, err := os.ReadDir(filepath.Join(root, "services"))
	if err != nil {
		return out
	}
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		rel := filepath.Join("services", e.Name(), "tests", "newman")
		if _, serr := os.Stat(filepath.Join(root, rel)); serr == nil {
			out = append(out, rel)
		}
	}
	sort.Strings(out)
	return out
}

// ghResolver asks the GitHub CLI for one issue's state.
func ghResolver() func(string, int) (IssueState, error) {
	return func(repo string, n int) (IssueState, error) {
		if _, err := exec.LookPath("gh"); err != nil {
			return StateUnknown, fmt.Errorf("gh CLI not available")
		}
		ctx, cancel := context.WithTimeout(context.Background(), 20*time.Second)
		defer cancel()
		// #nosec G204 -- аргументы фиксированы: номер приходит числом, слаг репозитория
		// собран из каталога, оболочки нет.
		cmd := exec.CommandContext(ctx, "gh", "issue", "view", strconv.Itoa(n),
			"--repo", repo, "--json", "state", "-q", ".state")
		raw, err := cmd.Output()
		if err != nil {
			return StateUnknown, fmt.Errorf("gh issue view %s#%d failed", repo, n)
		}
		switch strings.ToUpper(strings.TrimSpace(string(raw))) {
		case "OPEN":
			return StateOpen, nil
		case "CLOSED":
			return StateClosed, nil
		}
		return StateUnknown, fmt.Errorf("gh returned an unrecognised state for %s#%d", repo, n)
	}
}

// Print writes the census, the unverified dimensions, then the findings.
func Print(rep Report, out io.Writer) {
	c := rep.Census
	_, _ = fmt.Fprintf(out, "known-failing-subject: read %d suite(s), %d results doc(s), %d "+
		"collection(s), %d run report(s); %d declaring section(s), %d resolution record(s) skipped, "+
		"%d declaration(s), %d subject(s) resolved, %d issue(s) checked\n",
		c.Suites, c.Docs, c.Collections, c.Reports, c.DeclaringSections, c.ArchivedSections,
		c.Declarations, c.SubjectsResolved, c.IssuesChecked)

	if len(rep.Unverified) > 0 {
		_, _ = fmt.Fprintf(out, "known-failing-subject: NOT VERIFIED for %d item(s) — printed so that "+
			"\"the check did not run\" cannot read as \"the check passed\":\n", len(rep.Unverified))
		for _, u := range rep.Unverified {
			_, _ = fmt.Fprintf(out, "  %s\n", u)
		}
	}
	if len(rep.Findings) == 0 {
		_, _ = fmt.Fprintln(out, "known-failing-subject: OK")
		return
	}
	for _, f := range rep.Findings {
		_, _ = fmt.Fprintf(out, "known-failing-subject: %s\n", f)
	}
	_, _ = fmt.Fprint(out, explanation)
}

const explanation = `
A "known failing" declaration buys a case out of "everything must be green", so it
must be checkable and it must expire by itself:
  - it names a case this suite generates (a renamed or deleted case leaves the
    declaration excusing nothing);
  - it names its issue WITH the repository (` + "`kacho#11`, `kacho-iam#276`" + `), and that
    issue is still open;
  - where a run report exists, the named case is still red. A case that ran and
    passed means the declaration outlived its fix — delete it, do not "update" it.
Sections whose heading records a red as resolved are history and are not checked.
`

func dedupe(in []string) []string {
	seen := map[string]bool{}
	out := make([]string, 0, len(in))
	for _, s := range in {
		if !seen[s] {
			seen[s] = true
			out = append(out, s)
		}
	}
	return out
}

func sortedRefs[V any](m map[issueRef]V) []issueRef {
	out := make([]issueRef, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Slice(out, func(i, j int) bool {
		if out[i].repo != out[j].repo {
			return out[i].repo < out[j].repo
		}
		return out[i].num < out[j].num
	})
	return out
}
