# KAC-127 Phase 3 (acceptance §4.6 R6, design §4.1 #6)
# Deny: destructive ops on _prod-suffixed projects outside business hours
#       unless principal has break_glass_active.
#
# THIS POLICY IS NOT EVALUATED BY ANYTHING TODAY. Read that before reading the
# rest of the file, because everything below describes a control that does not
# run: the OPA guardrail overlay was removed from the authorization pipeline
# (services/iam/internal/service/authorize_service.go — "FGA is the sole policy
# gate"), the bundle service it was fed from is gone
# (services/iam/cmd/kaname/grpc_register.go — "OpaBundleService ... removed"),
# and `opaSidecar.enabled` is false in the chart default and in every umbrella
# values file, with no profile overriding it. So there is no out-of-hours
# restriction on destructive operations — not for block storage, and not for
# instances, networks or subnets either.
#
# The set below is kept correct rather than left to rot, so that whoever re-wires
# the overlay starts from a true list instead of one that quietly lost a domain.
# It is NOT evidence that the domains named in it are protected.
#
# Rationale: ChangeRiskOps™ — destructive ops on prod projects are the highest-
# risk class of action. Restricting to business hours forces "follow the sun"
# operator presence during the change, reduces blast radius of mistakes when
# fewer responders are awake. break_glass_active is the explicit emergency
# bypass (requires §R4 max-2h limit + 2-person approval Phase 7).
#
# Business hours are per-account (timezone, start_h, end_h) — sourced from
# data/timezones.json bundle data section, generated by kaname from
# per-account configuration. (The legacy B2B-tenant table was removed in
# RBAC-2026 Contract-B; business hours now key off the principal's timezone.)

package kacho.iam.guardrails

import rego.v1

# Scoped to destructive ops in the vpc, compute and storage domains. Extend with
# NLB delete + Address release etc. as those resources grow prod-only invariants.
#
# `compute.disks.delete` used to be here and is gone: compute no longer serves
# block storage, and that permission has zero entries in the permission catalog.
# Block storage is kacho-storage's, so the destructive block-storage permissions
# are storage.volumes.delete / storage.snapshots.delete / storage.images.delete —
# named here so the list matches the platform rather than its history.
destructive_prod_ops := {
	"vpc.networks.delete",
	"vpc.subnets.delete",
	"compute.instances.delete",
	"storage.volumes.delete",
	"storage.snapshots.delete",
	"storage.images.delete",
}

deny contains msg if {
	input.action in destructive_prod_ops
	endswith(input.resource.project_id, "_prod")
	not within_business_hours(input.principal.timezone)
	not input.principal.break_glass_active
	msg := "destructive ops on prod projects require business hours or break-glass"
}

# within_business_hours(tz) — true iff current_time (from input.context) is
# within the [start_h, end_h) range in the named timezone.
# Data shape (data/timezones.json):
#   {"business_hours": {"Europe/Moscow": {"start_h": 10, "end_h": 19}, ...}}
#
# OPA's built-in time.* functions handle TZ-aware hour extraction; bundle
# generator populates the timezones map keyed by the principal's timezone.
within_business_hours(tz) if {
	bh := data.kacho.iam.guardrails.data.timezones.business_hours[tz]
	# input.context.current_time_ns — Unix nanoseconds (set by interceptor).
	clock := time.clock([input.context.current_time_ns, tz])
	hour := clock[0]
	hour >= bh.start_h
	hour < bh.end_h
}
